### ISSUE TITLE
2960677249

### ISSUE THREAD

**Issue by sainting4** [Le-niao/Yunzai-Bot#1]
能教我嘛我是萌新

**Comment by Le-niao** [comment]
有什么问题...

**Comment by sainting4** [comment]
> 
> 
> 有什么问题...

ReplyError: ERR invalid password
    at parseError (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:302:14)

**Comment by Le-niao** [comment]
> > 有什么问题...
> 
> ReplyError: ERR invalid password at parseError (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:179:12) at parseType (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:302:14)

redis密码不对
没有密码的填一个空字符串

**Comment by sainting4** [comment]
> 
> 
> > > 有什么问题...
> > 
> > 
> > ReplyError: ERR invalid password at parseError (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:179:12) at parseType (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:302:14)
> 
> redis密码不对 没有密码的填一

> 
> 
> > > 有什么问题...
> > 
> > 
> > ReplyError: ERR invalid password at parseError (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:179:12) at parseType (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:302:14)
> 
> redis密码不对 没有密码的填一个空字符串

能不能加一下QQ，帮我看看问题在哪里，我的可以用了还是不行.我的QQ2960677249

**Comment by sainting4** [comment]
> 
> 
> > > 有什么问题...
> > 
> > 
> > ReplyError: ERR invalid password at parseError (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:179:12) at parseType (G:\123\Yunzai-Bot\node_modules\redis-parser\lib\parser.js:302:14)
> 
> redis密码不对 没有密码的填一个空字符串

(node:17792) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by Le-niao** [comment]
> (node:17792) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time

升级下nodejs

**Comment by sainting4** [comment]
> 
> 
> > (node:17792) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
> 
> 升级下nodejs

现在跟游戏内数据相关的全部用不了
