### ISSUE TITLE
大佬，没办法绑定stoken

### ISSUE THREAD

**Issue by Dream-yyk** [Le-niao/Yunzai-Bot#1003]
新stoken发送之后显示绑定成功，但是米币查询显示stoken失效，#更新抽卡记录显示authkey失效，目前只有老的cookie还能正常查询体力

**Comment by Dream-yyk** [comment]
用ck和stoken获取工具获取到的cookie发给云崽回复请先登录米游社或登录通行证再获取cookie

**Comment by ctrlcvs** [comment]
新stoken?v2sk? 
抓包获取的还是说通过教程文档获取的，目前并不支持抓包获取的stoken绑定
其次教程获取的话如果一直不行可以看看文件是否存在之类的 `xiaoyao-cvs-plugin/data/yaml/'qq'.yaml`
`stoken`目前的逻辑是按照uid走的如果说一直不行的话可以看下`uid`绑定的`stoken`是否匹配。
如果说匹配的话尝试更新`plugin`后再操作看看如果还是不行的话请移步到 [这里](https://github.com/ctrlcvs/xiaoyao-cvs-plugin.git)提`issue` 
因为我个人最近不是很闲，这周末会考虑是否兼容`v2stoken`的逻辑具体看情况 

另外关于`cookie`问题，因为目前的话米游社加了`httponly`导致说原有的教程js代码去获取cookie不全而导致失效
目前推荐的话是通过获取`stoken`进行绑定后通过`#刷新ck`的方式
安卓获取的话我推荐是用最新的`via` 具体的话`stoken`教程中有说到
IOS目前推荐抓包获取`cookie`
pc端也就是电脑端 ，电脑端的话目前推荐`f12`获取网络请求的`cookie`  `中文名：网络` ，`英文：Network`
在网络请求中找`/ys`的然后再在`header`里面找到`cookie`字段 把里面的内容复制就行

**Comment by Dream-yyk** [comment]
欸……我就是看文档获取的，电脑控制台和via获取到的都不行啊

**Comment by Dream-yyk** [comment]
那个”新stoken“是指新获取的stoken，老的能用新的就不行了

**Comment by ctrlcvs** [comment]
目前我了解的新的stoken只有抓包会获取到，通过教程获取的stoken依旧是旧版本的，新版本的stoken 标记会带个`v2_`开头
我不清楚你看的是cookie文档还是stoken文档，刚刚测试stoken文档还是可用的[stoken文档](https://docs.qq.com/doc/DV2tDY2ltSFdtbU9z)

> 那个”新stoken“是指新获取的stoken，老的能用新的就不行了

**Comment by Dream-yyk** [comment]
啊……今天via获取的的变成v2了：
_ga=GA1.2.1267025015.1663161630; _MHYUUID=943d0569-e14b-4889-bdb4-109490038d57; DEVICEFP_SEED_ID=0282558f2ce83b82; DEVICEFP_SEED_TIME=1663536152735; mi18nLang=zh-cn; LOGIN_PLATFORM_SWITCH_STATUS={%22password_reset_entry%22:true%2C%22sms_login_tab%22:true%2C%22pwd_login_tab%22:true}; account_mid_v2=0cd75hhvaf_mhy; ltmid_v2=0cd75hhvaf_mhy; ltoken_v2=v2_YzznJeV5Xu1HR2uqOdFSVbkCs7IKlX-QhKJTP0Miy6Gn51rv4MtbRjfmBKXcsmpHs7KbZdb6fWWZuiurhjTGNfMN82ySsnbMVg==; login_uid=314152631; cookie_token_v2=v2_-W_nxLeJPNItVg6c-iwFJ6F_DmYUF901QjmMgmUjpDFLhDQnHD59UC2xq7xHmvyFYoa5w4_ba2AuauSmo-z90Pnc-xzdm0CQDgiwAATEb3HD6RZtPdQX2A==; DEVICEFP=38d7ec4e617e0; login_ticket=PsoSDzNr8HZ0wlyoHRYwhyeCqDHDA2rCdhBiNd4u

**Comment by Dream-yyk** [comment]
结案，每次折腾很久就突然又能绑定了，以后随便不更新stoken了doge
