### ISSUE TITLE
 puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by Feilx234** [Le-niao/Yunzai-Bot#1011]
[YzBot][10:28:29.087][MARK] [喵喵:喵喵帮助][help][私聊]#菜单
0|Yunzai-Bot  | [YzBot][10:28:29.206][MARK] puppeteer Chromium 启动中...
0|Yunzai-Bot  | [YzBot][10:28:29.218][ERRO] Error: Failed to launch the browser process! spawn /usr/lib64/chromium-browser EACCES
0|Yunzai-Bot  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|Yunzai-Bot  | [YzBot][10:28:29.218][ERRO] puppeteer Chromium 启动失败
0|Yunzai-Bot  | [YzBot][10:28:29.219][MARK] [喵喵:喵喵帮助][help] #菜单 处理完成 129ms

--------------------------------------------------------------------------
浏览器运行报错，重装也还是没能解决

**Comment by Le-niao** [comment]
没有正确安装Chromium

**Comment by Feilx234** [comment]
服务器安装其他机器人调试之后出现这个问题。后来通过格式化整个系统解决
