### ISSUE TITLE
pm2运行报错

### ISSUE THREAD

**Issue by Aromoze** [Le-niao/Yunzai-Bot#1033]
debian11.1 64bit
pm2 5.2.2 
nodejs 18.12.1
![Screenshot_2022-12-18-11-15-12-754_com.sonelli.juicessh.png](https://user-images.githubusercontent.com/78656727/208279754-44a0f244-952a-4467-8ffe-b8c2edae4c17.png)

**Comment by lgyseven** [comment]
pm2 update

**Comment by Aromoze** [comment]
> pm2 update

pm2已经是最新版本[8_ZP)%Q5XKNI99)IXO550PJ(1).png](https://user-images.githubusercontent.com/78656727/209285283-acaa66ef-7f02-4331-bf50-b6ba387d6d10.png)
