### ISSUE TITLE
Error: spawn UNKNOWN puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by huagjichen** [Le-niao/Yunzai-Bot#1039]
[YzBot][22:48:52.622][MARK] puppeteer Chromium 启动中...
[YzBot][22:48:52.644][ERRO] Error: spawn UNKNOWN
[YzBot][22:48:52.645][ERRO] puppeteer Chromium 启动失败
[YzBot][22:48:52.646][MARK] [云崽帮助][help] #帮助 处理完成 219ms

win2012R2，如题这个要怎么办，把redis和nodejs完整卸载重装也不行，只能重装系统了吗

**Comment by LJY7812** [comment]
我是重装系统之后，21H2重装22H2，就不行了

**Comment by leiji001** [comment]
重新部署就会这样

**Comment by leiji001** [comment]
Linux 和 Windows 都试过了
都是安装 puppeteer 时报错

**Comment by huagjichen** [comment]
OK兄弟们，我解决了！！！

这个问题应该是puppeteer依赖没装好

所以我直接复制一个正常运行的yunzaibot的puppeteer依赖，把这个报错的给他覆盖一下，完美

目前我已经解决了，正常运行了，顺便把这个依赖发给大家

因为蓝奏云上传限制100M，所以分成了两个卷
https://wwpm.lanzouf.com/imUzO0j27lrc
https://wwpm.lanzouf.com/iq9XN0j27jeh

两个都下载下来之后，
把1puppeteer_2.7z重命名成puppeteer_2.7z.001
把2puppeteer_2.7z重命名成puppeteer_2.7z.002

(这里我用7z解压的，官网https://7-zip.org/，其他解压软件也可以)
然后，右键解压puppeteer_2.7z.001
得到一个puppeteer.7z，（这个就是能正常运行的puppeteer依赖）

如果机器人还在运行，先关掉
然后找到你自己的路径 \Yunzai-Bot\node_modules\puppeteer\
把这里的东西全删掉（不敢删的可以移到别的地方），然后移动puppeteer.7z到这里并解压
最后再把puppeteer.7z删掉

OKK
