### ISSUE TITLE
#设置默认攻略 出现问题

### ISSUE THREAD

**Issue by fenggegang** [Le-niao/Yunzai-Bot#1048]
#设置默认攻略

直接发送给机器人 会提示 默认攻略已设置为: undefined
此时问题就会出现，之后无论你怎么再次设置，配置文件中保存的依旧是NaN
位置
Yunzai-Bot\plugins\genshin\config\mys.set.yaml

defaultSource: NaN

希望能修改为触发提示或者直接设置为1 解决下这个问题  避免更多人触发这个问题
感谢作者大大qwq

**Comment by Ansellyu** [comment]
巧了，今天就遇到了

**Comment by Ansellyu** [comment]
顺便说一下如果遇到了这个bug如何手动解决，很简单，只要访问Yunzai-Bot\plugins\genshin\config文件夹，编辑mys.set.yaml里的defaultSource参数即可，将NaN修改成1到4任意一个阿拉伯数字后保存退出即可（用记事本打开都可编辑），希望作者早点修。

**Comment by fenggegang** [comment]
该问题已修复
