### ISSUE TITLE
oicq中配置的版本似乎过期了

### ISSUE THREAD

**Issue by nyaachen** [Le-niao/Yunzai-Bot#1050]
昨天重启的时候提示版本低，还以为是设备问题，重试好多次都不行。
今天干脆把整个云崽都全新安装了一遍，结果第一次登录就直接提示版本低不允许登录。

![image](https://user-images.githubusercontent.com/16128355/209523510-2cdf7ff1-9a19-491c-a70e-1254bfa366b4.png)

云崽好像依赖库里有个oicq的patch，不知道这个issue要不要提到oicq那边去

**Comment by nyaachen** [comment]
改了改device，又能登录了。腾讯这个风控真的迷

**Comment by nyaachen** [comment]
oicq默认生成的设备信息是完全根据qq号来的，所以默认生成的设备被风控了就会一直被风控。
根据oicq的这个issue，要修改data/<qq号>/device-<qq号>.json里面的信息，主要是改一下imei，避免风控。
看了一下云崽的patch，代码里写死的qq版本已经高于issue中提出的版本了，因此不建议再改。

[#451 当前QQ版本过低   takayama-lily/oicq ](https://github.com/takayama-lily/oicq/issues/451)

**Comment by rnadow** [comment]
> oicq默认生成的设备信息是完全根据qq号来的，所以默认生成的设备被风控了就会一直被风控。 根据oicq的这个issue，要修改data/<qq号>/device-<qq号>.json里面的信息，主要是改一下imei，避免风控。 看了一下云崽的patch，代码里写死的qq版本已经高于issue中提出的版本了，因此不建议再改。
> 
> [#451 当前QQ版本过低 takayama-lily/oicq ](https://github.com/takayama-lily/oicq/issues/451)

感谢大佬提供解决办法，这就去试试

**Comment by Termux000001** [comment]
> oicq默认生成的设备信息是完全根据qq号来的，所以默认生成的设备被风控了就会一直被风控。 根据oicq的这个issue，要修改data/<qq-号>/device >.json里面的消息，主要是改一下imei，避开风控。 看了下云崽的补丁，代号里写死的qq版已经高在issue中提出的版本了，因此不建议再改。
> 
> [#451 当前QQ版本过低 takayama-lily/oicq](https://github.com/takayama-lily/oicq/issues/451)

怎么改？改最后一位没啥作用

**Comment by nyaachen** [comment]
> > oicq默认生成的设备信息是完全根据qq号来的，所以默认生成的设备被风控了就会一直被风控。 根据oicq的这个issue，要修改data/<qq-号>/device >.json里面的消息，主要是改一下imei，避开风控。 看了下云崽的补丁，代号里写死的qq版已经高在issue中提出的版本了，因此不建议再改。
> > [#451 当前QQ版本过低 takayama-lily/oicq](https://github.com/takayama-lily/oicq/issues/451)
> 
> 怎么改？改最后一位没啥作用

多改几位。如果还是有问题的话把前面设备信息也改了。
