### ISSUE TITLE
Yunzai-Bot Linux搭建教程在登录QQ时存在安全风险

### ISSUE THREAD

**Issue by Any2021** [Le-niao/Yunzai-Bot#106]
在使用服务器搭建教程时在登录QQ时输入了账号密码登录显示安全风险如何解
![1233](https://user-images.githubusercontent.com/93184852/165957840-1d67fbb6-22d1-4ea3-8781-54745df3a708.png)

**Comment by karakoo** [comment]
可以选择使用二维码扫码登录或者关闭登录保护后登录。

**Comment by Any2021** [comment]
> 关

大佬教一下如何使用二维码扫码登录，已经是关闭登录保护了的

**Comment by karakoo** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/d57bf674e1456a195d725c6cac147c6e7bb12b96/config/config_default.js#L10

**Comment by Any2021** [comment]
> https://github.com/Le-niao/Yunzai-Bot/blob/d57bf674e1456a195d725c6cac147c6e7bb12b96/config/config_default.js#L10

大佬，我纯萌新一个，不知道怎么修改
![-41d209857aeeb63c](https://user-images.githubusercontent.com/93184852/165968950-ec1a471a-a998-4a1e-bef5-5b2619729151.jpg)

**Comment by karakoo** [comment]
你是用的手机吧，你可以选择删除`config/config.js`，之后重新配置，配置的时候不设置密码就可以用扫码登录了

删除`config.js`的指令是
```shell
rm -f config/config.js
```
要先进入项目目录之后再输入

**Comment by Any2021** [comment]
> 你是用的手机吧，你可以选择删除`config/config.js`，之后重新配置，配置的时候不设置密码就可以用扫码登录了
> 
> 删除`config.js`的指令是
> 
> ```shell
> rm -f 配置/config.js
> ```
> 
> 要先进入项目目录之后再输入

我是电脑端的，我试过了扫码登录和账号密码登录，都显示异常，服务器搭和win系统都是显示风险

**Comment by karakoo** [comment]
> > 你是用的手机吧，你可以选择删除`config/config.js`，之后重新配置，配置的时候不设置密码就可以用扫码登录了
> > 
> > 删除`config.js`的指令是
> > 
> > ```shell
> > rm -f 配置/config.js
> > ```
> > 
> > 要先进入项目目录之后再输入
> 
> 我是电脑端的，我试过了扫码登录和账号密码登录，都显示异常，服务器搭和win系统都是显示风险

账号问题了，多挂一段时间看看

**Comment by Any2021** [comment]
![QQ图片20220430110225](https://user-images.githubusercontent.com/93184852/166088053-b7e2c5ac-e16d-4732-a505-6260aa4f2348.jpg)
两天都是这个样子

**Comment by karakoo** [comment]
> ![QQ图片20220430110225](https://user-images.githubusercontent.com/93184852/166088053-b7e2c5ac-e16d-4732-a505-6260aa4f2348.jpg)
> 两天都是这个样子

试试删除device.json、换个登录设备类型

#93

**Comment by Any2021** [comment]
> > ![QQ图片20220430110225](https://user-images.githubusercontent.com/93184852/166088053-b7e2c5ac-e16d-4732-a505-6260aa4f2348.jpg)
> > 两天都是这个样子
> 
> 试试删除device.json、换个登录设备类型
> 
> #93

换了 还是显示环境异常

**Comment by Shuery-Shuai** [comment]
### 以下提供两种方法

#### 一、在 WSL 上登录

你的 Windows 上有 WSL 么？

可以尝试先在 WSL 上登录账号。

成功以后进行以下操作。

##### **WSL** 上操作：

1. 进入 `Yunzai-Bot` 文件夹。

   ```sh
   cd /path/to/Yunzai-Bot
   ```

2. 使用 `tar` 命令打包上的 `Yunzai-Bot/data` 文件夹。

   ```sh
   tar -cf data.tar data
   ```

3. 将 `data.tar` 从 **WSL** 上传至**服务器**。

   ```sh
   scp data.tar user@server.ip:/path/to/Yunzai-Bot/
   ```

##### **服务器**上操作：

1. 进入 `Yunzai-Bot` 文件夹。

   ```sh
   cd /path/to/Yunzai-Bot
   ```

2. 删除**服务器**上的 `Yunzai-Bot/data` 文件夹。

   ```sh
   rm -rf data
   ```

3. 解压 `data.tar` 至 `Yunzai-Bot` 文件夹。

   ```sh
   tar -xf data.tar -C data
   ```

4. 使用 `node app` 启动项目。

   ```sh
   node app
   ```

#### 使用 VPN 进行登录

你可以在服务器端搭建 VPN（_PPTP_、_v2ray_ 什么的），之后手机上以**全局模式**连接此 VPN，再进行扫码登录的操作。

具体操作比较麻烦，可以百度以下。

**Comment by Any2021** [comment]
> ### 以下提供两种方法
> #### 一、在 WSL 上登录
> 你的 Windows 上有 WSL 么？
> 
> 可以尝试先在 WSL 上登录账号。
> 
> 成功以后进行以下操作。
> 
> ##### **WSL** 上操作：
> 1. 进入 `Yunzai-Bot` 文件夹。
>    ```shell
>    cd / path / to / Yunzai-Bot
>    ```
> 2. 使用 `tar` 命令打包上的 `Yunzai-Bot/data` 文件夹。
>    ```shell
>    tar -cf data.tar 数据
>    ```
> 3. 将 `data.tar` 从 **WSL** 上传至**服务器**。
>    ```shell
>    scp data.tar user@server.ip:/path/to/Yunzai-Bot/
>    ```
> 
> ##### **服务器**上操作：
> 1. 进入 `Yunzai-Bot` 文件夹。
>    ```shell
>    cd / path / to / Yunzai-Bot
>    ```
> 2. 删除**服务器**上的 `Yunzai-Bot/data` 文件夹。
>    ```shell
>    rm -rf 数据
>    ```
> 3. 解压 `data.tar` 至 `Yunzai-Bot` 文件夹。
>    ```shell
>    -xf data.tar -C 数据
>    ```
> 4. 使用 `node app` 启动项目。
>    ```shell
>    节点应用
>    ```
> 
> #### 使用 VPN 进行登录
> 你可以在服务器端搭建 VPN（_PPTP_、_v2ray_ 什么的），之后手机上以**全局模式**连接此 VPN，再进行扫码登录的操作。
> 
> 具体操作比较麻烦，可以百度以下。

谢谢大佬的教程，目前是已经解决了，我是使用了在服务器上重装为win系统下载QQ挂了两天之后才重为Linux使用密码登录，这样子就可以正常登录进去了
