### ISSUE TITLE
#导出记录 发送文件失败，但#导出记录json 是正常的，后台附在正文里

### ISSUE THREAD

**Issue by PrussianBlueCN** [Le-niao/Yunzai-Bot#1068]
![image](https://user-images.githubusercontent.com/110645427/210474304-01640060-9fb3-439b-aca9-28cca41b4204.png)

**Comment by Le-niao** [comment]
刚上线会这样，重试就可以了

**Comment by PrussianBlueCN** [comment]
那天尝试了几次都失败所以issue的，刚又试了一下成功了，那就先关了吧
