### ISSUE TITLE
机器人挂在linux无法发送图片

### ISSUE THREAD

**Issue by FakeEnd** [Le-niao/Yunzai-Bot#107]
其他不用发送图片功能的都测试成功了，但是发送图片的都不可以
因为之前都是用的cqhttp，这个的日志也没找到，所以没太搞清什么问题
![D32703D7-F6DA-4DD4-969D-935CAA0E8F11](https://user-images.githubusercontent.com/56879963/165993815-6df5feba-3f76-4c54-b4d4-5bf892823ace.png)

**Comment by Le-niao** [comment]
chromium没装或者没装依赖，生成图的时候就会保存

**Comment by FakeEnd** [comment]
linux上也要装吗

**Comment by FakeEnd** [comment]
> chromium没装或者没装依赖，生成图的时候就会保存

这个是自己安装吗，我用的文档里的脚本自动生成的

**Comment by FakeEnd** [comment]
问题可能是服务器没有更新索引问题，不清楚，反正我又运行了一下自动安装脚本的chrom部分就ok了，后面的人可以mark一下
