### ISSUE TITLE
更新面板失败

### ISSUE THREAD

**Issue by Huangdou233** [Le-niao/Yunzai-Bot#1116]
![Screenshot_2023-01-18-07-34-30-927_com tencent mobileqq](https://user-images.githubusercontent.com/122944096/213037006-da4e4fed-5a01-4944-96fd-8793bdd70ddb.jpg)
![Screenshot_2023-01-18-07-34-25-756_com tencent mobileqq](https://user-images.githubusercontent.com/122944096/213037011-62b27733-a89d-4bf5-97ad-9e7500bd3aa9.jpg)
![Screenshot_2023-01-18-07-29-21-885_com tencent mobileqq](https://user-images.githubusercontent.com/122944096/213037015-917e8d92-3402-400e-8153-6d336174103f.jpg)
如图 三个云崽bot无法正常更新面板

**Comment by Huangdou233** [comment]
破案了 原神在更新服务器 我忘了这回事

**Comment by Huangdou233** [comment]
破案了 我忘了原神服务器在更新

**Comment by 6T6T** [comment]
我也是在这种情况请问怎么解决 大佬

**Comment by Huangdou233** [comment]
OK
