### ISSUE TITLE
兑换码使用问题

### ISSUE THREAD

**Issue by AllureLove98** [Le-niao/Yunzai-Bot#1133]
当我使用  #兑换码使用 NAS3K7XR3C46 时，返回 米游社接口报错，暂时无法查询：请先登录账号 绑定的账号是国际服 我看[README.md](https://github.com/Le-niao/Yunzai-Bot/blob/main/README.md) 说时只支持国服 但是我看到 commit c6965a3ded6a4f3ea33bb255c442efd3b37ea4c3 说仅支持国际服  麻烦确定下到底是支持哪个 麻烦了

**Comment by Dream-yyk** [comment]
应该是只支持国际服吧，我国服和国际服的反馈分别是“仅支持国际服uid”和“米游社接口报错，暂时无法查询：无效的兑换码”（因为我搞不到兑换码做实验……）
而且源码也可以看到写的是拦截6，7，8，9开头以外的uid

**Comment by Dream-yyk** [comment]
你如果没绑定ck和sk的话可以试试绑定一下再兑换，说不定先登陆账号指的是这个

**Comment by wangmiaowj** [comment]
关于兑换码使用的问题，目前只支持国际服，而且还有个问题，就是这个功能使用的ck效期和hoyolab的效期是不一样的，也就是你的ck能在hoyolab使用但是在这个功能却提示ck过期，重新登录，目前我打算用xiaoyao的stoken刷新ck的方法保证ck是有效的
