### ISSUE TITLE
请问最新的米游社如何绑定stoken

### ISSUE THREAD

**Issue by GuiltyKirito** [Le-niao/Yunzai-Bot#1135]
想咨询一下大家，如题，最新的米游社如何绑定stoken呢？感谢

**Comment by Sora98** [comment]
同问，貌似方法都失效了，获取之后无法正常登录签到

**Comment by LingXuanYin** [comment]
可以看看我的项目 :) [https://github.com/LingXuanYin/YueHaiXianLin](url)，可以获取v2的cookie

**Comment by GuiltyKirito** [comment]
> 可以看看我的项目 :) [https://github.com/LingXuanYin/YueHaiXianLin](url)，可以获取v2的cookie

感谢，不过我想我应该是想要找个基于云崽bot的插件

**Comment by ctrlcvs** [comment]
#扫码绑定 
你用到stoken的话是有这个指令的，没有的话建议更新一下插件

**Comment by GuiltyKirito** [comment]
> #扫码绑定 你用到stoken的话是有这个指令的，没有的话建议更新一下插件

后来发现是逍遥插件的功能，我之前没装这个插件
