### ISSUE TITLE
QQ版本过低

### ISSUE THREAD

**Issue by 1324762577** [Le-niao/Yunzai-Bot#1145]

**Comment by 1324762577** [comment]
尝试了各种方法，改IMEI，device.js等无法解决QQ版本过低而无法登陆的问题

**Comment by Dream-yyk** [comment]
我用ipad一直可以登录，不知道为啥
apad和手表都是版本过低

**Comment by The-GL** [comment]
我现在已知的是扫码没问题，密码必定报

**Comment by Dream-yyk** [comment]
> 我现在已知的是扫码没问题，密码必定报

对的对的，我也是这样
