### ISSUE TITLE
更新发生错误

### ISSUE THREAD

**Issue by zhengsongjian** [Le-niao/Yunzai-Bot#1146]
[YzBot][23:23:53.099][MARK] [更新][update][私聊][myself(431559078)] #更新
fatal: detected dubious ownership in repository at 'D:/yunzai/Yunzai-Bot'
'D:/yunzai/Yunzai-Bot' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-335779833-2354742322-2240578716-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory D:/yunzai/Yunzai-Bot
[YzBot][23:23:53.313][ERRO] [更新][update]
[YzBot][23:23:53.314][ERRO] Error: Command failed: git rev-parse --short HEAD
fatal: detected dubious ownership in repository at 'D:/yunzai/Yunzai-Bot'
'D:/yunzai/Yunzai-Bot' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-335779833-2354742322-2240578716-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory D:/yunzai/Yunzai-Bot

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at update.getcommitId (file:///D:/yunzai/Yunzai-Bot/plugins/other/update.js:
151:26)
    at update.runUpdate (file:///D:/yunzai/Yunzai-Bot/plugins/other/update.js:11
4:35)
    at update (file:///D:/yunzai/Yunzai-Bot/plugins/other/update.js:58:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)
    at async PluginsLoader.deal (file:///D:/yunzai/Yunzai-Bot/lib/plugins/loader
.js:251:52)
麻烦各位大佬看一下该怎么解决，不太明白具体出错的地方

**Comment by zhengsongjian** [comment]
![image](https://user-images.githubusercontent.com/123851138/215803777-9a40782c-8bda-4d14-8a28-5d908f52c837.png)

**Comment by Dream-yyk** [comment]
我也碰到过类似的事情，稍微翻译一下就是云崽所在目录的所有者和执行更新操作时用的用户不同，所以没法更新文件内容
主要就是因为d盘权限乱……你应该也有各种复制删除文件都要多点一个授权窗口的问题吧（笑）
解决方法就是在cmd或者bash里执行一下给的那条`git config --global --add safe.directory D:/yunzai/Yunzai-Bot`，然后重新更新就好了

（当然你不嫌麻烦也可以把云崽搬去c盘）（划掉）

**Comment by zhengsongjian** [comment]
好的，在cmd里执行了就解决了，多谢大佬（开心.jpg）
