### ISSUE TITLE
启动之后报错ERR wrong number of arguments for 'set'  command

### ISSUE THREAD

**Issue by pump4kin** [Le-niao/Yunzai-Bot#1147]
![image](https://user-images.githubusercontent.com/109211373/215927397-2f2b6f85-f00e-457c-9e61-59b133a65e2b.png)

发送指令也没有响应

**Comment by pump4kin** [comment]
找到原因了，是redis没启动。。

**Comment by pump4kin** [comment]
多谢，已经可以了，自动启动的是什么版本？

**Comment by pump4kin** [comment]
懂了，我用的docker安装的，不会开机自启动

**Comment by Dream-yyk** [comment]
自动启动的是msi，安装的时候会自动加进windows服务
![image](https://user-images.githubusercontent.com/72236930/215970202-9eec7c45-409f-41b2-904e-79c2b78dc28c.png)

当然压缩包的redis网上也有手动加入服务的办法（
