### ISSUE TITLE
角色查询的时候出错了

### ISSUE THREAD

**Issue by mikuhasband** [Le-niao/Yunzai-Bot#115]
作者您好，先在这里向你说一声辛苦了！机器人部署完后，私聊发送#角色指令，一直close connected，请问是什么原因导致的？希望作者能帮助一下我，感谢！
![Screenshot_20220503-140050_JuiceSSH](https://user-images.githubusercontent.com/56474820/166410625-762c3eb6-0eb0-4fb0-989a-08674d6b49a7.jpg)

**Comment by Le-niao** [comment]
重复登录，后台的已经运行了一个，`npm stop` 停止后台运行

**Comment by mikuhasband** [comment]
感谢作者的回复，不断重连的问题解决了，但是又出现了新的报错，麻烦作者帮我看一下，感谢！
![Screenshot_20220503-141411_JuiceSSH](https://user-images.githubusercontent.com/56474820/166411974-b7d8faed-2c8e-4b3e-8247-694f97e99a62.jpg)
服务端系统是centos7

**Comment by mikuhasband** [comment]
同时刚刚发现控制台出现了乱码
![Uploading Screenshot_20220503-142358_JuiceSSH.jpg…]()
