### ISSUE TITLE
角色查询时报错

### ISSUE THREAD

**Issue by mikuhasband** [Le-niao/Yunzai-Bot#116]
感谢作者百忙之中地抽空回复我！反复重连的问题解决了，但是在查询角色和角色卡片的时候报错了，同时控制台出现了乱码，需要作者的帮助，感谢！
![Screenshot_20220503-141411_JuiceSSH](https://user-images.githubusercontent.com/56474820/166413329-965e39a5-987b-4a2d-bab0-c39acfc2074f.jpg)
![Screenshot_20220503-142358_JuiceSSH](https://user-images.githubusercontent.com/56474820/166413338-b69b4133-b0d7-4c5a-a276-c3a2565f7b35.jpg)

**Comment by mikuhasband** [comment]
已自行解决，问题出在复制cookie的时候不能带''(单引号)，cookie带符号会导致查询出错，麻烦作者了，不好意思！顺便问一下作者有赞助的渠道吗？

**Comment by Le-niao** [comment]
配置下公共ck就行
