### ISSUE TITLE
角色查询时报错

### ISSUE THREAD

**Issue by wzyu26** [Le-niao/Yunzai-Bot#117]
作者您好，请问这个问题怎么解决呢
![image](https://user-images.githubusercontent.com/104823427/166419777-2b628b05-2828-429b-9be9-f9d440b4e935.png)

**Comment by HTTE-lx** [comment]
同样的问题，期待答复

**Comment by DrinkCoffee2012** [comment]
same problems.

**Comment by ITManCHINA** [comment]
同样的问题，坐等修复

**Comment by karakoo** [comment]
我这边已经更新到了最新，然后没有发现这个问题
更新到最新试试
如果更新了之后还不行的话，可以描述一下当时的使用场景，看看可不可以复现

**Comment by HTTE-lx** [comment]
刚开机的电脑，打开redis（版本5.0.14.1windowsx64），在Yunzai-Bo文件夹下右键Git Bash Here打开命令提示窗口，键入npm start运行机器人，测试体力会有回复，但是#角色，#角色卡片等命令等均未回复。nmp start直接后台运行我看不到运行代码，不知道怎么解决
![image](https://user-images.githubusercontent.com/65992830/166655773-37549973-b7ee-4cdb-b26b-51d2485d9f00.png)

**Comment by ITManCHINA** [comment]
> 我这边已经更新到了最新，然后没有发现这个问题 更新到最新试试 如果更新了之后还不行的话，可以描述一下当时的使用场景，看看可不可以复现 ![image](https://user-images.githubusercontent.com/70872201/166654472-2c785eb0-9efa-4c68-869c-d9712e3ccdce.png)

我用的腾讯轻量云，Node14.6.1，装的CentOS，使用查询命令#UID 查询会出错
[https://s2.loli.net/2022/05/04/LyIG8PHeWtdw7SD.pnghttps://s2.loli.net/2022/05/04/LyIG8PHeWtdw7SD.png](url)

**Comment by DrinkCoffee2012** [comment]
I tried in my computer and found this problem yesterday: all commands related to the user information can't work. I test on my Android phone this afternoon and it works really fine.

**Comment by karakoo** [comment]
> 刚开机的电脑，打开redis（版本5.0.14.1windowsx64），在Yunzai-Bo文件夹下右键Git Bash Here打开命令提示窗口，键入npm start运行机器人，测试体力会有回复，但是#角色，#角色卡片等命令等均未回复。nmp start直接后台运行我看不到运行代码，不知道怎么解决 ![image](https://user-images.githubusercontent.com/65992830/166655773-37549973-b7ee-4cdb-b26b-51d2485d9f00.png)

用的`npm start`的话，可以看log文件夹下的日志
`#角色`，`#角色卡片`等功能都是`cookie`相关功能，看看`cookie`有没有过期，或者设置错误(例如https://github.com/Le-niao/Yunzai-Bot/issues/116#issuecomment-1115813299)

**Comment by karakoo** [comment]
> > 我这边已经更新到了最新，然后没有发现这个问题 更新到最新试试 如果更新了之后还不行的话，可以描述一下当时的使用场景，看看可不可以复现 ![image](https://user-images.githubusercontent.com/70872201/166654472-2c785eb0-9efa-4c68-869c-d9712e3ccdce.png)
> 
> 我用的腾讯轻量云，Node14.6.1，装的CentOS，使用查询命令#UID 查询会出错 ![1651656494.jpg](https://camo.githubusercontent.com/a11545da69640c28fca3b1ae2ebc7506053908bd0503dc4f2f16b67262e33b14/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f30342f4c79494738504865577464773753442e706e67)

已经拉取了GitHub上最新的commit了吗？详细情况我也不清楚(ｕДｕ〃) 也有可能是cookie的问题

**Comment by HTTE-lx** [comment]
> > 刚开机的电脑，打开redis（版本5.0.14.1windowsx64），在Yunzai-Bo文件夹下右键Git Bash Here打开命令提示窗口，键入npm start运行机器人，测试体力会有回复，但是#角色，#角色卡片等命令等均未回复。nmp start直接后台运行我看不到运行代码，不知道怎么解决 ![image](https://user-images.githubusercontent.com/65992830/166655773-37549973-b7ee-4cdb-b26b-51d2485d9f00.png)
> 
> 用的`npm start`的话，可以看log文件夹下的日志 `#角色`，`#角色卡片`等功能都是`cookie`相关功能，看看`cookie`有没有过期，或者设置错误(例如[#116 (comment)](https://github.com/Le-niao/Yunzai-Bot/issues/116#issuecomment-1115813299))

![image](https://user-images.githubusercontent.com/65992830/166662730-1fb211d1-2804-472a-ad06-454f7bb8e262.png)

**Comment by ITManCHINA** [comment]
> 

已经是更新+重启过了呢，也抓取了新的Cookie

**Comment by ITManCHINA** [comment]
> > > 我这边已经更新到了最新，然后没有发现这个问题 更新到最新试试 如果更新了之后还不行的话，可以描述一下当时的使用场景，看看可不可以复现 ![image](https://user-images.githubusercontent.com/70872201/166654472-2c785eb0-9efa-4c68-869c-d9712e3ccdce.png)
> > 
> > 
> > 我用的腾讯轻量云，Node14.6.1，装的CentOS，使用查询命令#UID 查询会出错 ![1651656494.jpg](https://camo.githubusercontent.com/a11545da69640c28fca3b1ae2ebc7506053908bd0503dc4f2f16b67262e33b14/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f30342f4c79494738504865577464773753442e706e67)
> 
> 已经拉取了GitHub上最新的commit了吗？详细情况我也不清楚(ｕДｕ〃) 也有可能是cookie的问题


已经是更新+重启过了呢，也抓取了新的Cookie

**Comment by karakoo** [comment]
> > > 刚开机的电脑，打开redis（版本5.0.14.1windowsx64），在Yunzai-Bo文件夹下右键Git Bash Here打开命令提示窗口，键入npm start运行机器人，测试体力会有回复，但是#角色，#角色卡片等命令等均未回复。nmp start直接后台运行我看不到运行代码，不知道怎么解决 ![image](https://user-images.githubusercontent.com/65992830/166655773-37549973-b7ee-4cdb-b26b-51d2485d9f00.png)
> > 
> > 
> > 用的`npm start`的话，可以看log文件夹下的日志 `#角色`，`#角色卡片`等功能都是`cookie`相关功能，看看`cookie`有没有过期，或者设置错误(例如[#116 (comment)](https://github.com/Le-niao/Yunzai-Bot/issues/116#issuecomment-1115813299))
> 
> ![image](https://user-images.githubusercontent.com/65992830/166662730-1fb211d1-2804-472a-ad06-454f7bb8e262.png)

没有其它日志了么，看下`log`文件夹下的`error.log`
看看redis是否存活，和端口是不是6379

**Comment by HTTE-lx** [comment]
> 

![image](https://user-images.githubusercontent.com/65992830/166668251-b7c4c2bc-b54b-4ed0-803d-490e9c420dac.png)
看不出来端口是哪个，redis一直是开着的

**Comment by HTTE-lx** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/65992830/166668251-b7c4c2bc-b54b-4ed0-803d-490e9c420dac.png) 看不出来端口是哪个，redis一直是开着的

![image](https://user-images.githubusercontent.com/65992830/166668623-747848ed-6e8f-4bee-83c3-06f91ed1e167.png)
duank端口是6379

**Comment by wzyu26** [comment]
在Linux环境重新搭建没有遇到这个问题。

**Comment by xiaoyudamaoxian** [comment]
这边也是相同的情况，而且更新完重启出现了一直跳closed，用的百度云windows-2012-x86_64-20210825-021657
![FRCH531OBX T@JV6U$FOM{7](https://user-images.githubusercontent.com/104823371/166670822-b244ee56-e7a8-44da-b192-6ba6bb44246e.png)
![image](https://user-images.githubusercontent.com/104823371/166670987-c84a13c2-0611-483b-958a-888acc51b530.png)
更新重启了cookie也重新获取了，无痕模式也试过

**Comment by xiaoyudamaoxian** [comment]
![image](https://user-images.githubusercontent.com/104823371/166672198-ca8ce9e0-57db-4d08-96cc-c2338c8588c6.png)

**Comment by karakoo** [comment]
尝试了半天，我这边还无法复现这个问题

**Comment by yzy-youren** [comment]
同样遇到了此问题 尝试过删除文件夹 重新npm install  升级过node。js 依旧是此问题

**Comment by yoimiya-kokomi** [comment]
暂未复现错误，怀疑为redis版本问题
出问题的朋友可尝试将redis置为 https://github.com/microsoftarchive/redis/releases/tag/win-3.0.504 对应版本

如未解决请详细描述下出问题的详情
1. 本次出问题是新安装，还是还是仅升级了Yunzai-Bot
2. reids具体版本及安装包地址

**Comment by xiaoyudamaoxian** [comment]
> 暂未复现错误，怀疑为redis版本问题 出问题的朋友可尝试将redis置为 https://github.com/microsoftarchive/redis/releases/tag/win-3.0.504 对应版本
> 
> 如未解决请详细描述下出问题的详情
> 
> 1. 本次出问题是新安装，还是还是仅升级了Yunzai-Bot
> 2. reids具体版本及安装包地址

更换了上面链接的redis版本
![image](https://user-images.githubusercontent.com/104823371/166709449-c3a0dd5c-d2c2-433c-b59a-1dd377343fdc.png)
![image](https://user-images.githubusercontent.com/104823371/166709493-42f0e91c-137e-4caa-b858-6e804acb9636.png)
新安装没有更新前就有这个问题了，升级后问题还在，还出现了无限跳closed
之前用的redis是[5.0.14.1](https://github.com/tporadowski/redis/releases/tag/v5.0.14.1)

**Comment by ITManCHINA** [comment]
> > > > 我这边已经更新到了最新，然后没有发现这个问题 更新到最新试试 如果更新了之后还不行的话，可以描述一下当时的使用场景，看看可不可以复现 ![image](https://user-images.githubusercontent.com/70872201/166654472-2c785eb0-9efa-4c68-869c-d9712e3ccdce.png)
> > > 
> > > 
> > > 我用的腾讯轻量云，Node14.6.1，装的CentOS，使用查询命令#UID 查询会出错 ![1651656494.jpg](https://camo.githubusercontent.com/a11545da69640c28fca3b1ae2ebc7506053908bd0503dc4f2f16b67262e33b14/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30352f30342f4c79494738504865577464773753442e706e67)
> > 
> > 
> > 已经拉取了GitHub上最新的commit了吗？详细情况我也不清楚(ｕДｕ〃) 也有可能是cookie的问题
> 
> 已经是更新+重启过了呢，也抓取了新的Cookie

（补）Redis server 5.0.3
![1D}H(98ESKKC`W44EHS[BLA.png](https://s2.loli.net/2022/05/05/cKfCz1tjsENBQiA.png)

**Comment by yoimiya-kokomi** [comment]
删除 Yunzai根目录 node_modules 后重新npm install安装所有依赖试下
如果问题仍然存在并且可以提供环境给我排查的可以加一下我，qq 592981798，备注 redis

**Comment by yzy-youren** [comment]
怀疑是某插件问题 重装yunzai和喵喵之后 问题解决

**Comment by Le-niao** [comment]
redis版本4.1.0，再拉取更新下就可以了
