### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 741807012** [Le-niao/Yunzai-Bot#12]
不能登录QQ了

**Comment by Le-niao** [comment]
有没有报错之类的

**Comment by 741807012** [comment]
> 有没有报错之类的
[2021-12-22T17:45:09.143] [MARK] [iPad:1662734212] - 5秒后重新连接
[2021-12-22T17:45:09.143] [ERROR] [iPad:1662734212] - length of encrypted data must be a multiple of 8
[2021-12-22T17:45:09.143] [MARK] [iPad:1662734212] - 14.22.9.53:443 closed

**Comment by 741807012** [comment]
还有无法使用cookie_token=*******; account_id=******

**Comment by Le-niao** [comment]
npm update oicq

**Comment by 741807012** [comment]
我有好几百个cookie_token=*; account_id=*这样的格式的Cookie

**Comment by 741807012** [comment]
> 我有好几百个cookie_token=*; account_id=*这样的格式的Cookie

现在都用不了了

**Comment by Le-niao** [comment]
你这个不行 那个是签到用的 查询用的是 ltoken=***;ltuid=***;

**Comment by 741807012** [comment]
怎么改手机端登录，不想平板端登录

**Comment by Le-niao** [comment]
> 怎么改手机端登录，不想平板端登录

config.js  -> account  -> platform

**Comment by 741807012** [comment]
能不能搞私聊添加Cookie啊，太多我不好添加

**Comment by Le-niao** [comment]
我看看

**Comment by Le-niao** [comment]
> 能不能搞私聊添加Cookie啊，太多我不好添加

不用加这么多吧，十几个都够用了
