### ISSUE TITLE
大佬，关于cookies绑定

### ISSUE THREAD

**Issue by Juenia** [Le-niao/Yunzai-Bot#120]
![-1e8d8a495d7b9761.jpg](https://user-images.githubusercontent.com/48351858/166621449-0c7b87f7-d41a-4c73-ba54-ca7d27c43f5b.jpg)
似乎是没绑定成功

**Comment by Juenia** [comment]
重启即可解决，感谢@yoimiya-kokomi

**Comment by Le-niao** [comment]
ck截图没打码

**Comment by Juenia** [comment]
> ck截图没打码

已重置，已失效
