### ISSUE TITLE
关于字体渲染有锯齿

### ISSUE THREAD

**Issue by 1055169799** [Le-niao/Yunzai-Bot#127]
今天在腾讯云一个低配机器上搭建的时候，发现出来的字渲染不精致，有锯齿 ![-7e95a5aabe5ea810.png](https://user-images.githubusercontent.com/41286675/167058416-72fd9896-b9d0-477a-98eb-1d59276e190c.png)
![Screenshot_2022-05-06-10-47-53-58_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/167058735-c758dc30-1075-4b1c-b681-10a4acce38d4.jpg)
并且更换过字体也是一样，所以推测是渲染的问题
![3b0b021dbe6828f7.png](https://user-images.githubusercontent.com/41286675/167058501-f9f0ce7b-6108-4b78-b346-9ebe4ef94919.png)
这个可以通过什么方法解决呢？

**Comment by 1055169799** [comment]
已自行研究解决

原理是这个图片都是在无头浏览器里渲染的，浏览器的字体显示效果由系统决定，所以只需要把系统的Clear Type打开，调节一下系统字体的视觉感，然后重启机器人就好了。

![6136d5e431a42bc9.png](https://user-images.githubusercontent.com/41286675/167337872-b16dfe7c-3911-4856-b1b7-442db5b94e7a.png)

**Comment by Le-niao** [comment]
更换系统中文字体，推荐微软雅黑
