### ISSUE TITLE
能不能添加个树脂、派遣的私聊提醒功能

### ISSUE THREAD

**Issue by King-Nameless** [Le-niao/Yunzai-Bot#13]
原来用的机器人就是看重这个功能，但前几天失效了，作者也不知道怎么改……
我觉得这功能真的好用，发命令可以直接查询米游社的便签，树脂到了设定值、派遣完成都会私聊提醒
在GitHub搜了半天，没发现有这种功能的机器人了_(:зゝ∠)_

**Comment by Le-niao** [comment]
有一个简单查看树脂，没有定时提醒

**Comment by King-Nameless** [comment]
> 有一个简单查看树脂，没有定时提醒

大佬搞一个吗
![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147637587-4e3fc5f8-b8bc-4445-b326-08b4ec389b36.jpg)

**Comment by Le-niao** [comment]
> > 有一个简单查看树脂，没有定时提醒
> 
> 大佬搞一个吗 ![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147637587-4e3fc5f8-b8bc-4445-b326-08b4ec389b36.jpg)

加了，现在可以了

**Comment by 1368129224** [comment]
请问提醒功能需要单独打开吗？或者是需要单独配置？
