### ISSUE TITLE
腾讯智能对话平台要怎么配置

### ISSUE THREAD

**Issue by Lixuhuilll** [Le-niao/Yunzai-Bot#133]
我申请了腾讯智能对话平台公测权限，并填入了BotId，似乎无事发生。

**Comment by Lixuhuilll** [comment]
myyzbot-yunzai-bot-1  | [2022-05-11T18:21:26.249] [ERROR] error - ai.tencentAI
myyzbot-yunzai-bot-1  | [2022-05-11T18:21:26.250] [ERROR] error - TencentCloudSDKHttpException [Error]: GetRobotBasicInfo failed, [err:rpc error: code = Unknown desc = robot not complied or robot not exist or robot offline]

**Comment by Le-niao** [comment]
没创建机器人或者配置填错了
