### ISSUE TITLE
登录协议问题

### ISSUE THREAD

**Issue by loveyoutan90** [Le-niao/Yunzai-Bot#14]
之前我可以同时go-cqhttp和redis同时登录，但是更新后redis也使用的是ipad协议，和go-cqhttp冲突了，导致不能同时登录

**Comment by loveyoutan90** [comment]
好的，我已经在配置文件里修改了

**Comment by Le-niao** [comment]
改下config就好

**Comment by Le-niao** [comment]
还有是node 不是redis
