### ISSUE TITLE
角色攻略查询功能失效

### ISSUE THREAD

**Issue by Jayzongzer** [Le-niao/Yunzai-Bot#140]
![1](https://user-images.githubusercontent.com/50653415/168487701-32186983-ea81-457c-bd47-cba6e7d3b018.png)
上图是13日的查询记录，功能正常
![2](https://user-images.githubusercontent.com/50653415/168487727-8019db7f-9dfb-47bf-84e9-bfa2736a10d4.png)
这是16日晚上2点左右的查询记录，显示暂无攻略

并未更改任何设置，版本已更新到最新版本，其他功能均正常，只是角色攻略查询功能失效

**Comment by Sakurai233** [comment]
遇到了同样的问题

**Comment by tgllt** [comment]
#老婆命令也失效了

**Comment by MskTim** [comment]
接口失效
将/root/Yunzai-Bot/lib/app/url/strategy_xf.js中的url路径更新为：https://bbs-api.mihoyo.com/post/wapi/getPostFullInCollection?collection_id=642956&gids=2&order_type=2

**Comment by Jayzongzer** [comment]
> 接口失效将/root/Yunzai-Bot/lib/app/strategy_xf.js 中的url路径更新为：https://bbs-api.mihoyo.com/post/wapi/getPostFullInCollection?collection_id=642956&gids=2&order_type=2

thx,多谢大佬，修改url后攻略功能已恢复

**Comment by Le-niao** [comment]
别改这个，图是旧的攻略已过时

**Comment by Jayzongzer** [comment]
> 别改这个，图是旧的攻略已过时

啊 我已经改了  那现在需要改成什么url才是较新的攻略呢？

**Comment by Jayzongzer** [comment]
> 别改这个，图是旧的攻略已过时

我到米游社会去看了下，发现原作者现在使用属性来划分角色了，整个火系角色攻略是一张大图了

**Comment by MskTim** [comment]
> 别改这个，图是旧的攻略已过时

啊这，没细看。。。
