### ISSUE TITLE
运行没多久就闪退

### ISSUE THREAD

**Issue by 741807012** [Le-niao/Yunzai-Bot#15]
不能长时间运行闪退

**Comment by Le-niao** [comment]
拉下最新的代码，修复了风控导致发送消息失败，报错崩溃

**Comment by 741807012** [comment]
是最新的了

**Comment by Le-niao** [comment]
> 是最新的了

有没有具体报错

**Comment by 741807012** [comment]
> > 是最新的了
> 
> 有没有具体报错

没看见，窗口不见了

**Comment by Le-niao** [comment]
> > > 是最新的了
> > 
> > 
> > 有没有具体报错
> 
> 没看见，窗口不见了

不知道什么情况，你试试npm start 后台运行
