### ISSUE TITLE
模拟抽卡功能的卡池设定似乎有点问题

### ISSUE THREAD

**Issue by Lixuhuilll** [Le-niao/Yunzai-Bot#163]

**Comment by Lixuhuilll** [comment]
模拟抽卡卡池的up角色并没有更新，程序从config/genshin/gacha.json读取卡池配置，而更新的卡池配置是config/genshin/pool/301.json和config/genshin/pool/302.json

![image](https://user-images.githubusercontent.com/88485037/169699062-c0746f98-e243-47da-9ae2-08e98a61d5a8.png)

**Comment by PoorGarry** [comment]
也遇到了，有解决方法吗

**Comment by zzctonyh** [comment]
直接修改gacha.json
把endtime改成正确的日期就行了

**Comment by PoorGarry** [comment]
> 直接修改gacha.json 把endtime改成正确的日期就行了

试了，有效，感谢大佬
