### ISSUE TITLE
角色显示内容与文档中图片有所出入？

### ISSUE THREAD

**Issue by li0817** [Le-niao/Yunzai-Bot#165]
能不能显示成文档中的这样啊：
![image](https://user-images.githubusercontent.com/27659768/169703179-6438fd28-1ac5-4f69-b52b-ce4c95c7ca47.png)

实际效果1——【#行秋】
![b0e05237d2ff9371ae90712e3dfa6e3b](https://user-images.githubusercontent.com/27659768/169703225-db51e393-1fb4-4382-abd2-74e6b1052132.jpg)

实际效果2——【#行秋卡片】
![a689c2d81355477d23b080517a63dff7](https://user-images.githubusercontent.com/27659768/169703231-e80ce23b-2a35-4e9f-b1bb-35c2dc95fc3a.jpg)

目前的两种角色查看方式都不能看到具体的圣遗物信息

**Comment by karakoo** [comment]
因为你安装了 [miao-plugin](https://github.com/yoimiya-kokomi/miao-plugin) 插件

**Comment by li0817** [comment]
明白了_(:з」∠)_
