### ISSUE TITLE
希望加入圣遗物评分

### ISSUE THREAD

**Issue by programerluffy** [Le-niao/Yunzai-Bot#167]

**Comment by karakoo** [comment]
有此功能，指令是 `#圣遗物评分`

**Comment by programerluffy** [comment]
这个是单圣遗物的评分，能不能做到针对某个角色，做出全身圣遗物评分呢。我看他们可以从角色展示栏，拿到对应角色的数据

**Comment by karakoo** [comment]
> 这个是单圣遗物的评分，能不能做到针对某个角色，做出全身圣遗物评分呢。我看他们可以从角色展示栏，拿到对应角色的数据

[miao-plugin](https://github.com/yoimiya-kokomi/miao-plugin) 有这个功能，不过最近并没有开放这个功能的token

原神也没有开放相关的接口

不过如果你有能力的话，可以自己写一个，大致思路是：通过 [playwright](https://playwright.dev) 控制浏览器，打开[网易云游戏](https://cg.163.com/#/mobile)的安卓端原神，然后登录一个机器人专用的账号进行查询角色，之后就用OCR和目标检测拿数据了
