### ISSUE TITLE
cnpm install后出错

### ISSUE THREAD

**Issue by Rainxing0323** [Le-niao/Yunzai-Bot#168]
> ![Screenshot_2022-05-24-20-04-06-914_com.microsoft.rdc.android.jpg](https://user-images.githubusercontent.com/76428018/170030524-2d1d0da5-45f3-41c8-ad53-c3c859aa9d19.jpg)![Screenshot_2022-05-24-19-53-20-025-edit_com.microsoft.rdc.android.jpg](https://user-images.githubusercontent.com/76428018/170030549-dd7eb17d-1877-4dc4-b107-dd536d8910a4.jpg)命令符那边也不对

**Comment by SirlyDreamer** [comment]
请问您的nodejs版本是多少

**Comment by SirlyDreamer** [comment]
Yunzai-Bot建议使用最新版的nodejs 16，从您的执行结果来看似乎您使用的是13.13.0，请升级
下载地址：[https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi](https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi)

**Comment by Rainxing0323** [comment]
> Yunzai-Bot建议使用最新版的nodejs 16，从您的执行结果来看似乎您使用的是13.13.0，请升级
> 下载地址：[https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi](https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi)

你好！
按照您说的方法，我又试了一下，还是原来的问题怎么办

**Comment by SirlyDreamer** [comment]
请将node13卸载，如还是存在问题，请截图

**Comment by Rainxing0323** [comment]
> 请将node13卸载再安装node16，如还是存在问题，请截图

我就是这样操作的，git里还是用不了，不过使用命令符可以操作，已经解决了
