### ISSUE TITLE
ubuntu16 LTS安装后运行中文乱码

### ISSUE THREAD

**Issue by mobutcher** [Le-niao/Yunzai-Bot#175]
![-45993cc8ced395a1](https://user-images.githubusercontent.com/22803513/170807775-ee5bdbb8-560f-4b68-bab0-17a9cd92938d.jpg)
发送#帮助的图片中文乱码？

**Comment by SirlyDreamer** [comment]
请先安装中文字体，具体方法请参考：[https://www.freesion.com/article/5086447741/](https://www.freesion.com/article/5086447741/)
