### ISSUE TITLE
关于转化其他抽卡工具记录文件的提议

### ISSUE THREAD

**Issue by 1055169799** [Le-niao/Yunzai-Bot#180]
我看了一下，机器人的抽卡记录文件是分为三个的
![image](https://user-images.githubusercontent.com/41286675/171166714-5fc1219e-347c-4ab2-9ba3-5cf0ffe08171.png)

在这之前，我用的是 https://github.com/biuuu/genshin-wish-export 这个抽卡记录统计工具
这个工具是会把每一次查询的数据都存在电脑本地的，只要软件不删除，数据一直在，所以我这里留下了很长时间的记录
然后它是支持导出Excel数据 
![image](https://user-images.githubusercontent.com/41286675/171167451-ddf043ca-bb2e-40ad-998b-634acb65454d.png)
还有导出Json数据的
![image](https://user-images.githubusercontent.com/41286675/171167621-ab922de1-ad5f-4f70-8fe4-83bc6cbf2563.png)

并且这个数据在非小酋 https://feixiaoqiu.com/rank_url_upload_init/ 网站上是受支持的
![image](https://user-images.githubusercontent.com/41286675/171168091-2c835b34-cbd8-4a7e-96d8-714861c5b7eb.png)
在抽卡记录分析网站 https://genshin-gacha-analyzer.vercel.app/ 也是受支持的
![image](https://user-images.githubusercontent.com/41286675/171168855-6742fb01-9d9e-4a4d-8199-e4e1c6ad25f4.png)
在另一个软件的抽卡记录统计工具 https://www.snapgenshin.com/documents/features/wish-export.html 里，也支持导入和导出Excel和Json数据
![image](https://user-images.githubusercontent.com/41286675/171171148-d894648f-d726-4eeb-9014-7700e9ccf5e7.png)
这个数据格式还支持一些其他的工具，包括手机APP《应急食品》
![image](https://user-images.githubusercontent.com/41286675/171173051-ec8e8596-1c57-4d28-a825-fc35a75ed75b.png)

这个提议就是希望作者可以支持这个数据的读取，通过直接把数据文件发给机器人，就可以解析并保存半年以前的历史抽卡记录，或者直接把文件放在这里面也可以直接读取
![image](https://user-images.githubusercontent.com/41286675/171172424-d550e0a9-26b3-41d1-8abe-5ce202c7d9d1.png)

最后提供一下，这个是一些开发者制定的一项统一的可交换的标准
https://www.snapgenshin.com/development/UIGF.html#%E5%89%8D%E8%A8%80

**Comment by 1055169799** [comment]
已解决，使用了一个插件，成功将抽卡记录工具导出的Excel并入机器人中
![image](https://user-images.githubusercontent.com/41286675/172962769-1dbf8813-1c2a-46e0-bf99-1b452639eee0.png)
![image](https://user-images.githubusercontent.com/41286675/172962815-5f40ea3c-c05c-454c-9097-f5e0c49e46e3.png)
![image](https://user-images.githubusercontent.com/41286675/172963018-c516bc13-53db-4523-beff-dd706808ed01.png)
![image](https://user-images.githubusercontent.com/41286675/172963045-371480d1-4932-4f65-a64d-05636029e271.png)

**Comment by Micuks** [comment]
请问这是一个什么插件呢？我也想用这个功能。

**Comment by 1055169799** [comment]
> 请问这是一个什么插件呢？我也想用这个功能。

名字就是那个js的名字，在插件群里找到的

**Comment by Micuks** [comment]
> 

是什么插件群, 拉拉我喵

**Comment by 1055169799** [comment]
> > 
> 
> 是什么插件群, 拉拉我喵

就是作者的群啊，里面有很多插件
