### ISSUE TITLE
登录保护验证怎么办？让我调用login或者sendSmsCode

### ISSUE THREAD

**Issue by bingling66** [Le-niao/Yunzai-Bot#189]
我想通过密码登录，这样不用每次扫码。天天扫码太烦了，还不自动重连

**Comment by bingling66** [comment]
怎么搞啊

**Comment by Curker** [comment]
我也一样，有解决方法了踢我一脚

**Comment by Curker** [comment]
解决了踢我一下

**Comment by ADWN** [comment]
建议在QQ安全中心开启密码保护后去登录（虽然没有开但是还是会提示异地登录就很gou）
1、开启后，Yunzai-Bot目录下命令，node app，复制验证的url地址到浏览器并打开页面，用已登录的QQ去扫页面的二维码允许异地登录就好了
2、上述不行的话，删除Yunzai-Bot/config/config.js文件，删除登录设备信息/Yunzai-Bot/data/QQ号/device文件，回到主目录，执行node app重新进行登录操作（操作1）

**Comment by bingling66** [comment]
woc,解决了困扰我几星期的事情！！大佬牛B
