### ISSUE TITLE
是否考虑单独做成服务而非强依赖QQ

### ISSUE THREAD

**Issue by NepPure** [Le-niao/Yunzai-Bot#193]
比如基于https://onebot.dev/ 标准，这样不管是对接QQ微信Discord什么的都会非常方便，通信层可以考虑拆出去

**Comment by AnxiangLemon** [comment]
哇！！兄弟！我现在在自己强拆！！ 他的耦合性太强了....哈哈

**Comment by NepPure** [comment]
> 哇！！兄弟！我现在在自己强拆！！ 他的耦合性太强了....哈哈

搞好了at我 😆
