### ISSUE TITLE
查询他人角色列表时。技能信息无法显示

### ISSUE THREAD

**Issue by Explore617** [Le-niao/Yunzai-Bot#195]
![image](https://user-images.githubusercontent.com/90906241/172304251-70e0be24-5ece-43f8-8b24-4e3d161e1bde.png)

**Comment by sjlei** [comment]
配置的cookie不完整，重新获取并配置一下

**Comment by 1055169799** [comment]
第一次统计练度获取数据的时候如果没有配置cookie，就是查不到技能的，这个时候再去配置cookie也看不到，需要等6小时才能再次刷新

**Comment by sjlei** [comment]
> 第一次统计练度获取数据的时候如果没有配置cookie，就是查不到技能的，这个时候再去配置cookie也看不到，需要等6小时才能再次刷新

使用 `#练度统计force` 强制刷新

**Comment by 1055169799** [comment]
> 

好的
