### ISSUE TITLE
替换Docker源镜像以解决部署在Docker内的Yunzai-Bot在更新喵喵插件时报错的问题

### ISSUE THREAD

**Issue by SirlyDreamer** [Le-niao/Yunzai-Bot#196]
# 问题描述：

执行`#喵喵更新`命令时报错：

```
喵喵更新失败！
Error code: 128
Error: Command failed: git  pull
fatal: unsafe repository ('/app/Yunzai-Bot/plugins/miao-plugin' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /app/Yunzai-Bot/plugins/miao-plugin

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:740:14)
 请稍后重试。
```

# 问题解决：

这是一个普遍的问题：当安装插件的时候，git是从主机运行的，导致目录的所有者不同，容器内git无法pull。为了彻底解决这个问题，需要先设置safe directory为'*'，即`git config --global --add safe.directory '*'`。但是这里对`*`目录的支持是git 2.36版本之后的特性，Centos8的git版本过低且系统已经不再支持，不适用这个操作，故询问是否能够替换底层镜像。

征求您的意见 @Xm798 

如果可以的话我就提交pr

**Comment by Xm798** [comment]
喵喵插件这个，我之前还想过是否可以直接通过 entrypoint 初始化，例如通过环境变量 `ENABLE_MIAO_PLUGIN` 配置是否加载喵喵插件，启用之后 entrypoint  自动下载插件，省去手动安装的麻烦，但后来咕咕咕了…… 现在拿出来探讨一下必要性和可行性

**Comment by SirlyDreamer** [comment]
不用这么麻烦，实际上用户安装喵喵插件也是一行命令的事情，让用户自己决定就可以了,,ԾㅂԾ,,

另外可能需要在docker部署的帖子那里提醒以下用户安装插件应该在./Yunzai目录下执行git clone

**Comment by SirlyDreamer** [comment]
> @Xm798 我刚刚按照您的新repo（Yunzai-Bot-docker）的思路重新配置了一下GitHub Action，GitHub源推送到Docker Hub，Gitee源推送到华为云，目的是让用户根据自己的地区选择镜像，但是在Build的时候Gitee源始终无法解析连接，请问您有什么解决方案吗？
> 
> 报错的地址：https://github.com/SirlyDreamer/Yunzai-Bot/runs/6815808998?check_suite_focus=true

他好了XD

**Comment by Xm798** [comment]
> @Xm798 我刚刚按照您的新repo（Yunzai-Bot-docker）的思路重新配置了一下GitHub Action，GitHub源推送到Docker Hub，Gitee源推送到华为云，目的是让用户根据自己的地区选择镜像，但是在Build的时候Gitee源始终无法解析连接，请问您有什么解决方案吗？
> 
> 报错的地址：https://github.com/SirlyDreamer/Yunzai-Bot/runs/6815808998?check_suite_focus=true

Gitee 海外连接确实经常不顺畅，我觉得可以从 Github clone，结束后 git remote 换一下镜像地址好了。
