### ISSUE TITLE
启动后一直卡在正在探索可用服务器怎么破。。。

### ISSUE THREAD

**Issue by saiyoulala** [Le-niao/Yunzai-Bot#2]
大佬求帮忙

**Comment by Le-niao** [comment]
> 大佬求帮忙

https://github.com/takayama-lily/oicq/issues?q=%E6%8E%A2%E7%B4%A2%E5%8F%AF%E7%94%A8%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by Le-niao** [comment]
是不是node版本问题？

**Comment by saiyoulala** [comment]
> 是不是node版本问题？

好的，我试试

**Comment by saiyoulala** [comment]
> 是不是node版本问题？

还是不行，我试了16.13.0和14.18.1，大佬你用的啥版本

**Comment by Le-niao** [comment]
> > 是不是node版本问题？
> 
> 还是不行，我试了16.13.0和14.18.1，大佬你用的啥版本

探索服务器失败的报错有吗？

**Comment by saiyoulala** [comment]
> > > 是不是node版本问题？
> > 
> > 
> > 还是不行，我试了16.13.0和14.18.1，大佬你用的啥版本
> 
> 探索服务器失败的报错有吗？

没事了，我用git bash不行用powershell可以了[笑哭]，现在卡在QQ登录不是常用地，只能先挂着了
