### ISSUE TITLE
cookieUser.getCookie() 报错原因的跟踪结果

### ISSUE THREAD

**Issue by HeadmasterTan** [Le-niao/Yunzai-Bot#204]
首先是场景重现：

> 在给机器人只发送了仅包含 ltoken= 和 ltuid= 的cookie的情况下（非check.js 配置时候的cookie，是#体力的cookie），并且只有主人和机器人的情况下，发送命令#香菱（#角色），在机器人返回“米游社已退出登录”后，百分百重现bug，然后阻塞后续的相关查询

![geiheiryan](https://user-images.githubusercontent.com/24260221/173562335-7c664215-3232-48fa-93f4-6a46ce9791a7.png)

然后是造成的原因，我从源头开始回溯

![返回true](https://user-images.githubusercontent.com/24260221/173562619-0020c46a-d0ab-44e5-9fcc-217f58350023.png)

![true的后果1](https://user-images.githubusercontent.com/24260221/173564027-ceaa6f82-717d-4eee-a13f-ee409c073e02.png)

![最终后果](https://user-images.githubusercontent.com/24260221/173564050-58fc0fcf-2096-4aa2-b7ff-98e348e23a88.png)

大概就是这样，希望这个还是修复一下，毕竟有些萌新也不懂，出错了也不知道哪里出的问题

**Comment by NomadThanatos** [comment]
Duplicate as #148

**Comment by AmamiHaruka** [comment]
我提一下，描述上被归结到issue148重复，需要注意的是去config.js配置cookie是只能是ltoken和ltuid的内容。当你在这里配置如文档获取cookie方法获得到的cookie时，虽然可以通过检查ck这个命令，但是实际是不可用的，还是会引发这个报错。 @NomadThanatos

**Comment by NomadThanatos** [comment]
The fix #194  is also linked in #148 .

**Comment by 486494914** [comment]
查询别人的还是会出现同样错误

**Comment by HeadmasterTan** [comment]
> > 
> 
> 不改就和上面一样红色的报错，改为false查询别人的返回未绑定cookie，但是昨天都还能查询别人的。

bug修复前，现阶段最简单的解决方法有两个：
1. 给机器人发送完整的（包含cookie_token的）cookie，可以通过退出重新登陆米游社获取；
2. 简单粗暴的更改`./lib/components/Msg.js` 第170行`if`判断语句为：
```javascript
  if (typeof cookieUser === 'boolean' || !await cookieUser.getCookie()) {
    e.reply("暂未配置公共查询cookie，无法查询");
    return false;
  }
```

**Comment by HeadmasterTan** [comment]
啊，按错了原谅我

**Comment by HeadmasterTan** [comment]
> > 
> 
> 不改就和上面一样红色的报错，改为false查询别人的返回未绑定cookie，但是昨天都还能查询别人的。

bug修复前，现阶段最简单的解决方法有两个：

1. 给机器人发送完整的（包含cookie_token的）cookie，可以通过退出重新登陆米游社获取；
2. 简单粗暴的更改`./lib/components/Msg.js` 第170行`if`判断语句为：
``` javascript
  if (typeof cookieUser === 'boolean' || !await cookieUser.getCookie()) {
    e.reply("暂未配置公共查询cookie，无法查询");
    return false;
  }
```

**Comment by 486494914** [comment]
> 

还是有点点问题，但还是十分感谢！我自己再研究研究。

**Comment by 486494914** [comment]
> > > 
> > 
> > 
> > 不改就和上面一样红色的报错，改为false查询别人的返回未绑定cookie，但是昨天都还能查询别人的。
> 
> bug修复前，现阶段最简单的解决方法有两个：
> 
> 1. 给机器人发送完整的（包含cookie_token的）cookie，可以通过退出重新登陆米游社获取;
> 2. 简单粗暴的更改 第170行判断语句为：`./lib/components/Msg.js``if`
> 
> ```js
>   if (typeof cookieUser === 'boolean' || !await cookieUser.getCookie()) {
>     e.reply("暂未配置公共查询cookie，无法查询");
>     return false;
>   }
> ```

还是有点点问题，但还是十分感谢！我自己再研究研究。
