### ISSUE TITLE
希望角色卡片中增加圣遗物详情

### ISSUE THREAD

**Issue by ImHeroZero** [Le-niao/Yunzai-Bot#207]
最好还能和圣遗物评分那个功能整合, 群里大家最想要的就是这个

**Comment by chen8665272** [comment]
不是有一个了吗？Yunzai-Bot的插件 Miao-Plugin 就有

**Comment by ImHeroZero** [comment]
> 不是有一个了吗？Yunzai-Bot的插件 Miao-Plugin 就有
啊...抱歉,不过页面没有说明,只是作者感谢了下提供者,我就没看到
