### ISSUE TITLE
centos7+ 克隆项目之后无法运行

### ISSUE THREAD

**Issue by qq1036828060** [Le-niao/Yunzai-Bot#217]
[root@VM-4-6-centos Yunzai-Bot]# node app.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'oicq' imported from /qqBot/Yunzai-Bot/app.js

**Comment by SirlyDreamer** [comment]
请确认是否执行过`npm install`或`cnpm install`

**Comment by qq1036828060** [comment]
已解决，但是是先clone到本地windows上部署好之后，在上传到服务器解决
