### ISSUE TITLE
能把默认指令开头#改为&吗？

### ISSUE THREAD

**Issue by ialdaiaxiariyay** [Le-niao/Yunzai-Bot#223]

**Comment by SirlyDreamer** [comment]
没必要吧，如果你自己有需求的话可以查找替换（

**Comment by ialdaiaxiariyay** [comment]
我不会




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Le-niao/Yunzai-Bot] 能把默认指令开头#改为&amp;吗？ (Issue #223)






没必要吧，如果你自己有需求的话可以查找替换（

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by ialdaiaxiariyay** [comment]
我尝试过，都是报错了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月27日(星期一) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Le-niao/Yunzai-Bot] 能把默认指令开头#改为&amp;吗？ (Issue #223)






没必要吧，如果你自己有需求的话可以查找替换（

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;
