### ISSUE TITLE
代码有个bug

### ISSUE THREAD

**Issue by senaairi** [Le-niao/Yunzai-Bot#227]
lib/app/gacha.js 文件里的变量 let gachaConfig = {};
应该初始化为数组 let gachaConfig = [];
![aaa](https://user-images.githubusercontent.com/7553293/179148067-20b22066-283a-4527-b9e1-84218277f51c.png)

**Comment by NoelleDLL** [comment]
这不是数组哦，这是集合，建议了解一下js基础呢，有没有可能是你其他地方出错了！

**Comment by senaairi** [comment]
我看那个变量是存放的文件 config/genshin/gacha.json 里的东西，这里面是数组下多个集合。
那个报错最后看代码找到了问题，配置文件里的up池时间都过期后；如果继续抽卡，这里的https://github.com/Le-niao/Yunzai-Bot/blob/master/lib/app/gacha.js#L452 代码会删除最后一个池，多抽几次配置就清空了，然后就报错了
还有，我js基础很好谢谢提醒

发件人: NoelleDLL
发送时间: 2022年7月29日 9:28
收件人: Le-niao/Yunzai-Bot
抄送: lihz; Author
主题: Re: [Le-niao/Yunzai-Bot] 代码有个bug (Issue #227)

这不是数组哦，这是集合，建议了解一下js基础呢，有没有可能是你其他地方出错了！

**Comment by NoelleDLL** [comment]
你就嘴硬吧，承认自己不会有那么难吗？

**Comment by senaairi** [comment]
行行行我菜我不会我嘴硬

从 Windows 版邮件发送

发件人: NoelleDLL
发送时间: 2022年7月29日 10:01
收件人: Le-niao/Yunzai-Bot
抄送: lihz; Author
主题: Re: [Le-niao/Yunzai-Bot] 代码有个bug (Issue #227)

你就嘴硬吧，承认自己不会有那么难吗？
