### ISSUE TITLE
怎么从2.1.8升级到3.0

### ISSUE THREAD

**Issue by qq5520746** [Le-niao/Yunzai-Bot#229]
需要重新部署吗  git pull后还是老版本

**Comment by 200780381** [comment]
要的。刚刚安装

**Comment by dongb0** [comment]
3.0在main分支，你直接pull还是拉的master分支代码

**Comment by linjie5492** [comment]
git checkout master, 2.1.8
git checkout main, 3.0.0
3.0.0部署后不能用，估计作者在更新中，建议用旧版

**Comment by qq5520746** [comment]
> 3.0在main分支，你直接pull还是拉的master分支代码

直接pull  重新部署试了3,0 还不是很完善 等更新

**Comment by qq5520746** [comment]
> git checkout master, 2.1.8 git checkout main, 3.0.0 3.0.0部署后不能用，估计作者在更新中，建议用旧版

3.0等更新  老版本先继续用, 要是能把用户数据迁移到3就好了  初步看下来2和3差别很大

**Comment by YsKiKi** [comment]
关键是找不到2.1.8版本了

**Comment by KudouShinnyan** [comment]
> 关键是找不到2.1.8版本了

cd ~

**Comment by KudouShinnyan** [comment]
> 关键是找不到2.1.8版本了

cd ~
rm -rf Yunzai-Bot
git clone --depth=1 -b master https://gitee.com/Le-niao/Yunzai-Bot.git

**Comment by zhouym233** [comment]
才发现是放在了两个不同分支，readme里竟然没有任何提示...
