### ISSUE TITLE
更新后 #重启 失败  无法后台运行

### ISSUE THREAD

**Issue by motian16** [Le-niao/Yunzai-Bot#230]
从2.1.8升级到2.20报错，#重启 会提示操作失败
node app 可以正常运行
npm start 也无法后台运行
重装机器人发现，有3.0重构了，和以前一样成功运行后已经提示yunzai3.0上线成功，也能在终端看到群聊私聊信息，发送帮助等一系列指令都没有回复，终端里也没有，也无法用npm start后台运行，#重启也无反应
![Uploading Picsart_22-07-16_10-38-05-021.jpg…]()

**Comment by motian16** [comment]
![Picsart_22-07-16_10-38-05-021](https://user-images.githubusercontent.com/89713447/179336310-9b780b76-9e85-4414-90d3-71944a881ef5.jpg)

**Comment by SirlyDreamer** [comment]
3.0版本还在完善，目前帮助命令还没有实现，请先不要急

**Comment by motian16** [comment]
> 3.0版本还在完善，目前帮助命令还没有实现，请先不要急

奥好的，那我还能找到2.1.8或2.20原始的压缩包吗，想先用着，现在没机器人可用了😂

**Comment by SirlyDreamer** [comment]
`git clone --depth=1 --branch master https://gitee.com/yoimiya-kokomi/Yunzai-Bot.git`
