### ISSUE TITLE
能否提供旧版本下载

### ISSUE THREAD

**Issue by Nuist666** [Le-niao/Yunzai-Bot#232]
觉得3.0版本没有之前的版本好，能否提供旧版本下载

**Comment by 205456** [comment]
同意

**Comment by sjlei** [comment]
切换个分支即可
https://github.com/Le-niao/Yunzai-Bot/tree/master

**Comment by AnxiangLemon** [comment]
其实代码更规范了！2.0的代码 。。。

**Comment by yibeiliang151** [comment]
git clone -b master https://gitee.com/Le-niao/Yunzai-Bot.git
提取项目换这句就能下载分支了

**Comment by Yaklo** [comment]
3.0没完成不应该放到主分支，喵喵帮助都用不了
