### ISSUE TITLE
3.0版本无法添加Cookie

### ISSUE THREAD

**Issue by CanYuShang** [Le-niao/Yunzai-Bot#236]
如图。输入Cookie后机器人无任何反馈且该命令仅能在私聊使用。
![QQ图片20220716200923](https://user-images.githubusercontent.com/108755592/179354898-5d7037d3-ee92-4ea2-9b37-dc85aeb34858.jpg)
![捕获](https://user-images.githubusercontent.com/108755592/179354900-83328a5e-cd56-4773-8c84-16b3ebe8d624.PNG)

**Comment by CanYuShang** [comment]
未对/plugins/genshin/内的相关JS文件进行改动

**Comment by CanYuShang** [comment]
协议为：MACQQ

**Comment by Le-niao** [comment]
`绑定cookie`命令只是发送帮助说明，后面直接发cookie就行
![QQ截图20220717083813](https://user-images.githubusercontent.com/12881780/179379261-5b46cd1b-5ad3-4eaf-85d1-ab3ad3cd7ca8.png)

**Comment by Eden-CN** [comment]
我使用#绑定cookie后机器人未作出任何相应

**Comment by CanYuShang** [comment]
我使用#绑定Cookie后机器人未作出任何响应
