### ISSUE TITLE
无法在群聊发送信息

### ISSUE THREAD

**Issue by RivenNero** [Le-niao/Yunzai-Bot#237]
```
yunzai-bot        | [2022-07-16T20:35:08.312] [ERRO] failed to send: [Group: 某群号] undefined(46)
yunzai-bot        | [2022-07-16T20:35:08.314] [MARK] ApiRejection { code: 46, message: 'unknown' }
```

使用这个 [issue](https://github.com/Le-niao/Yunzai-Bot/issues/80) 的 docker 方法搭建的。

**Comment by RivenNero** [comment]
我发到那个 issue 下面。

**Comment by Nuist666** [comment]
大佬有解决方案吗，我也遇到了同样的问题

**Comment by Xm798** [comment]
看下 #222 是否有帮助

**Comment by RivenNero** [comment]
> 看下 #222 是否有帮助

在此之前已经看过和尝试过了，没有帮助。

**Comment by Nuist666** [comment]
我知道为什么了，不是机器人的问题，是自己号被风控了，私聊正常，群聊被风控，原因应该是我的群员狂发命令导致的。我拿自己的设备登了机器人的号，发现所有群聊消息都发不出去，会有小字提示，点击蓝色字体解除风控即可。
![Screenshot_20220716_224801 jpg](https://user-images.githubusercontent.com/104258411/179375456-0d483670-c7ea-42db-8e7a-58cbbcf4e544.jpg)

**Comment by RivenNero** [comment]
> 我知道为什么了，不是机器人的问题，是自己号被风控了，私聊正常，群聊被风控，原因应该是我的群员狂发命令导致的。我拿自己的设备登了机器人的号，发现所有群聊消息都发不出去，会有小字提示，点击蓝色字体解除风控即可。 ![Screenshot_20220716_224801 jpg](https://user-images.githubusercontent.com/104258411/179375456-0d483670-c7ea-42db-8e7a-58cbbcf4e544.jpg)

😭😭😭 我这里都没显示这行字

**Comment by Nuist666** [comment]
你拿机器人的号和其他人创建一个群聊，机器人作为群主，随便发条信息，应该有显示。

**Comment by Nuist666** [comment]
实在不行就换一个号做机器人

**Comment by RivenNero** [comment]
> 你拿机器人的号和其他人创建一个群聊，机器人作为群主，随便发条信息，应该有显示。

竟然真的可以了，谢谢！
