### ISSUE TITLE
git clone失败，连不上github

### ISSUE THREAD

**Issue by xiaomingwa** [Le-niao/Yunzai-Bot#239]
![image](https://user-images.githubusercontent.com/74846916/179394201-44e34704-18fd-4e0f-a448-921ca14dbf12.png)

**Comment by Le-niao** [comment]
连不上github的，可以将`github.com`换成`gitee.com`

**Comment by xiaomingwa** [comment]
> 连不上github的，可以将`github.com`换成`gitee.com`

已经安装完成👍

**Comment by xiaomingwa** [comment]
> 连不上github的，可以将`github.com`换成`gitee.com`

感谢回复
