### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by 02wh12** [Le-niao/Yunzai-Bot#242]
puppeteer Chromium 启动失败
1|qq  | [YzBot][01:07:22.618][MARK] [角色查询][roleIndex] #角色 处理完成 357ms
它提示这个，我应该怎么办，大佬救命

**Comment by Le-niao** [comment]
1. 没有安装puppeteer指定版本的Chromium
2. 没有安装Chromium拓展

**Comment by 02wh12** [comment]
那我应该怎么做，不太会哈哈
