### ISSUE TITLE
使用7次#十连后第八次开始使用时后台报error且没有任何信息传递到q群

### ISSUE THREAD

**Issue by WNCX** [Le-niao/Yunzai-Bot#245]
`[INFO] recv from: [Group: 群名, Member: 群员] 十连`
`[MARK] [群名] 十连:gacha`
`[ERRO] gacha.gacha`
`[ERRO] TypeError: Cannot read property 'up4' of undefined`
`      at getNowPool (file:///home/adminuser/desktop/Yunzai-bot/lib/app/gacha.js:460:13)`
`      at Module.gacha (file:///home/adminuser/desktop/Yunzai-bot/lib/app/gacha.js:237:44)`
`      at runMicrotasks (<anonymous>)`
`      at processTicksAndRejections (internal/process/task_queues.js:95:5)`
`      at async Object.dealMsg (file:///home/adminuser/desktop/Yunzai-bot/lib/dealMsg.js:193:19)`

后台在第8次开始就会报这个，然后群里什么信息都没有
重启bot之后又能用7次，然后第八次之后又报错同样的代码

**Comment by iCdo-X** [comment]
对的 我也是这个问题

**Comment by DearXuan7392** [comment]
我也遇到了

**Comment by AmamiHaruka** [comment]
same here

**Comment by AmamiHaruka** [comment]
我没怎么写过nodejs，我初步看了下代码，可能是config/genshin/gacha.json中的卡池配置文件没有更新的问题

**Comment by WNCX** [comment]
> 我没怎么写过nodejs，我初步看了下代码，可能是config/genshin/gacha.json中的卡池配置文件没有更新的问题

我也看了下代码，应该是json池子里过时了导致end没有值，所以up4和其他变量都没有了，up4作为第一个被读取的也就自然报未定义

我先去重写一下池子，如果可以解决的话我考虑pull request一下修改json

**Comment by Japex-yu** [comment]
gacha.js  452行end = gachaConfig.pop();
这里是先循环判断当前时间是否在某个卡池的结束时间之前，如果没有，end为空则pop最后一个卡池数据
这行代码在多次抽卡gachaConfig被pop空之后再次抽卡就会报错。感觉可以把end为空执行的代码改成
end = gachaConfig[gachaConfig.length - 1];
这样就是默认取最后面一个卡池

贴一下原来的代码
![image](https://user-images.githubusercontent.com/50712702/181425306-484c7bae-2cbd-4d15-9d08-6c6771ef2f89.png)

**Comment by Japex-yu** [comment]
> 用pop也会导致抽卡的时候卡池一直在变。
