### ISSUE TITLE
机器人对命令没反应

### ISSUE THREAD

**Issue by EternityXuNuo** [Le-niao/Yunzai-Bot#250]
有人进群的时候倒是会发欢迎消息，但是命令却不回应
![Z_1QQ)2O9Q(8H3_X`~$4}$C](https://user-images.githubusercontent.com/72371530/179743092-1a3b2a38-ef20-425c-98e1-42a854caf6dc.png)

**Comment by EternityXuNuo** [comment]
自己的问题，解决了

**Comment by qixikeai** [comment]
怎么解决的，大佬儿，我的角色面板和角色命座还有武器图鉴都没反应
