### ISSUE TITLE
更新到3.0无法使用 miao-plugin 插件了

### ISSUE THREAD

**Issue by iCdo-X** [Le-niao/Yunzai-Bot#251]

**Comment by iCdo-X** [comment]
查询面板也无法使用

**Comment by MLYSCEM** [comment]
这个要等喵喵插件的作者适配哦

**Comment by CuteLittleSky** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/69#issuecomment-1191475621

**Comment by yoimiya-kokomi** [comment]
miao-plugin1.9.0版本已经初步支持3.0yunzai，基础功能可正常使用
