### ISSUE TITLE
部署完成运行之后显示无法启动puppeteer。

### ISSUE THREAD

**Issue by weilai5201314** [Le-niao/Yunzai-Bot#252]
分别部署了两次3.0版本，都因为puppeteer无法启动而没办法生成图片，然后通过在github上的puppeteer/issues补安装了依赖，能生成图片，但是会显示文字错误。

![CB32735797242CE4B71D5EBB0D09E0CD](https://user-images.githubusercontent.com/99032101/179776861-edddf045-6fd8-4da4-923f-214a34feb591.jpg)

**Comment by weilai5201314** [comment]
补上了依赖之后，发送的图片都没文字
<img width="430" alt="image" src="https://user-images.githubusercontent.com/99032101/179777459-1ccabc84-40a6-4a9e-868c-d51a3f6fde90.png">

**Comment by marumosama** [comment]
文字显示成这样是没字体

**Comment by weilai5201314** [comment]
或者我自己去搜字体，然后放置在机器人文件夹的某个位置？
