### ISSUE TITLE
只能绑定个人米游社cookie吗？

### ISSUE THREAD

**Issue by xiaomingwa** [Le-niao/Yunzai-Bot#253]
输入#检查ck之后会提示未配置公共查询ck，这个公共查询ck我在config文件也没找着啊，指令各种也不知道怎么配置，这是需要配置的还是不去配置也行？另外更新面板功能时好时坏啊

**Comment by marumosama** [comment]
公共ck在config里是mysCookies

**Comment by xiaomingwa** [comment]
> 公共ck在config里是mysCookies

emmm谢了
