### ISSUE TITLE
抽卡记录json导入后统计有误

### ISSUE THREAD

**Issue by zhxycn** [Le-niao/Yunzai-Bot#255]
分支 `main` `d9afe34`

下图一为导入后的统计情况，图二为 Snap Genshin 中的统计，使用 Snap Genshin 导出的 UIGF Json 格式数据。
![image](https://user-images.githubusercontent.com/99539499/179978598-122b5fcd-05fe-46cb-b3a1-2850e061bdbc.png)
![image](https://user-images.githubusercontent.com/99539499/179978668-7174489e-7763-423e-8068-ff1194ae1e1c.png)

**Comment by yzfylyw** [comment]
![image](https://user-images.githubusercontent.com/67729330/180037419-01edc067-5a2a-494f-b527-105e1c4f6143.png)
发现了同样的问题，Genshin Wish Export导出的json和excel均是从旧到新排序，而导入云崽之后云崽是从新到旧开始分析的，也就是逆序统计的，导致所有抽卡记录数均不对

**Comment by Le-niao** [comment]
更新下重新导入看看
