### ISSUE TITLE
安装配置QQ登陆后无后续反应

### ISSUE THREAD

**Issue by Hillperson** [Le-niao/Yunzai-Bot#256]
扫码登陆后，显示加载好友成功 加载插件成功  然后就没有后续了，也没有输入cookie的步骤，不知道是哪里出了问题？

命令行最后一行是 “加载插件完成[7个]”，然后就是分割线  如果再按回车就刷新二维码了

**Comment by Hillperson** [comment]
[YzBot][21:54:18.233][MARK] Welcome, Yahaha ! 正在加载资源...                         
[YzBot][21:54:18.647][MARK] 加载了3个好友，1个群，0个陌生人                           
[YzBot][21:54:18.650][INFO] ----^_^----                                               
[YzBot][21:54:18.651][INFO] Yunzai-Bot 上线成功 版本v3.0.0                            
[YzBot][21:54:18.652][INFO] https://github.com/Le-niao/Yunzai-Bot                     
[YzBot][21:54:18.652][INFO] -----------                                               
[YzBot][21:54:18.660][INFO] 加载插件中..                                              
[YzBot][21:54:19.656][INFO] 加载定时任务[1个]                                         
[YzBot][21:54:19.657][INFO] 加载插件完成[7个]                                         
[YzBot][21:54:19.657][INFO] -----------     

然后就不动了。。。

**Comment by MLYSCEM** [comment]
可以接收消息吗

**Comment by Hillperson** [comment]
> 可以接收消息吗

可以，我那个大号好友发消息，日志里显示收到消息xxx

**Comment by Hillperson** [comment]
> 初始化没有填公共cookie了，先手动到`plugins/genshin/config/mys.pubCk.yaml`填吧
> 没有收到消息，可以重启试下

现在机器人能收到别的QQ给他的消息，但是不回复内容，这是什么问题呢？
整个CentOS也重启过几次了，然后重新运行node app，还是一样的结果

**Comment by gloat2103** [comment]
> 

我把redis重启之后好了

**Comment by gloat2103** [comment]
> > 初始化没有填公共cookie了，先手动到填吧
> > 没有收到消息，可以重启试下`plugins/genshin/config/mys.pubCk.yaml`
> 
> 现在机器人能收到别的QQ给他的消息，但是不回复内容，这是什么问题呢？ 整个CentOS也重启过几次了，然后重新运行node app，还是一样的结果
> 
> 然后昨天收了两条消息后，发现过了十分钟收到如下一条错误信息code： -2， 消息： '数据包超时 （704）'

我把redis重启之后就好了，你试试
