### ISSUE TITLE
#更新面板  经常报请求失败

### ISSUE THREAD

**Issue by WNCX** [Le-niao/Yunzai-Bot#260]
有时候是内存不能为read，有时候是econnection failed，这些都是我机器的问题

但是现在报错的是
`FetchError: request to https://enka.network/u/179580712/__data.json failed, reason: Client network socket disconnected before secure TLS connection was established.`
`at ClientRequest.emit (ecents.js:400:28)`
`at TLSSocket.socketErrorListener (_http_client.js:475:9)`
`at TLSSocket.emit (events.js:400:28)`
`at emitErrorNT (internal/streams/destroy.js:74:3)`
`at processTickAndRejections (internal/process/task_queues.js:82:21)`
`type: 'system',`
`errno: 'ECONNRESET',`
`code:'ECONNRESET',`
`erroredSyscall: undefined`

**Comment by simo8102** [comment]
其实你可以看下这个https://github.com/yoimiya-kokomi/miao-plugin/issues/63
