### ISSUE TITLE
3.0退回2.1.8之后npm start启动正常，但bot无法回复消息

### ISSUE THREAD

**Issue by dongb0** [Le-niao/Yunzai-Bot#264]
退回2.1.8之后，node app在后台能看到消息，bot功能也正常；但是换成npm start启动之后，虽然看到Job启动成功，但是bot不会回复消息了；有什么排查方案吗？

**Comment by 200780381** [comment]
操作系统环境不一致，因为3.0使用的是pnpm，2.0版本，使用的是PM 2，请尝试卸载，进行操作尝试

**Comment by linjie5492** [comment]
你解决了吗？我部署的3.0.0，根本没用，能收到消息但是bot不会回复消息，我另外部署的2.1.8是可以的，搞不懂啥原因，没报任何错误。。。

**Comment by dongb0** [comment]
> 你解决了吗？我部署的3.0.0，根本没用，能收到消息但是bot不会回复消息，我另外部署的2.1.8是可以的，搞不懂啥原因，没报任何错误。。。

我现在发现npm start启动之后，过一会再用 `pm2 list` 查，发现application其实是挂掉的；用 `pm2 logs` 命令其实看到一直在报错

```
0|Yunzai | Error: Cannot find module '/home/xxx/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/ProcessContainerFork.js'
0|Yunzai |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
0|Yunzai |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
0|Yunzai |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
0|Yunzai |     at node:internal/main/run_main_module:17:47 {
0|Yunzai |   code: 'MODULE_NOT_FOUND',
0|Yunzai |   requireStack: []
0|Yunzai | }
```

也许把整个文件夹清理重新部署能解决，但是鉴于我用 `node app` 能正常收发消息，所以我暂时用 tmux 在服务器后台启了一个终端在跑，先不折腾了；
