### ISSUE TITLE
私聊功能全在，群里发送失败

### ISSUE THREAD

**Issue by Stevenmark33** [Le-niao/Yunzai-Bot#267]
这机器人是什么原因啊，错误代码看不明白
![Screenshot_2022-07-23-13-12-05-649_com termux](https://user-images.githubusercontent.com/109842783/180592337-1e2fc836-aefc-4e10-ab7f-9656070542b8.jpg)

**Comment by Stevenmark33** [comment]
私聊机器人什么功能都能使用，但是群里的话，查询后群里图片发送失败，什么都没有

**Comment by zfmfm** [comment]
> 私聊机器人什么功能都能使用，但是群里的话，查询后群里图片发送失败，什么都没有
我和你是同一个情况，应该是QQ号的问题，我换了个QQ号就好了

**Comment by zfmfm** [comment]
@Stevenmark33 我和你是同样的情况，应该是QQ号的问题，我应该换个QQ号就好了

**Comment by StudyHB-jp** [comment]
我也遇到了相同的问题。私聊的话功能都可以使用 但是在群里发不出消息 已经尝试了将登陆设备改为手机然后开启服务挤掉已登录的手机QQ的操作，结果任然是一样的报出和楼主提供的一样的错误：failed to send .... undefined(46).

**Comment by 200780381** [comment]
软冻结手动去腾讯客服那边进行解冻申请反馈

**Comment by bud-primordium** [comment]
我也遇到过，是bot被冻住了，可以登上bot的账号，手动在群里发消息（虽然发不出去），但多试几次之后，会出现让你解冻的蓝色链接入口，发个短信就可以了

**Comment by minelg** [comment]
bot的群聊功能被冻结了换个号把。

**Comment by siwuas** [comment]
qq打开链接验证一下就好了https://accounts.qq.com/safe/message/unlock?lock_info=5_5
