### ISSUE TITLE
关于公共cookie

### ISSUE THREAD

**Issue by muguodiao** [Le-niao/Yunzai-Bot#268]
到底怎么绑，个人的绑了，其他人仍然让绑公共cookie。
之前两天用机器人号电脑端给机器人号自己发，能用了。但这两天又不行了，中间有git pull更新过，然后cookie记录貌似都没了。按之前的办法绑定还是不行。是更新的问题还是什么问题

**Comment by muguodiao** [comment]
帮助和#帮助也没回应

**Comment by Le-niao** [comment]
打开`plugins/genshin/config/mys.pubCk.yaml`自行配置公共cookie
