### ISSUE TITLE
Chromium 实例关闭或崩溃！

### ISSUE THREAD

**Issue by Rainbow503** [Le-niao/Yunzai-Bot#269]
![image](https://user-images.githubusercontent.com/74725619/180607493-556bcc39-a3f2-4b73-b92c-69cb2e4fab3b.png)

**Comment by Rainbow503** [comment]
无法发送图片！

**Comment by 200780381** [comment]
查看是否群限制，这个只有关闭运行窗口才会出现，或者软冻
