### ISSUE TITLE
作者是否忘记添加3.0或编写配置公共CK

### ISSUE THREAD

**Issue by 200780381** [Le-niao/Yunzai-Bot#272]
如果大家有公共CK， 3.0版本的机器人，麻烦发送一下命令，谢谢，或者告知文件名

**Comment by marvinli001** [comment]
找到了！！
在这个路径下 Yunzai-Bot/plugins/genshin/defSet/mys/pubCk.yaml

**Comment by Le-niao** [comment]
`plugins/genshin/config/mys/pubCk.yaml`
