### ISSUE TITLE
弱弱的问一句，3.0.0是不是还不能用？

### ISSUE THREAD

**Issue by linjie5492** [Le-niao/Yunzai-Bot#273]
新部署的3.0.0版本，启动bot没有任何报错，能收到qq信息，但是bot不会回复消息，我另外部署的2.1.8版本是可以用的，弱弱问一句，是不是3.0.0还不能使用？

**Comment by linjie5492** [comment]
不用回复了，破案了，估计是功能在完善中，有一些功能能用，但是要自己配置

**Comment by TomyJan** [comment]
屎一样一大堆配置全改了也没任何提示或者兼容/转换
从旧版覆盖升级的话 , 用新版的app.js 运行重新配置就可以用了
