### ISSUE TITLE
3.0无法启动浏览器进程，怎么解决啊

### ISSUE THREAD

**Issue by Teslaofeizao** [Le-niao/Yunzai-Bot#274]
如图：
![image](https://user-images.githubusercontent.com/80935674/180693196-e94b95a4-6b8c-43c3-8f56-3b58c52a3709.png)

**Comment by marvinli001** [comment]
窝安装了一下依赖就好了，你试一下运行
`yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y`
