### ISSUE TITLE
后台一直在重连

### ISSUE THREAD

**Issue by super-shp-12138** [Le-niao/Yunzai-Bot#285]
[YzBot][16:51:38.030][MARK] 163.177.30.225:8080 closed
[YzBot][16:51:38.115][MARK] 163.177.30.225:8080 connected
[YzBot][16:51:50.026][MARK] 163.177.30.225:8080 closed
[YzBot][16:51:50.110][MARK] 163.177.30.225:8080 connected
[YzBot][16:52:02.025][MARK] 163.177.30.225:8080 closed
[YzBot][16:52:02.108][MARK] 163.177.30.225:8080 connected
[YzBot][16:52:14.014][MARK] 163.177.30.225:8080 closed
[YzBot][16:52:14.098][MARK] 163.177.30.225:8080 connected
[YzBot][16:52:26.023][MARK] 163.177.30.225:8080 closed
[YzBot][16:52:26.109][MARK] 163.177.30.225:8080 connected
[YzBot][16:52:38.025][MARK] 163.177.30.225:8080 closed
[YzBot][16:52:38.110][MARK] 163.177.30.225:8080 connected
[YzBot][16:52:50.017][MARK] 163.177.30.225:8080 closed
[YzBot][16:52:50.099][MARK] 163.177.30.225:8080 connected
[YzBot][16:53:02.022][MARK] 163.177.30.225:8080 closed
[YzBot][16:53:02.108][MARK] 163.177.30.225:8080 connected

**Comment by Le-niao** [comment]
重复运行了，自己顶掉自己

**Comment by super-shp-12138** [comment]
怎么把重复的关了呢
