### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by ChthollyWn** [Le-niao/Yunzai-Bot#287]
![image](https://user-images.githubusercontent.com/85938618/181583129-bf12556f-b48c-4263-bda4-274689257945.png)

**Comment by ChthollyWn** [comment]
安装依赖时报错
![image](https://user-images.githubusercontent.com/85938618/181590968-c95eaf9e-d5f2-4442-bef5-69a4e7a6e581.png)

**Comment by ChthollyWn** [comment]
关于依赖库
![image](https://user-images.githubusercontent.com/85938618/181676741-6c1ffb86-5312-4a43-b154-797a367b5da1.png)
由于是ub系统，使用apt安装报错
![~1P7IVN~83`JBWPPONXBHPF](https://user-images.githubusercontent.com/85938618/181676799-d4d67495-95c4-498d-9756-cc9532ee69cd.png)
换源后依旧无法解决
求救！

**Comment by Le-niao** [comment]
![1](https://user-images.githubusercontent.com/12881780/181802647-dd61733f-6e46-4733-98f7-f452a13a9cd9.png)
装下这个依赖
