### ISSUE TITLE
米社保存的cookie是否可以新增出cookies的字段

### ISSUE THREAD

**Issue by ctrlcvs** [Le-niao/Yunzai-Bot#289]
比如我目前实现了米游社米游币签到，但是的话需要读取用户的cookie，我这块尝试过发送我的完整cookies给机器人，但是的话并没有保存到 login_ticket 跟 login_uid 数据

**Comment by Le-niao** [comment]
`login_ticket `已保存，`login_uid`和`ltuid`一样都是米游社id
