### ISSUE TITLE
机器人可以监听消息，但是不能触发指令了也没有报错，有人出现过这种问题吗？

### ISSUE THREAD

**Issue by ying-leader** [Le-niao/Yunzai-Bot#290]
![image](https://user-images.githubusercontent.com/110163369/181674995-900e282b-42af-4e43-bdd3-e1d1c440710c.png)

**Comment by Le-niao** [comment]
可以尝试其他指令看有没有反应

**Comment by ying-leader** [comment]
> 可以尝试其他指令看有没有反应

我试了其他的都不行

**Comment by Le-niao** [comment]
日志前缀都不一样，请等加载完成后再发消息
