### ISSUE TITLE
自动签到功能失效了吗

### ISSUE THREAD

**Issue by ShiinaRinne** [Le-niao/Yunzai-Bot#295]
v2时还可以正常使用，替换为v3后功能似乎失效了，仅可发送`#签到`手动签到。
![image](https://user-images.githubusercontent.com/45081750/181739074-1c7dcaa6-4972-4b16-b137-f1d550a0d0c3.png)

目前使用的版本是[4f73248](https://github.com/Le-niao/Yunzai-Bot/commit/4f732489d29fa5793e736dd38861f2a1a7e764be)

**Comment by Le-niao** [comment]
没有和之前一样，12:02就开始签到任务

**Comment by ShiinaRinne** [comment]
![image](https://user-images.githubusercontent.com/45081750/181802423-654725d6-98b0-4c66-adf0-2729ce0c1b58.png)
![image](https://user-images.githubusercontent.com/45081750/181803122-fd75e257-f46a-47c4-979c-0ef5feaa70d3.png)


米游社看了一下确实签到成功了，日志也有显示，只是bot这里没提示

加上前几天签到失败(已修复)的问题，误以为自动签到失效了
![image](https://user-images.githubusercontent.com/45081750/181802727-bfab618d-86df-415e-a5c2-3272b4a82f64.png)
![image](https://user-images.githubusercontent.com/45081750/181802785-12690543-4891-4707-8a23-a9e101d2942a.png)
