### ISSUE TITLE
QQ登入问题

### ISSUE THREAD

**Issue by 1458320934** [Le-niao/Yunzai-Bot#296]
QQ登入最近扫码 文件里面设置成密码登入也输入了密码还是登入不了 只能扫码 利用2.2版本的文件可以实现直接登入不用扫码 但是一重连就又要扫码 重启yunzai也要扫码 只要不重连重启yunzai也不会要扫码

**Comment by Le-niao** [comment]
可以尝试用密码登录，用滑动验证app过验证

**Comment by 1458320934** [comment]
> 可以尝试用密码登录，用滑动验证app

> 可以尝试用密码登录，用滑动验证app过验证

切换不了密码登入 输入了密码还是需要扫码

**Comment by 1458320934** [comment]
切换不了密码登入 输入了密码之后还是跳出来扫码
