### ISSUE TITLE
插件热更新时对于新增文件验证文件后缀

### ISSUE THREAD

**Issue by liuly0322** [Le-niao/Yunzai-Bot#298]
https://github.com/Le-niao/Yunzai-Bot/blob/fa4cf1e68e401ad505ab72e86de33be57b51841c/lib/plugins/loader.js#L697
现在是监听所有新增文件，但只有 js 文件可能是需要加载的插件
是否考虑增加：
```js
if (!appName.endsWith('.js')) return
```
场景：插件可能产生一些临时文件

**Comment by Le-niao** [comment]
已增加
