### ISSUE TITLE
大佬们，请问这种问题你们是怎么解决的？

### ISSUE THREAD

**Issue by 200780381** [Le-niao/Yunzai-Bot#299]
他说我的cookie已经达到上限，无法查询到新的uid，使用c佬的插件也会提示这一个
![Screenshot_20220730_102915_com tencent mobileqq](https://user-images.githubusercontent.com/87887733/181866800-ebd1f80e-82be-4d46-9c91-5f89c0174f22.jpg)

**Comment by LiTTTTT87** [comment]
重新弄公共ck

**Comment by letter-xin** [comment]
我在公共ck里加了好几个ck，用不满上限就没事

**Comment by 200780381** [comment]
> 

还是不行

**Comment by Le-niao** [comment]
更新，然后配置多个公共ck
