### ISSUE TITLE
win绑定uid报错

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [Le-niao/Yunzai-Bot#30]
![image](https://user-images.githubusercontent.com/94744908/158745345-8af42903-74a9-4bcd-93c1-c81593b520dd.png)

**Comment by Le-niao** [comment]
浏览器没装成功，可以试下删除node_modules，重新cnpm install安装

**Comment by Zoe-Wh1t3zZ** [comment]
还是报错叫remove node_modules

**Comment by Zoe-Wh1t3zZ** [comment]
![image](https://user-images.githubusercontent.com/94744908/159104770-22538cb5-e65e-49a6-a98d-272f6b7e3e9b.png)

**Comment by Le-niao** [comment]
![...](https://user-images.githubusercontent.com/12881780/159104906-99479efe-b74a-424c-81ab-6fe4cb3ccdaa.png)

**Comment by Zoe-Wh1t3zZ** [comment]
ok环境变量手动配置了下，谢谢！
