### ISSUE TITLE
关闭新人入群欢迎

### ISSUE THREAD

**Issue by HoratioShaw** [Le-niao/Yunzai-Bot#301]
请问如何关闭新人入群欢迎和禁止非主人拉群（

**Comment by liuly0322** [comment]
禁止非主人拉群：
https://github.com/Le-niao/Yunzai-Bot/blob/d0a40ff8f317f51e362fe8882f6020fe7d68d230/config/default_config/other.yaml#L4
更改为 0，为了不影响升级，建议该文件保留不动，拷贝到与 default_config 同级的 config 目录下，在拷贝后的文件更改该值

新人入群欢迎：
删除这一文件：https://github.com/Le-niao/Yunzai-Bot/blob/main/plugins/example/example3.js
或者写一个与该插件触发正则相同的插件，并设置更高的优先级以屏蔽原插件
前者可能会影响后续升级

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/510464745544bd16ac1275c8d1491a0d7e6f0216/config/default_config/group.yaml#L16
在这里禁用`欢迎新人`就行
