### ISSUE TITLE
什么时候可以接入频道使用，就是希望云崽能支持频道

### ISSUE THREAD

**Issue by Guitu-cc** [Le-niao/Yunzai-Bot#302]
什么时候可以接入频道使用，就是希望云崽能支持频道

**Comment by liuly0322** [comment]
本项目通过 [oicq](https://github.com/takayama-lily/oicq) 实现 qq API 交互，由于 oicq 并不支持 qq 频道（原作者虽然发布了一个插件，但是并没有后续维护，也没有实现发送图片等功能，因此可能比较困难

qq 频道官方提供的[接入方式](https://bot.q.qq.com/wiki/#%E6%8E%A5%E5%85%A5%E6%B5%81%E7%A8%8B)也比较复杂，因此最起码不是近期能有的功能了（

**Comment by Le-niao** [comment]
不用频道，没有动力支持
