### ISSUE TITLE
卡池自己在变

### ISSUE THREAD

**Issue by XiaoGanCN** [Le-niao/Yunzai-Bot#309]
![无标题72_20220731134335](https://user-images.githubusercontent.com/76635216/182012062-8cf0c374-e1e5-481e-9ea4-88ab4a40ec7a.png)
水友十连的时候池子一直在变，一到钟离就抽不了了，发送十连没有任何回复了
还有，用#更新 后重启更新不了，一直是2.1.8，直接git后发送#更新说是最新版本，但还是2.1.8
![Screenshot_20220731_135144](https://user-images.githubusercontent.com/76635216/182012250-a65d2925-6199-40fd-ad03-c3a256a70f1a.jpg)

**Comment by Le-niao** [comment]
自行修改卡池，或者更新3.0

**Comment by XiaoGanCN** [comment]
我没更成功 要把yunzai-bot目录全删吗？
还有卡池咋改（我很逊
