### ISSUE TITLE
#角色列表

### ISSUE THREAD

**Issue by RockRadix** [Le-niao/Yunzai-Bot#310]
角色列表-满亲密度变成0级。
![72ac2b9b455ff6ce86982e40df93e490](https://user-images.githubusercontent.com/99504275/182013261-e68a0fe0-07d8-4f85-b24d-2a70ca3672ff.jpg)

**Comment by Le-niao** [comment]
列表0的只有命座...

**Comment by RockRadix** [comment]
看错了之前V2版本，是有爱心图标的，V3版本变数字了。

**Comment by Le-niao** [comment]
专门给你加了个图标，防止眼瞎...
![image](https://user-images.githubusercontent.com/12881780/182024487-d1015034-5233-4f0c-b5a3-53bfe3ca6609.png)
