### ISSUE TITLE
Yunzai3.0遇到Chromium启动失败如何解决? 已经是用apt安装chromium-browser的了

### ISSUE THREAD

**Issue by KudouShinnyan** [Le-niao/Yunzai-Bot#311]
是用Termux的ubuntu弄的, ubuntu22.04和20.04都这样
![182014082-63dd946d-170f-4397-8e31-0acf71ec9a8d](https://user-images.githubusercontent.com/68854981/182017463-e6bbc10a-44fd-4dfe-9ac1-438b8413f067.png)
![182015313-833f2c38-ee10-4190-9e95-6541664b5e5c](https://user-images.githubusercontent.com/68854981/182017468-6cd2c929-0099-4d32-87a6-92bc64e8c8ac.png)
![182016294-05cb6c52-fccb-4351-92f0-fa5b8f3284d6](https://user-images.githubusercontent.com/68854981/182017474-376df6bb-3c6b-4876-8693-f24762726a86.PNG)

ubuntu 18.04则是pnpm都装不上…

**Comment by Le-niao** [comment]
`apt install chromium-browser -y`
apt安装就行

**Comment by KudouShinnyan** [comment]
> `apt install chromium-browser -y` apt安装就行

(这个就像标题说的安装过了的, 但它还是提示启动失败所以旧尝试提示说的snap install chromium)

**Comment by KudouShinnyan** [comment]
(屈服于ubuntu18.04和node.js17了)
