### ISSUE TITLE
更新卡池

### ISSUE THREAD

**Issue by HoratioShaw** [Le-niao/Yunzai-Bot#312]
请问3.0如何更新卡池，现在还是在宵宫池

**Comment by Le-niao** [comment]
现在是还是万叶池，8月2号才开宵宫池

**Comment by HoratioShaw** [comment]
> 现在是还是万叶池，8月2号才开宵宫池

但是我现在抽卡就是肖工，蛮怪的
![Uploading -3a785c23fc91dd3c.jpg…]()

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/c35cfce851e221412f9f9847e70bc5ec51005532/plugins/genshin/defSet/gacha/pool.yaml#L36
万叶池结束时间设置是28号，所以新卡池都是提前几天的
