### ISSUE TITLE
【建议】既然v3使用了pnpm，那么把pnpm的workspace特性也使用起来吧

### ISSUE THREAD

**Issue by sjlei** [Le-niao/Yunzai-Bot#314]
既然v3使用了pnpm，那么把pnpm的workspace特性也使用起来吧，这对开发插件有很大的帮助，也能让插件更加灵活。
比如我可以在插件里定义一个package.json，定义一些依赖，然后在Yunzai根目录就可以快速安装这些依赖。

只需要写一个配置文件`pnpm-workspace.yaml`即可，不会对现有的项目结构产生影响。
<https://pnpm.io/zh/pnpm-workspace_yaml>

参考文档：<https://pnpm.io/zh/workspaces>

![image](https://user-images.githubusercontent.com/34293221/182028370-1577f32d-6834-4dee-8bbd-f06db957c03b.png)
![image](https://user-images.githubusercontent.com/34293221/182028619-c20ca318-809d-48eb-bad6-076b8cfdd84d.png)

**Comment by Le-niao** [comment]
已增加

**Comment by sjlei** [comment]
nice，这样写插件就能灵活很多了😺
