### ISSUE TITLE
#更新面板 报错

### ISSUE THREAD

**Issue by goodapple8946** [Le-niao/Yunzai-Bot#316]
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///D:/Repo/Yunzai-Bot/node_modules/_node-fetch@3.2.6@node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.request (file:///D:/Repo/Yunzai-Bot/plugins/miao-plugin/components/profile-data/enka.js:15:16)
    at async Object.request (file:///D:/Repo/Yunzai-Bot/plugins/miao-plugin/components/Profile.js:61:14)
    at async Module.getProfile (file:///D:/Repo/Yunzai-Bot/plugins/miao-plugin/apps/character/profile-common.js:185:14)
    at async Object.dealMsg (file:///D:/Repo/Yunzai-Bot/lib/dealMsg.js:193:19)

----------------------------------
----------------------------------
console.log(req)

Response {
  size: 0,
  [Symbol(Body internals)]: {
    body: BrotliDecompress {
      _writeState: [Uint32Array],
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      bytesWritten: 0,
      _handle: [BrotliDecoder],
      _outBuffer: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 68 74 6d 6c 20 6c 61 6e 67 3d 22 65 6e 2d 55 53 22 3e 0a 3c 68 65 61 64 3e 0a 20 20 20 20 3c 74 69 ... 16334 more bytes>,
      _outOffset: 0,
      _chunkSize: 16384,
      _defaultFlushFlag: 0,
      _finishFlushFlag: 2,
      _defaultFullFlushFlag: 1,
      _info: undefined,
      _maxOutputLength: 4294967296,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null,
      [Symbol(kError)]: null
    },
    stream: BrotliDecompress {
      _writeState: [Uint32Array],
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      bytesWritten: 0,
      _handle: [BrotliDecoder],
      _outBuffer: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 68 74 6d 6c 20 6c 61 6e 67 3d 22 65 6e 2d 55 53 22 3e 0a 3c 68 65 61 64 3e 0a 20 20 20 20 3c 74 69 ... 16334 more bytes>,
      _outOffset: 0,
      _chunkSize: 16384,
      _defaultFlushFlag: 0,
      _finishFlushFlag: 2,
      _defaultFullFlushFlag: 1,
      _info: undefined,
      _maxOutputLength: 4294967296,
      [Symbol(kCapture)]: false,
      [Symbol(kCallback)]: null,
      [Symbol(kError)]: null
    },
    boundary: null,
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    type: 'default',
    url: 'https://enka.network/u/100550257/__data.json',
    status: 403,
    statusText: 'Forbidden',
    headers: {
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
      'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
      'cf-chl-bypass': '1',
      'cf-ray': '733b721a3f067ca7-LAX',
      connection: 'close',
      'content-encoding': 'br',
      'content-type': 'text/html; charset=UTF-8',
      date: 'Mon, 01 Aug 2022 03:21:47 GMT',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
      nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
      'permissions-policy': 'accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
      'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=oGfBirdaFOweBsR%2BtHwceCr5WLYIZCt5oskNudtb%2B4I9ztdYodTmIaffMzKYkhiU5kMNLOt6u7it2Ep0RdIlazf2AZVNrghc94qaCwILfGreGNrzfp0tLUXkxuoTyNo%3D"}],"group":"cf-nel","max_age":604800}',
      server: 'cloudflare',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding',
      'x-frame-options': 'SAMEORIGIN'
    },
    counter: 1,
    highWaterMark: 16384
  }
}

**Comment by Le-niao** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/63#issue-1299812134
