### ISSUE TITLE
一直提示：[安全提醒]当前登录存在安全风险，请使用常用设备或通过手机号登录

### ISSUE THREAD

**Issue by sulorrr** [Le-niao/Yunzai-Bot#319]
昨天被临时冻结了，解冻了之后登不上，一直提示：安全提醒]当前登录存在安全风险，请使用常用设备或通过手机号登录。，不论是怎么登也上不去，

**Comment by sulorrr** [comment]
![image](https://user-images.githubusercontent.com/110394561/182161348-3058f6e7-e797-4904-8058-b165c5b08fe3.png)

**Comment by Le-niao** [comment]
没有输入ticket，用滑动验证app获取再输入

**Comment by sulorrr** [comment]
滑动验证app?滑动完回来按一下回车吗？还是怎么操作...不好意思，有点小白..

**Comment by sulorrr** [comment]
解决了大佬！！感谢
