### ISSUE TITLE
能加个每日天赋、武器素材查看的功能不？

### ISSUE THREAD

**Issue by FengmiQingmei** [Le-niao/Yunzai-Bot#32]
能加个今日天赋素材、武器素材查看的功能不？群里小伙伴这功能用的挺多的

**Comment by NiHang** [comment]
现在能看到自己角色和武器的赋素材、武器素材。但是每天总的素材看不到了，导致自己没有的角色或武器都看不了了。想给下版本角色准备就没法看了。

**Comment by FengmiQingmei** [comment]
你的邮件我已收到。

**Comment by NiHang** [comment]
看能不能加个指令查询每天总的天赋素材和武器素材

**Comment by lin-4414** [comment]
群里有每日素材的插件

**Comment by liuzj288** [comment]
> 群里有每日素材的插件

群号是多少啊

**Comment by FengmiQingmei** [comment]
你的邮件我已收到。
