### ISSUE TITLE
#原石统计命令无效

### ISSUE THREAD

**Issue by ChthollyWn** [Le-niao/Yunzai-Bot#326]
![image](https://user-images.githubusercontent.com/85938618/182278028-4bd35275-a2ab-406d-849c-bd8d20978f13.png)
![image](https://user-images.githubusercontent.com/85938618/182278045-f2ac72e7-619f-4ca0-b7c7-0cf8d8c7b299.png)
如图，使用命令后无反应，后台也没有报错信息

**Comment by ChthollyWn** [comment]
另外，其余指令中的部分指令也无反应
![image](https://user-images.githubusercontent.com/85938618/182278347-ee0057c2-a48a-4a79-be50-0a605926a1de.png)
![image](https://user-images.githubusercontent.com/85938618/182278382-783f1296-8a97-43bc-b3ce-2ab3611b94c7.png)
后台也无报错信息

**Comment by KudouShinnyan** [comment]
![Screenshot_20220802-152925_QQ](https://user-images.githubusercontent.com/68854981/182317521-721bba7d-e7f1-4ed9-a172-1dcfd9436613.png)

**Comment by KudouShinnyan** [comment]
![Screenshot_20220802-153048_QQ](https://user-images.githubusercontent.com/68854981/182317779-328680c3-c0d4-4cec-bea0-80e6de318352.png)

**Comment by KudouShinnyan** [comment]
![Screenshot_20220802-153214_QQ](https://user-images.githubusercontent.com/68854981/182318041-9c0a8cd9-5218-42c5-aa2d-980e051f3395.png)

**Comment by Le-niao** [comment]
不是没有，是消息被拦截了，更新下miao-plugin
