### ISSUE TITLE
关于自动签到与数据迁移的问题

### ISSUE THREAD

**Issue by Haorwen** [Le-niao/Yunzai-Bot#327]
Yunzai-bot从2.x升级到了3.x是好事，但是原本的自动签到功能咋就没了，以及从2.x迁移到3.x，数据的储存方式都大改了，请问怎么迁移呢

**Comment by Ailumar** [comment]
请问是通过#配置ck触发吧,触发后我是发用户数据文件给bot?还有超时这东西好玄学,有中断指令吗?

**Comment by TrisAXJ** [comment]
怎么触发加载旧数据啊 原先json文件我放在文件夹里了 好像没什么用

**Comment by daheiguai** [comment]
把那个NoteCookie.json文件放到MysCookie下重启机器人就行了
