### ISSUE TITLE
树莓派3B e14版本(Debian11)显示登录QQ后，node进程秒没

### ISSUE THREAD

**Issue by OCTSJimmy** [Le-niao/Yunzai-Bot#328]
云崽使用3.0，master最新commit。
树莓派3B e14版本(Debian11)显示登录QQ后，node进程秒没.

cnpm install 完全正常，无任何报错。
node app 首次能正常执行到登录小号。

之后无论是二维码方式登录，还是滑动验证码登录，还没来得及扫码或者滑动验证码，node进程已经消失不见了。
没有任何报错信息。

求问UP大大这个需要如何调试？

**Comment by Le-niao** [comment]
用pnpm安装依赖试下

**Comment by Le-niao** [comment]
`node -v` 查看版本

**Comment by Ponysesame** [comment]
实测国产香橙派orangepi 3 LTS(Ubuntu)也无法正常扫码验证，通过修改config文件夹下面的qq.yaml文件采用密码登录可以解决。

**Comment by OCTSJimmy** [comment]
> `node -v` 查看版本
node版本最新的，通过n stable装的。
个人盲猜可能是系统用的armv7(armfh)的安装包装的，这玩意是x86的架构。周末换系统，更新到aarch11(arm64)试试。

**Comment by OCTSJimmy** [comment]
> 实测国产香橙派orangepi 3 LTS(Ubuntu)也无法正常扫码验证，通过修改config文件夹下面的qq.yaml文件采用密码登录可以解决。

多谢测试。密码登录没指望了，因为要滑动验证码 /(ㄒoㄒ)/~~

**Comment by OCTSJimmy** [comment]
果然，替换arm64内核的系统以后，成功运行云崽了。
