### ISSUE TITLE
更新面板报错

### ISSUE THREAD

**Issue by hubu2021** [Le-niao/Yunzai-Bot#330]
今天突然就这样了
![Snipaste_2022-08-02_19-56-26](https://user-images.githubusercontent.com/95953449/182371627-93ea5d3e-74ce-480c-b0e3-62210099e947.png)

x下面是一直都有的情况
![Snipaste_2022-08-02_19-52-10](https://user-images.githubusercontent.com/95953449/182371692-54278a13-c436-4abc-8c4f-cc0d44743060.png)

**Comment by Le-niao** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/63#issue-1299812134
