### ISSUE TITLE
关于bot的qq号初始化文件

### ISSUE THREAD

**Issue by ctrlcvs** [Le-niao/Yunzai-Bot#335]
V2版本是支持直接用BotConfig点出用户账号以及bot账号的，然后V3的话必须引用文件才能获取到bot的qq，是否可以把bot的qq以及主人的qq公开出来，如果已经公开出来了麻烦告知调用方法

**Comment by liuly0322** [comment]
## 主人 qq

`./config/config/other.yaml`

## bot qq

`./config/config/qq.yaml`

初始这两个文件不存在，可以从 `./config/default_config` 下复制一份

**Comment by ctrlcvs** [comment]
不是文件没有初始化而是我想要临时调用获取到bot的qq或者是bot主人的qq如图
![image](https://user-images.githubusercontent.com/73279880/182542253-fd76411a-e239-4bfb-bfe4-992efc05c281.png)
![image](https://user-images.githubusercontent.com/73279880/182542301-454dd427-5f71-40ab-bfd5-fc4a6956f473.png)
这种情况下通过import得到的数据显然不是我要的而且通过点是点不出来的

**Comment by liuly0322** [comment]
> 不是文件没有初始化而是我想要临时调用获取到bot的qq或者是bot主人的qq如图 ![image](https://user-images.githubusercontent.com/73279880/182542253-fd76411a-e239-4bfb-bfe4-992efc05c281.png) ![image](https://user-images.githubusercontent.com/73279880/182542301-454dd427-5f71-40ab-bfd5-fc4a6956f473.png) 这种情况下通过import得到的数据显然不是我要的而且通过点是点不出来的

分别在

https://github.com/Le-niao/Yunzai-Bot/blob/50f1a0083ecc6476cc91dbd03ba6e8611a23c61f/lib/config/config.js#L29

和

https://github.com/Le-niao/Yunzai-Bot/blob/50f1a0083ecc6476cc91dbd03ba6e8611a23c61f/lib/config/config.js#L53

提供了接口，直接调用图上 cfg 对象的这个方法看看？

**Comment by Le-niao** [comment]
`cfg.default.qq`
`cfg.default.masterQQ `
