### ISSUE TITLE
机器人上传图片显示网络错误，报错代码如下：

### ISSUE THREAD

**Issue by abcdeqwq** [Le-niao/Yunzai-Bot#336]
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by Le-niao** [comment]
腾讯偶尔抽风，图片上传失败

**Comment by abcdeqwq** [comment]
解决了，是网络的问题，换网就行
