### ISSUE TITLE
手机号验证登录问题

### ISSUE THREAD

**Issue by ZzzHe2333** [Le-niao/Yunzai-Bot#337]
大佬好，首先很感谢你提供这个app以及代码。
就是在用的时候，部署在本地扫码问题不算大。
**但是部署在服务器的时候，出现了QQ风控的问题，密码和扫码都没办法解决了。**
希望可以出一个由手机号登录的功能，感谢。
pptp虚拟VPN访问弄了两天还是没办法，那只能求助大佬，能不能弄一个新的方式了，应该也不难吧？谢谢了

**Comment by Le-niao** [comment]
风控是腾讯整的，换手机号登录也一样

**Comment by ZzzHe2333** [comment]
ouo阿这....那为啥我在服务器上可以远程登录QQ，但是...
