### ISSUE TITLE
3.0版本米游社签到问题

### ISSUE THREAD

**Issue by Jinyihua** [Le-niao/Yunzai-Bot#342]
3.0版本
#签到命令没有反应 查看日志是请求错误
#全部签到 日志显示错误 返回的是签到成功 实际米游社没有签到成功
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/19164606/182781512-0f3dac2e-4ea0-40eb-895d-3188acc27164.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/19164606/182781544-96300daa-9511-4f4d-9f45-ee02ebeef35b.png">

**Comment by habacat** [comment]
同样的问题，Mark

**Comment by Gu-Miao** [comment]
+1

**Comment by anshifa958** [comment]
> 米游社原神签到接口寄了？，暂时无法签到

云函数的签到还是正常的，但是bot的好像寄了
![屏幕截图 2022-08-04 211902](https://user-images.githubusercontent.com/83939886/182856987-6626b229-cec9-4bd8-849f-3fc27c87eeb9.png)

**Comment by lancelotpro** [comment]
Mark下，同样invalid request

**Comment by lanlanwa** [comment]
++

**Comment by Le-niao** [comment]
已修复，更新下就行

**Comment by PrussianBlueCN** [comment]
![94D54789-457C-4E32-89CD-393322825164](https://user-images.githubusercontent.com/110645427/182983354-8215c9f7-e8df-4087-a1ab-3cab8b3cc18d.png)
![0246A939-511C-49DA-B12F-B701B78EAC75](https://user-images.githubusercontent.com/110645427/182983693-f6ecb1c0-8f02-4a63-a058-0786eba28c69.jpeg)


更新依然返回invalid request，控制台重启不能解决问题

**Comment by setobox** [comment]
同上，更新后依然没有解决问题。

**Comment by Jinyihua** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/19164606/182985827-5e51dfa6-c7df-4c2a-b01b-6ad27331b1c3.png">
<img width="844" alt="image" src="https://user-images.githubusercontent.com/19164606/182985868-90bb9c89-51b4-480a-b693-6d9256d96e92.png">
我这边更新后 是能签到成功

**Comment by B1ackSand** [comment]
我这边是v2.1.8，bot签到还是报`米游社签到：invalid request`的错误，拉取过更新，并且在终端手动重启过。

**Comment by ctrlcvs** [comment]
目前2.1.8已经不在维护可以移动到喵喵目前在维护的2.x版本云崽https://gitee.com/yoimiya-kokomi/Yunzai-Bot

**Comment by B1ackSand** [comment]
感谢告知，现可以正常签到。
