### ISSUE TITLE
无法登录QQ

### ISSUE THREAD

**Issue by YvetteVv** [Le-niao/Yunzai-Bot#344]
二维码一直失效，输入账号密码显示
[YzBot][08:23:26.502][ERRO] [安全提醒]当前登录存在安全风险，请使用常用设备或通过手机号登录。
[YzBot][08:23:26.502][ERRO] 登录错误，已停止运行

**Comment by Le-niao** [comment]
二维码刷新几次试下，要在同一网络下刷码，或者你更换其他登录设备试试

**Comment by YvetteVv** [comment]
我是服务器登不上

**Comment by BeterKing** [comment]
自己本地搭建一个，替换一下data里面带有你qq号的文件

**Comment by YvetteVv** [comment]
> 二维码刷新几次试下，要在同一网络下刷码，或者你更换其他登录设备试试

服务器端现在不支持吗？

**Comment by YunJin77** [comment]
> > 二维码刷新几次试下，要在同一网络下刷码，或者你更换其他登录设备试试
> 
> 服务器端现在不支持吗？

二维码登陆只支持同 ip

可以考虑

- 使用手机号登录
- 如果使用二维码登陆，可以如 @BeterKing 所说，先在本地电脑端登录，然后服务器端拷贝本地生成的 data 数据文件夹中

**Comment by Le-niao** [comment]
ticket输入已增加提示
