### ISSUE TITLE
v3.0 bot如何从win环境迁移到另一台机器，也是win环境

### ISSUE THREAD

**Issue by uyaddayu** [Le-niao/Yunzai-Bot#347]
有无教程，要把用户数据一起搬过去，用户数据要搬过去最重要

**Comment by liuly0322** [comment]
- `data` 文件夹
- `config/config` 文件夹
  - 这些是配置文件，不一定必须迁移
  - 如果你安装了别的插件，可能也需要一并注意别的插件的配置文件
- 在 redis 安装目录下有 dump.rdb 文件，复制到新机器的同样位置

**Comment by uyaddayu** [comment]
> * `data` 文件夹
> * `config/config` 文件夹
>   
>   * 这些是配置文件，不一定必须迁移
>   * 如果你安装了别的插件，可能也需要一并注意别的插件的配置文件
> * 在 redis 安装目录下有 dump.rdb 文件，复制到新机器的同样位置

如果把整个文件夹拷贝过去能直接用吗？

**Comment by YunJin77** [comment]
> > * `data` 文件夹
> > * `config/config` 文件夹
> >   
> >   * 这些是配置文件，不一定必须迁移
> >   * 如果你安装了别的插件，可能也需要一并注意别的插件的配置文件
> > * 在 redis 安装目录下有 dump.rdb 文件，复制到新机器的同样位置
> 
> 如果把整个文件夹拷贝过去能直接用吗？

最好保证两个仓库版本相同，应该是可以的

**Comment by uyaddayu** [comment]
> > > * `data` 文件夹
> > > * `config/config` 文件夹
> > >   
> > >   * 这些是配置文件，不一定必须迁移
> > >   * 如果你安装了别的插件，可能也需要一并注意别的插件的配置文件
> > > * 在 redis 安装目录下有 dump.rdb 文件，复制到新机器的同样位置
> > 
> > 
> > 如果把整个文件夹拷贝过去能直接用吗？
> 
> 最好保证两个仓库版本相同，应该是可以的

![image](https://user-images.githubusercontent.com/40861535/182998596-58227b29-32a5-4aeb-9566-9173f83caf3b.png)
已经被吓死，怎接近2G

**Comment by uyaddayu** [comment]
迁移完了，丢了一部分用户cookie数据。。
