### ISSUE TITLE
工作空间报错

### ISSUE THREAD

**Issue by Chenzyang02** [Le-niao/Yunzai-Bot#352]
ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.
这个怎么解决啊，使用docker安装的，一直无限重启

**Comment by liuly0322** [comment]
目前 docker 这个源 sirly/yunzai-bot:plus 的 entrypoint 脚本暂未更新 @SirlyDreamer ，目前主线代码应该搜修复的（插件的依赖需要用 pnpm add -w 添加）

解决方法：

- 等待 docker 镜像更新
  - 话说 @SirlyDreamer 有利用 CI 在 build 后自动上传更新 docker 镜像的打算吗w
- 手动 clone 安装

**Comment by SirlyDreamer** [comment]
plus镜像的构建并没有使用pnpm，这个应该是yunzai-bot/dev（v3版本）出现的问题，目前新镜像已经在构建

CI更新镜像早已实现，Action记录在 https://github.com/SirlyDreamer/Yunzai-Bot/actions

抱歉最近比较忙，镜像的更新可能不及时，请见谅。

如果您能帮忙提供修复，请向 https://github.com/SirlyDreamer/Yunzai-Bot 提交pr

其中dockerdev分支是云崽2.2.1版本（喵佬维护）的sirly/yunzai-bot:latest

dockerplus分支是sirly/yunzai-bot:plus

dockerdev_v3是云崽3.0版本的sirly/yunzai-bot:dev

**Comment by KeyPJ** [comment]
#314 可以参考这个
在插件根目录 npm init,后修改type为module,并添加依赖


`{
  "name": "miao-plugin",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "image-size": "^1.0.2"
  }
}
`

**Comment by Chenzyang02** [comment]
已经解决了，我是手动改的，先拉取dev镜像，接着启动容器，先不要添加插件，先进入容器内部修改entrypoint.sh文件里的两个插件安装依赖的命令，然后再退出容器，拉取插件就可以正常运行了，问题就出在这个文件的安装依赖命令是`pnpm install 包名 -P`,这个命令会报错，改回`pnpm add 包名 -w`即可
