### ISSUE TITLE
json或xlsx导入问题

### ISSUE THREAD

**Issue by tommynanny** [Le-niao/Yunzai-Bot#354]
![image](https://user-images.githubusercontent.com/22390882/182996220-be25cf92-f8cf-4bdc-9f2e-845ed2aba432.png)
![image](https://user-images.githubusercontent.com/22390882/182996322-e37726f0-99a7-49a9-825f-5f6bdf1e5b8a.png)

**Comment by YunJin77** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/5ac06128b0b5cd354ad42c5a1d54416464d8084b/plugins/genshin/apps/gcLog.js#L173

删除文件名开头的UIGF_以匹配正则表达式试一下？

这里应该是正则范围太窄了，后续可能考虑把^去掉？

**Comment by Le-niao** [comment]
更新下就行，这里已经改了 1896660cb47b04780743dde3fbaba14081567ae3

**Comment by YunJin77** [comment]
> 更新下就行，这里已经改了 [1896660](https://github.com/Le-niao/Yunzai-Bot/commit/1896660cb47b04780743dde3fbaba14081567ae3)

line 159 和 line 173 的或之后的判断似乎应该删去（accept 里进行了判断，否则应该还是接收不到？

**Comment by Le-niao** [comment]
> > 更新下就行，这里已经改了 [1896660](https://github.com/Le-niao/Yunzai-Bot/commit/1896660cb47b04780743dde3fbaba14081567ae3)
> 
> line 159 和 line 173 的或之后的判断似乎应该删去（accept 里进行了判断，否则应该还是接收不到？

.....多谢提醒，等下就改

**Comment by tommynanny** [comment]
谢谢大佬们的帮忙，
请教一下，因为我是用swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:dev的docker镜像；
这个image是根据git commit自动build的么? 如果不是的话，是不是推荐用docker目录下dockerfile本地build image来获取及时更新

**Comment by liuly0322** [comment]
> 谢谢大佬们的帮忙，修改文件名后就可以识别了 ![image](https://user-images.githubusercontent.com/22390882/183004908-65a3d433-a63f-4dd2-9a2b-2c2c9175f14a.png)
> 
> 请教一下，因为我是用swr.cn-south-1.myhuaweicloud.com/sirly/yunzai-bot:dev的docker镜像； 这个image是根据git commit自动build的么? 如果不是的话，是不是推荐用docker目录下dockerfile本地build image来获取及时更新

- image 会在 `docker-compose restart` 时自动拉取更新，因为指定的 entrypoint 脚本会 pull 仓库更新
  - 这个过程是在 container 内通过 pull 仓库完成的，无需重新 build image

- 除此之外，Yunzai 最新版提供的 `#更新` 和 `#全部更新` 指令也可以在 qq 上实现更新

- 另外旧版的 `yunzai-bot:dev` 在更新插件时会遇到一点小问题，如果后续需要使用插件可以自己 build 镜像
  - 自己 build 的镜像因为指定了 entrypoint ，所以每次重启也会同步更新版本
