### ISSUE TITLE
缺少命令或一些错误

### ISSUE THREAD

**Issue by uyaddayu** [Le-niao/Yunzai-Bot#357]
1、关闭程序指令，每次关闭我得从任务管理器找node进程关闭。
2、配置公用ck，2.x版本有地方配置，3.0版本没找到在哪，config/config文件夹下的每个文件我都看了，没找到。。
3、全部签到不反馈成功或者失败。
4、3.0版本迁移到另外一台机器会丢失部分用户数据，这个不清楚是操作有误的问题还是啥，总之就是数据的迁移不方便不完整，希望出一个导出导入用户数据的功能。
5、miao插件的用户统计功能无效之类的，不过应该不在这里问。。

**Comment by Conard-Ferenc** [comment]
> 2、配置公用ck，2.x版本有地方配置，3.0版本没找到在哪，config/config文件夹下的每个文件我都看了，没找到。。

```bash
cd ./Yunzai-Bot/plugins/genshin/config
vim ./mys.pubCk.yaml
```
在这个文件下编辑 @uyaddayu

**Comment by YunJin77** [comment]
> 1、关闭程序指令，每次关闭我得从任务管理器找node进程关闭。

npm run stop

> 3、全部签到不反馈成功或者失败。

最新版本成功应该是有的，“签到任务完成”，没注意到失败的情况

**Comment by uyaddayu** [comment]
> npm run stop

签到失败后台报无效请求也是这一句，所以说没区分。
成功的话如果可以的话可以来个：5个签到已成功，10个已签到，2个签到失败。
