### ISSUE TITLE
3.0机器人‘’#更新‘’指令不反应啊

### ISSUE THREAD

**Issue by xiaomingwa** [Le-niao/Yunzai-Bot#360]
无法进行更新啊，米游社签到不了，我是手机搭建的有点麻烦了

**Comment by Le-niao** [comment]
手动git pull更新下就有
 `#更新` 5ac06128b0b5cd354ad42c5a1d54416464d8084b 指令两天前加的

**Comment by xiaomingwa** [comment]
> 手动git pull更新下就有 `#更新` [5ac0612](https://github.com/Le-niao/Yunzai-Bot/commit/5ac06128b0b5cd354ad42c5a1d54416464d8084b) 指令两天前加的

敢问如何操作
私聊机器人#更新 5ac0612也没用
手机后台有我的信息但没做出反应

**Comment by xiaomingwa** [comment]
> 手动git pull更新下就有 `#更新` [5ac0612](https://github.com/Le-niao/Yunzai-Bot/commit/5ac06128b0b5cd354ad42c5a1d54416464d8084b) 指令两天前加的

嘿嘿嘿终于弄明白这git pull是啥了，可以了，感谢，祝您生活愉快，大佬nb!

**Comment by HstarHeng** [comment]
> 

为啥QQ上发更新一直连接失败，是网络问题吗

**Comment by HstarHeng** [comment]
> 手动git pull更新下就有 [5ac0612](https://github.com/Le-niao/Yunzai-Bot/commit/5ac06128b0b5cd354ad42c5a1d54416464d8084b) 指令两天前加的`#更新`

为啥QQ上发更新一直连接失败，是网络问题吗

**Comment by xiaomingwa** [comment]
> > 手动git pull更新下就有 [5ac0612](https://github.com/Le-niao/Yunzai-Bot/commit/5ac06128b0b5cd354ad42c5a1d54416464d8084b) 指令两天前加的`#更新`
> 
> 为啥QQ上发更新一直连接失败，是网络问题吗

这我不知道，你可以新建一个issue问问大佬们

**Comment by XiaoGanCN** [comment]
我直接删库重装了(≖_≖ )

**Comment by xiaomingwa** [comment]
> 我直接删库重装了(≖_≖ )

已经可以全部更新了
