### ISSUE TITLE
为啥QQ上发更新一直连接失败，是网络问题吗

### ISSUE THREAD

**Issue by HstarHeng** [Le-niao/Yunzai-Bot#361]
![QQ图片20220805224204](https://user-images.githubusercontent.com/110680739/183103750-0eb91106-285d-4efa-81ea-88aa6034e43c.png)

就是这样

**Comment by uyaddayu** [comment]
根目录执行npm run log，看报错日志

**Comment by Le-niao** [comment]
你自己瞎操作，把git remote改了......

**Comment by HstarHeng** [comment]
> 你自己瞎操作，把git remote改了......

![image](https://user-images.githubusercontent.com/110680739/183235303-0d02d34f-09f3-454c-96e3-9c3deee068a4.png)
