### ISSUE TITLE
3.0.0版本#更新 更新失败

### ISSUE THREAD

**Issue by WNCX** [Le-niao/Yunzai-Bot#362]
`操作失败！`
`Error: Command failed: npm run start`
`Error: EACCES: permission denied, mkdir '/root/.pm2/logs'`
`    at Object.mkdirSync (node:fs:1349:3)`
`    at mkdirpNativeSync (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/lib/mkdirp-native.js:29:10)`
`    at Function.mkdirpSync [as sync] (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/index.js:21:7)`
`    at module.exports.Client.initFileStructure (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:133:25)`
`    at new module.exports (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:38:8)`
`    at new API (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:107:19)`
`    at Object.<anonymous> (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:22:11)`
`    at Module._compile (node:internal/modules/cjs/loader:1105:14)`
`    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`
`    at Module.load (node:internal/modules/cjs/loader:981:32)`
`Error: EACCES: permission denied, mkdir '/root/.pm2/pids'`
`    at Object.mkdirSync (node:fs:1349:3)`
`    at mkdirpNativeSync (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/lib/mkdirp-native.js:29:10)`
`    at Function.mkdirpSync [as sync] (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/index.js:21:7)`
`    at module.exports.Client.initFileStructure (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:141:25)`
`    at new module.exports (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:38:8)`
`    at new API (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:107:19)`
`    at Object.<anonymous> (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:22:11)`
`    at Module._compile (node:internal/modules/cjs/loader:1105:14)`
`    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`
`    at Module.load (node:internal/modules/cjs/loader:981:32)`
`Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'`
`    at Object.openSync (node:fs:585:3)`
`    at Object.writeFileSync (node:fs:2170:35)`
`    at module.exports.Client.initFileStructure (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:149:10)`
`    at new module.exports (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:38:8)`
`    at new API (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:107:19)`
`    at Object.<anonymous> (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:22:11)`
`    at Module._compile (node:internal/modules/cjs/loader:1105:14)`
`    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`
`    at Module.load (node:internal/modules/cjs/loader:981:32)`
`    at Function.Module._load (node:internal/modules/cjs/loader:822:12)`
`Error: EACCES: permission denied, mkdir '/root/.pm2/modules'`
`    at Object.mkdirSync (node:fs:1349:3)`
`    at mkdirpNativeSync (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/lib/mkdirp-native.js:29:10)`
`    at Function.mkdirpSync [as sync] (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/mkdirp@1.0.4/node_modules/mkdirp/index.js:21:7)`
`    at module.exports.Client.initFileStructure (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:157:25)`
`    at new module.exports (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Client.js:38:8)`
`    at new API (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:107:19)`
`    at Object.<anonymous> (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:22:11)`
`    at Module._compile (node:internal/modules/cjs/loader:1105:14)`
`    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`
`    at Module.load (node:internal/modules/cjs/loader:981:32)`
`Error: EACCES: permission denied, open '/root/.pm2/module_conf.json'`
`    at Object.openSync (node:fs:585:3)`
`    at Object.readFileSync (node:fs:453:35)`
`    at Object.Configuration.getAllSync (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Configuration.js:299:26)`
`    at Object.Configuration.getSync (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/Configuration.js:270:30)`
`    at new API (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/API.js:116:44)`
`    at Object.<anonymous> (/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/pm2@5.2.0/node_modules/pm2/lib/binaries/CLI.js:22:11)`
`    at Module._compile (node:internal/modules/cjs/loader:1105:14)`
`    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`
`    at Module.load (node:internal/modules/cjs/loader:981:32)`
`    at Function.Module._load (node:internal/modules/cjs/loader:822:12)`
`/home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/@pm2+agent@2.0.1/node_modules/@pm2/agent/src/InteractorClient.js:58`
`          if (stats.uid === 0) {`
`                    ^`
``
`TypeError: Cannot read properties of undefined (reading 'uid')`
`    at /home/whoncxis/桌面/yunzai-bot/Yunzai-Bot/node_modules/.pnpm/@pm2+agent@2.0.1/node_modules/@pm2/agent/src/InteractorClient.js:58:21`
`    at FSReqCallback.oncomplete (node:fs:198:21)`
``
`    at ChildProcess.exithandler (node:child_process:398:12)`
`    at ChildProcess.emit (node:events:527:28)`
`    at maybeClose (node:internal/child_process:1092:16)`
`    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)`

**Comment by uyaddayu** [comment]
新版本推荐 #全部更新 指令。。
你这是从2.x升级到3.0还是3.0版本的 #更新 指令？
看情况是没权限，也许可以试试给文件夹对应权限或者：npm i --unsafe-perm=true
（

**Comment by Hypocrisy212** [comment]
#更新出现
更新失败！
连接失败：https://github.com/yoimiya-kokomi/Yunzai-Bot/
后台也没有任何提示是为什么？

**Comment by WNCX** [comment]
> 新版本推荐 #全部更新 指令。。 你这是从2.x升级到3.0还是3.0版本的 #更新 指令？ 看情况是没权限，也许可以试试给文件夹对应权限或者：npm i --unsafe-perm=true （

这个是3.0的更新指令，还有为什么你的回复结尾要打括号（
