### ISSUE TITLE
现在是不是还不支持定时自动签到啊

### ISSUE THREAD

**Issue by SkinnyLi** [Le-niao/Yunzai-Bot#363]
我在定时任务那里找到了相关设置，不过好像没有作用

**Comment by uyaddayu** [comment]
![image](https://user-images.githubusercontent.com/40861535/183214290-caeb1b73-e3d3-4fc8-b51c-32b3cafb4460.png)
好像没设置自动帮我签到了

**Comment by Pull256** [comment]
之前签到是会发送消息提示的，现在没有了。自动签到倒是正常运行的

**Comment by SkinnyLi** [comment]
> ![image](https://user-images.githubusercontent.com/40861535/183214290-caeb1b73-e3d3-4fc8-b51c-32b3cafb4460.png) 好像没设置自动帮我签到了

我把plugins/genshin/defSet里的cron表达式改成了0点0分0秒，然后没起作用，手动#签到完成的。今天试试0分1秒会不会生效。

**Comment by Le-niao** [comment]
不是修改`defSet`默认设置，请修改`config/mys.set.yaml`，定时任务修改需要重启
