### ISSUE TITLE
无法查询武器

### ISSUE THREAD

**Issue by xiaomingwa** [Le-niao/Yunzai-Bot#364]
![image](https://user-images.githubusercontent.com/74846916/183228693-a01dbbc8-930b-4784-ba67-936219ad7e6e.png)
就像这样，其他功能暂时没发现什么问题

**Comment by xiaomingwa** [comment]
发送#雾切等武器命令后台接收但不做任何反应

**Comment by ctrlcvs** [comment]
有没有可能V3本身目前就没这个功能？

**Comment by xiaomingwa** [comment]
> 有没有可能V3本身目前就没这个功能？

?

**Comment by Ponysesame** [comment]
> 

图鉴功能是逍遥插件的功能，需要自行安装。
