### ISSUE TITLE
插件的request请求能使用代理吗？

### ISSUE THREAD

**Issue by uyaddayu** [Le-niao/Yunzai-Bot#366]
![image](https://user-images.githubusercontent.com/40861535/183236414-c74ae8c6-d383-46a4-bd17-50e07bb47312.png)
发生了一个这样的错误，请求不到。。
我只有代理没有vpn。
我直接浏览器请求这个json是可以成功的，插件没用上代理就没成功。

**Comment by Le-niao** [comment]
miao-plugin已加代理

**Comment by uyaddayu** [comment]
> miao-plugin已加代理

可以了，就是得安装一个https-proxy-agent
