### ISSUE TITLE
十连命令Yunzai发送图片后自动撤回

### ISSUE THREAD

**Issue by YsKiKi** [Le-niao/Yunzai-Bot#367]

**Comment by Le-niao** [comment]
建议撤回，避免刷屏，还有最重要的是，防止腾讯的诈骗冻结

**Comment by YsKiKi** [comment]
能不能把撤回的时间延长一下，很多时候群员都来不及看图片就撤回了

**Comment by YsKiKi** [comment]
还有就是刚刚用质感文件找了半天没找到抽卡次数在哪里更改

**Comment by Le-niao** [comment]
`plugins/genshin/config/gacha.set.yaml`
