### ISSUE TITLE
米游社签到invalid request 

### ISSUE THREAD

**Issue by daheiguai** [Le-niao/Yunzai-Bot#374]
关于8月5日修复的米游社签到invalid request  ，在8月7日#更新、重启服务器后依旧存在，手动git pull也显示已是最新（2.1.8）

**Comment by liuly0322** [comment]
本仓库的 v2.x 版本已不再维护

可以考虑切换 [yoimiya-kokomi](https://github.com/yoimiya-kokomi) 维护的 v2.x 第三方版本 <https://github.com/yoimiya-kokomi/miao-plugin#v2-yunzai> 或者切换到 main 分支更新至本仓库 v3.x 版本，数据迁移参考 https://github.com/Le-niao/Yunzai-Bot/issues/327
