### ISSUE TITLE
更新报错

### ISSUE THREAD

**Issue by magic5al** [Le-niao/Yunzai-Bot#375]
![YXM_SW477O%~B2A3@%L26K1](https://user-images.githubusercontent.com/91271243/183278269-d7a51067-4f86-4beb-bd60-19ec03698791.jpg)
最近看到好几个这种问题，但我自身没有遇到，看起来应该是分支问题，但git branch就在main上，拉代码应该也拉的main上的更改，那这个出错是为什么呢
有些用`git pull `git pull https://gitee.com/Le-niao/Yunzai-Bot.git`可以解决这个问题

**Comment by Le-niao** [comment]
git fetch all

**Comment by magic5al** [comment]
找到问题所在了

报错贴一下好让后面的人搜
> Error: Command failed: git pull --no-rebase
> fatal: couldn't find remote ref refs/heads/main

解决方法：
`git remote set-url origin https://github.com/Le-niao/Yunzai-Bot.git`

原因嘛，没看清喵喵插件readme中所说就直接运行了上面的代码 导致远端仓库被改到喵佬那了
