### ISSUE TITLE
node app之后出现错误

### ISSUE THREAD

**Issue by Michael-Rin** [Le-niao/Yunzai-Bot#378]
手机termux安装，B站动态上的一键安装脚本无法使用，就用了Issues#154的方法，但是运行出现问题
root@localhost:~/Yunzai-Bot# node app
node: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
<img width="703" alt="image" src="https://user-images.githubusercontent.com/58716629/183296518-d863f3cd-0fb4-4924-b7d7-ce8597282936.png">
该怎么解决

**Comment by xiao909** [comment]
curl -sL http://mtw.so/68HBVw | bash

**Comment by Le-niao** [comment]
教程已过期
