### ISSUE TITLE
原神签到失败，验证码失败

### ISSUE THREAD

**Issue by uyaddayu** [Le-niao/Yunzai-Bot#380]
![image](https://user-images.githubusercontent.com/40861535/183313794-b821168e-fc49-4dee-adbe-7ada9667a902.png)
去米游社看了下还没签到，上游戏看了下还是没邮件

**Comment by uyaddayu** [comment]
看了下，是只有我的大号没有被签到到。。。小号正常，大小号共用一个ck，把我签漏了应该，无法强制重新签到，只能我手动签到一次了。。

**Comment by ChthollyWn** [comment]
> 看了下，是只有我的大号没有被签到到。。。小号正常，大小号共用一个ck，把我签漏了应该，无法强制重新签到，只能我手动签到一次了。。

我今天也遇到了这个问题，只有我的账号漏签了，你解决了吗

**Comment by uyaddayu** [comment]
> > 看了下，是只有我的大号没有被签到到。。。小号正常，大小号共用一个ck，把我签漏了应该，无法强制重新签到，只能我手动签到一次了。。
> 
> 我今天也遇到了这个问题，只有我的账号漏签了，你解决了吗

上米有社手动签到去了hh

**Comment by ChthollyWn** [comment]
> > > 看了下，是只有我的大号没有被签到到。。。小号正常，大小号共用一个ck，把我签漏了应该，无法强制重新签到，只能我手动签到一次了。。
> > 
> > 
> > 我今天也遇到了这个问题，只有我的账号漏签了，你解决了吗
> 
> 上米有社手动签到去了hh

哈哈哈哈，我重新用命令签到了一下，还是没有反应，也去米游社手签了

**Comment by daheiguai** [comment]
我已经4个号连续2天，完全签不上，一直显示签到成功

**Comment by Wang-Jingrun** [comment]
我也是，显示签到成功，但是游戏里没收到签到奖励邮件

**Comment by SSRNova** [comment]
这个好像是cookie失效的问题吧，不知道有没有好办法

**Comment by ChthollyWn** [comment]
> 这个好像是cookie失效的问题吧，不知道有没有好办法

只是不能签到，可以查询米游社信息，应该不是cookie失效

**Comment by SSRNova** [comment]
那你绑定了cookie后，网页那退出登入，cookie还有用吗

**Comment by ChthollyWn** [comment]
> 那你绑定了cookie后，网页那退出登入，cookie还有用吗

退出后cookie肯定没用了啊

**Comment by zhxycn** [comment]
因为米游社近期加入了人机验证的滑动验证码，所以会导致签到失败，是否为cookie失效可以尝试查询账号的详细信息，如果能正常获取说明cookie正常。
另：验证码和ip有关联，可尝试通过更换服务器ip解决。

**Comment by uyaddayu** [comment]
> 因为米游社近期加入了人机验证的滑动验证码，所以会导致签到失败，是否为cookie失效可以尝试查询账号的详细信息，如果能正常获取说明cookie正常。 另：验证码和ip有关联，可尝试通过更换服务器ip解决。 ![image](https://user-images.githubusercontent.com/99539499/184310801-56085f5e-5cdf-471f-aa36-e6ade8333e54.png)
破案了，那这个确实不好搞

**Comment by 1011382654** [comment]
> 

如果是ip问题应该全部签到失败，如果是验证问题有人反馈手签没有出现滑块验证。疑惑！

**Comment by uyaddayu** [comment]
> > 
> 
> 如果是ip问题应该全部签到失败，如果是验证问题有人反馈手签没有出现滑块验证。疑惑！

我今天是官服签到成功，b服签到失败

**Comment by daheiguai** [comment]
我现在一天成功，一天失败，同一个号

**Comment by zhxycn** [comment]
本人更换ip后签到正常，暂不确定是ip风控还是账号风控问题导致，但出现验证码确实是导致此问题的原因。

**Comment by ChthollyWn** [comment]
> 本人更换ip后签到正常，暂不确定是ip风控还是账号风控问题导致，但出现验证码确实是导致此问题的原因。

已经更换过一次ip了，现在不能更换了，只能等大佬们解决了（笑哭）

**Comment by zhxycn** [comment]
除非有一个新的不需要验证码的接口，不然验证码这东西基本无解  
mhy好像用的是极验的验证码

**Comment by 1011382654** [comment]
除非挂本地不然换IP不是解决办法，这么高频的签到一下就监测出来了

**Comment by uyaddayu** [comment]
![image](https://user-images.githubusercontent.com/40861535/185249671-592ee340-01c1-4947-98fa-6d6018be8480.png)
能否增加隔随机时间重试的方法，我这里手动全部签到又成功了几次。
这个重试设置个10次的机会这样子？

**Comment by uyaddayu** [comment]
![image](https://user-images.githubusercontent.com/40861535/185249925-2d326958-26b2-4632-90b5-ee7f8309efc3.png)
我这11个ck的情况，3次全部签到机会就可以全都签到成功了。

**Comment by ywstratus** [comment]
![IMG_8065](https://user-images.githubusercontent.com/40598605/185665880-eced5c95-4fd8-4d55-a4e7-0a1586052700.jpeg)
同样的问题，签五个五个全噶了，我觉得可以考虑加入间隔签到功能

**Comment by Ponysesame** [comment]
很有可能是因为太多人在00:02这个时间点附近同时签到导致米游社服务器访问量过大触发了验证码保护机制，将自动签到改为3点，4点这样的时间段似乎可以解决。

**Comment by uyaddayu** [comment]
> 很有可能是因为太多人在00:02这个时间点附近同时签到导致米游社服务器访问量过大触发了验证码保护机制，将自动签到改为3点，4点这样的时间段似乎可以解决。



> 很有可能是因为太多人在00:02这个时间点附近同时签到导致米游社服务器访问量过大触发了验证码保护机制，将自动签到改为3点，4点这样的时间段似乎可以解决。

并不是，我早上手动签到都会失败，就是需要一个失败就隔段时间重新签到的机制

**Comment by uyaddayu** [comment]
今天更新完一次成功了，次数不知道在哪设置，希望重试次数多一些
