### ISSUE TITLE
一直连接失败是怎么回事，是我的网络有问题吗

### ISSUE THREAD

**Issue by Guodiancheng** [Le-niao/Yunzai-Bot#382]
1|Yunzai-B | [YzBot][09:59:58.008][MARK] 120.232.67.190:8080 closed
1|Yunzai-B | [YzBot][09:59:58.068][MARK] 106.53.142.76:8080 connected
1|Yunzai-B | [YzBot][10:00:10.008][MARK] 106.53.142.76:8080 closed
1|Yunzai-B | [YzBot][10:00:10.067][MARK] 106.55.209.162:443 connected
1|Yunzai-B | [YzBot][10:00:19.006][MARK] 106.55.209.162:443 closed
1|Yunzai-B | [YzBot][10:00:19.067][MARK] 106.55.209.162:443 connected
1|Yunzai-B | [YzBot][10:00:28.007][MARK] 106.55.209.162:443 closed
1|Yunzai-B | [YzBot][10:00:28.068][MARK] 106.55.209.162:443 connected
1|Yunzai-B | [YzBot][10:00:37.009][MARK] 106.55.209.162:443 closed
1|Yunzai-B | [YzBot][10:00:37.069][MARK] 106.55.209.162:443 connected
1|Yunzai-B | [YzBot][10:00:46.006][MARK] 106.55.209.162:443 closed
1|Yunzai-B | [YzBot][10:00:46.066][MARK] 106.55.209.162:443 connected

**Comment by SkinAir** [comment]
考古没找到原因.
