### ISSUE TITLE
“今日素材”   查询功能   希望在天赋栏下的角色窗口除了等级以外加个天赋等级小框

### ISSUE THREAD

**Issue by 7assassin7** [Le-niao/Yunzai-Bot#384]
![)P3K Z6FFHK4YEIZNABM_74](https://user-images.githubusercontent.com/57352654/183326617-b8a25c06-1504-4901-9425-16f7cc46e46e.png)

**Comment by RockRadix** [comment]
查询技能等级需要绑定米游社cookie

**Comment by lgyseven** [comment]
这个可以有，
