### ISSUE TITLE
puppeteer启动失败，提示缺少依赖，安装仍然有问题

### ISSUE THREAD

**Issue by Herzlos277** [Le-niao/Yunzai-Bot#385]
服务器是腾讯云，centos7.6
使用node app命令启动bot后输入命令，提示puppeteer缺少如下图依赖
![image](https://user-images.githubusercontent.com/57382392/183335091-0c5bf336-aa89-434c-8f09-847d94560773.png)
使用yum install 【复制依赖名称】命令后仍然提示缺少依赖
后根据stackoverflow提示安装yum -y install libxkbcommon-x11
再次启动后不再报错，可以使用，但是所有生成的图片中的中文都是乱码，至此希望能够帮助给出解决方案
![image](https://user-images.githubusercontent.com/57382392/183335349-904e934c-a8a6-4aad-a390-7138fa49e00f.png)

**Comment by Qujixiang** [comment]
yum groupinstall fonts -y

**Comment by Qujixiang** [comment]
```bash
yum groupinstall fonts -y
```
