### ISSUE TITLE
如何禁用十连功能配置呢

### ISSUE THREAD

**Issue by 200780381** [Le-niao/Yunzai-Bot#387]
如何关闭十连这一个功能呢？

**Comment by liuly0322** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/301#issuecomment-1200331958

**Comment by 200780381** [comment]
可是改了错误

**Comment by Le-niao** [comment]
`/config/config/group.yaml` `disable` 横杆空格一行一个
