### ISSUE TITLE
#角色 米游社接口访问失败，暂时无法查询；私聊发送cookie没反应

### ISSUE THREAD

**Issue by zcxbz** [Le-niao/Yunzai-Bot#390]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/96189144/183419474-a874637e-d7e6-4995-a9fc-66cfa27cb3c1.png">

**Comment by Le-niao** [comment]
米游社接口问题，请确认能正常访问米游社

**Comment by zcxbz** [comment]
ping bbs.mihoyo.com 可以ping通算是能正常访问吗
