### ISSUE TITLE
V3云崽和V2（Yoimiya-Kokomi维护版）共存问题

### ISSUE THREAD

**Issue by ITManCHINA** [Le-niao/Yunzai-Bot#393]
![feedback image](https://s2.loli.net/2022/08/09/PJtsOEMvmHjpxWl.png)
V3版本和V2版本（Yoimiya-Kokomi维护的版本）在同一个群里，接收到 “#帮助” 的命令时显示命令执行失败并且是一堆数字，但是V2版本正常运行，求解答

**Comment by Le-niao** [comment]
更新

**Comment by ITManCHINA** [comment]
V3.0版本更新命令没有反应，是需要用git pull强制拉取嘛

**Comment by Le-niao** [comment]
更新命令后面加的，没有的要先手动git pull更新

**Comment by ITManCHINA** [comment]
明白了，感谢大大
