### ISSUE TITLE
2.18 #签到 invalid request

### ISSUE THREAD

**Issue by xiaofeicn** [Le-niao/Yunzai-Bot#394]
版本 2.18
错误命令 #签到
可使用cookie相关命令：#体力，#我的xxx面板，#我的ck，#原石
![image](https://user-images.githubusercontent.com/27882640/183548147-87d875ad-8ad0-44c6-852e-9be5c5977f7e.png)
手动签到后发送命令 #签到
![image](https://user-images.githubusercontent.com/27882640/183548198-0ea37fdc-646d-4993-ba4a-b96c97f0a38e.png)
麻烦帮忙看看，感谢

**Comment by Le-niao** [comment]
更新

**Comment by xiaofeicn** [comment]
已重复更新重启多次，我再试试

**Comment by xiaofeicn** [comment]
![image](https://user-images.githubusercontent.com/27882640/183548754-c1bbdebe-ac9b-4089-91ce-cbb02265cd4a.png)
更新后#签到
![image](https://user-images.githubusercontent.com/27882640/183548812-b8a358a6-454f-4da8-8d36-e3ffba505ecd.png)

**Comment by ITManCHINA** [comment]
命令行在Yunzai-Bot目录下使用如下命令
`git remote set-url origin https://gitee.com/yoimiya-kokomi/Yunzai-Bot`
然后再尝试更新

**Comment by ITManCHINA** [comment]
> 命令行在Yunzai-Bot目录下使用如下命令 `git remote set-url origin https://gitee.com/yoimiya-kokomi/Yunzai-Bot` 然后再尝试更新

这个方法适用于升级V2版本的机器人，更新V3的话建议先备份V2绑定的个人Cookie和公用Cookie再升级

**Comment by xiaofeicn** [comment]
好的，我试试，谢谢

**Comment by xiaofeicn** [comment]
失败！
Error code: 1
Error: Command failed: git pull
From https://gitee.com/yoimiya-kokomi/yunzai-bot
   b9a5a18..97d0e37  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
	config/genshin/roleId.js
Please commit your changes or stash them before you merge.
Aborting

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

本地代码与远程代码存在冲突,上面报错信息中包含冲突文件名称及路径，请尝试处理冲突
如果不想保存本地修改请使用【#强制更新】
(注意：强制更新命令会忽略所有本地对Yunzai-Bot本身文件的修改，本地修改均不会保存，请注意备份，lib/example不影响)

**Comment by xiaofeicn** [comment]
已强制更新，但还是错误
执行了插件  #喵喵更新 后签到正常
感谢帮助

**Comment by ITManCHINA** [comment]
备份好Cookie再更新应该就没问题了吧
