### ISSUE TITLE
进群里不发送消息怎么弄

### ISSUE THREAD

**Issue by SSRNova** [Le-niao/Yunzai-Bot#397]
![image](https://user-images.githubusercontent.com/110885173/183573613-df3db42f-3444-4d71-a966-5fbdd1d33a7d.png)

**Comment by SSRNova** [comment]
这个报错了私聊也不能发了

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/267#issuecomment-1196203656
