### ISSUE TITLE
大佬是否能出一个能调用观测枢地图，查素材如绝云辣椒这种的功能

### ISSUE THREAD

**Issue by davidelectricfree** [Le-niao/Yunzai-Bot#40]
https://github.com/H-K-Y/Genshin_Impact_bot

类似这个项目的查素材在哪的功能，但是这个项目已经不更新了，所有非主地图的均无法查询

谢谢大佬啊

**Comment by Le-niao** [comment]
这个太麻烦了，还是直接用米游社的工具查吧

**Comment by davidelectricfree** [comment]
> 这个太麻烦了，还是直接用米游社的工具查吧

额，好吧，谢谢
