### ISSUE TITLE
请问在哪里可以取消主人专属这个权限呢

### ISSUE THREAD

**Issue by dingzhenbaohujiaran** [Le-niao/Yunzai-Bot#400]
例如，#原石任务  这个指令，其他小伙伴使用的时候，机器人会提示只有主人才有权限，也就是只有我一个人可以使用，我想把这个权限取消掉，让大伙都能使用

**Comment by HAHH9527** [comment]
***本人非开发者，修改前请做好备份***
***本人非开发者，修改前请做好备份***
***本人非开发者，修改前请做好备份***

翻了下源码，做以下修改应该可以达到你的目的

`plugins/genshin/apps/ledger.js`
22行至26行
```js
        {
          reg: '^#原石任务$',
          permission: 'master',
          fnc: 'ledgerTask'
        },
```
改为
```js
        {
          reg: '^#原石任务$',
          fnc: 'ledgerTask'
        },
```
