### ISSUE TITLE
关于 code:46 的问题

### ISSUE THREAD

**Issue by ITManCHINA** [Le-niao/Yunzai-Bot#401]
经测试发现，log里显示这个情况大概率是被腾讯风控了
![1](https://s2.loli.net/2022/08/09/chskDZiGQgMaFCt.png)
![2](https://s2.loli.net/2022/08/09/nWtEOMKw5LBJxPy.jpg)

**Comment by ITManCHINA** [comment]
点击P2中的去处理即可（建议机器人iPad登录时用另一台真机挂着QQ，非风控的概率会小一点）

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/267#issuecomment-1196203656
