### ISSUE TITLE
云崽3.0更新面板失败

### ISSUE THREAD

**Issue by 1150260034** [Le-niao/Yunzai-Bot#403]
![image](https://user-images.githubusercontent.com/66198188/183621053-a49af63a-e77d-45a4-993f-7986741fb327.png)
日志如图所示
操作系统：Ubuntu20
版本：云崽v3.0.0
nodejs版本：v16.16.0

尝试过重启，但是没用
根据百度报错来看，推测是米游社接口未返回json类型的数据，导致解析出错

**Comment by Le-niao** [comment]
https://github.com/yoimiya-kokomi/miao-plugin/issues/63#issue-1299812134
