### ISSUE TITLE
请问重启的时候报错该如何解决谢谢

### ISSUE THREAD

**Issue by woshidxx** [Le-niao/Yunzai-Bot#405]
重启提示:
Error: Command failed: npm run start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.后面还有一大段

**Comment by liuly0322** [comment]
搜索引擎搜索 npm WARN config global --global, --local are deprecated 可能会解决问题

这个应该是本地的 node.js 版本问题，如果无法解决可以提供下 node.js 和 npm 的版本（node -v 和 npm -v）
