### ISSUE TITLE
机器人群聊中发送消息报错，但私聊没问题

### ISSUE THREAD

**Issue by tangling001** [Le-niao/Yunzai-Bot#406]
[YzBot][10:37:56.371][ERRO] failed to send: [Group: 726524364] undefined(46)
[YzBot][10:37:56.371][ERRO] 发送消息错误:{"type":"image","file":{}}
[YzBot][10:37:56.372][ERRO] ApiRejection { code: 46, message: 'unknown' }

以上为报错内容

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/267#issuecomment-1196203656
