### ISSUE TITLE
请问导入xlsx的内容需要是什么格式的

### ISSUE THREAD

**Issue by Shiyue00** [Le-niao/Yunzai-Bot#407]
![image](https://user-images.githubusercontent.com/94933592/183807217-6aedcc91-dfc5-4ba6-9afb-13a3de365e0e.png)
发送非小酋导出的这种xlsx会报错：“xlsx文件内容错误：非统一祈愿记录标准”

**Comment by Le-niao** [comment]
[统一可交换祈愿记录标准 v 2.2](https://github.com/DGP-Studio/Snap.Genshin/wiki/StandardFormat#%E7%BB%9F%E4%B8%80%E5%8F%AF%E4%BA%A4%E6%8D%A2%E7%A5%88%E6%84%BF%E8%AE%B0%E5%BD%95%E6%A0%87%E5%87%86-v-22)

**Comment by Shiyue00** [comment]
> [统一可交换祈愿记录标准 v 2.2](https://github.com/DGP-Studio/Snap.Genshin/wiki/StandardFormat#%E7%BB%9F%E4%B8%80%E5%8F%AF%E4%BA%A4%E6%8D%A2%E7%A5%88%E6%84%BF%E8%AE%B0%E5%BD%95%E6%A0%87%E5%87%86-v-22)

感谢大佬~
