### ISSUE TITLE
AidLux搭建寻求帮助

### ISSUE THREAD

**Issue by Tigarcen** [Le-niao/Yunzai-Bot#408]
正在探索使用AidLux搭建，想寻求一些帮助，我对于Linux熟悉度并不高

本来开始是按照教程使用termux的，但奈何发现那部手机的根目录所在空间太小
就找到了AidLux

termux教程使用的环境是Ubuntu，而AidLux的环境貌似是Debian
apt install chromium-browser
这个命令是用不了的，好像是提示的不存在这个包
所以使用的是：
apt-get install chromium -y

启动云崽后，提示chromium安装不正确
根据提示使用了
node ./node-modules/puppeteer/install.js
在重新启动云崽后依旧提示chromium安装不正确

故寻求帮助，劳敬尊上

**Comment by Le-niao** [comment]
不是派蒙

**Comment by Tigarcen** [comment]
> 不是派蒙

啊哈哈，QQ名打习惯了，抱歉，我改成云崽

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/0384ac2c861a547c41a08b1ad811850547c2f719/config/default_config/bot.yaml#L13

可以尝试在这里填你安装的chromium路径

**Comment by Tigarcen** [comment]
> https://github.com/Le-niao/Yunzai-Bot/blob/0384ac2c861a547c41a08b1ad811850547c2f719/config/default_config/bot.yaml#L13
> 
> 可以尝试在这里填你安装的chromium路径

多谢，这就尝试
