### ISSUE TITLE
ffmpeg的路径问题

### ISSUE THREAD

**Issue by XiTianGame** [Le-niao/Yunzai-Bot#409]
如果在bot.yaml里填写的ffmpeg路径包含空格（如Program Files）会导致不认路径

**Comment by liuly0322** [comment]
字符串有空格需要整体加引号，这个应该是 yaml 的格式要求

**Comment by XiTianGame** [comment]
试过了，但不起效，单双引号都已经尝试过，已经自行迁移到其他文件夹了
