### ISSUE TITLE
没有找到设置抽卡次数哇

### ISSUE THREAD

**Issue by Nu1L-404** [Le-niao/Yunzai-Bot#413]
![image](https://user-images.githubusercontent.com/95953449/183900740-e7ba15bf-93a0-4e3f-8ede-cbe402d5ee12.png)

**Comment by liuly0322** [comment]
https://github.com/Le-niao/Yunzai-Bot/blob/0384ac2c861a547c41a08b1ad811850547c2f719/plugins/genshin/defSet/gacha/set.yaml#L4

**Comment by liuly0322** [comment]
建议修改 `plugins/genshin/config/gacha.set.yaml`，上面的是默认配置文件，这个是建议自定义设置的位置
修改后重启即可
