### ISSUE TITLE
机器人显示“自动签到已开启”，但是并没有自动签到

### ISSUE THREAD

**Issue by hchen1134** [Le-niao/Yunzai-Bot#423]
![image](https://user-images.githubusercontent.com/28447051/184058307-1c676c4a-081d-45af-ae7b-72af365ee16c.png)
上次自动签到更新以后有人出现了无法自动签到的问题，无论是重新绑定cookie还是重登米游社都没有用

**Comment by Le-niao** [comment]
别发ck出来
