### ISSUE TITLE
再来提个建议，云崽作者 新建一个插件仓库，仓库里存放来自各方开发者pr的单独的js插件，这样云崽用户不至于到处去找小插件

### ISSUE THREAD

**Issue by xianxincoder** [Le-niao/Yunzai-Bot#427]
再来提个建议，建议云崽作者 新建一个插件仓库，仓库可以来自各方开发者写的单独的js插件，这样云崽用户不至于到处去找小插件。
目前小插件太凌乱了，也分不清到底是哪位开发者写的小插件，后续问题也找不到人。这样在插件库里谁写的谁负责。不过插件库可能也会比较乱，毕竟参与者会很多，不过都是单独的js互相也不会有什么影响。

**Comment by ctrlcvs** [comment]
首先我作为plugin开发者以及部分插件的开发者表达一下观点，开放仓库供用户拉取是没有问题的，但是信息差会导致出现说有些小人占这个便宜去倒卖之类的，而且另外一个问题就是插件作者自愿上传的情况，相对而言你应该也知道主群的插件很多都是不授权禁止转载的，但是还是一样的有很多插件是被转载到各种群的甚至有些转载的人说自己是插件作者的。
所以我个人是不希望开放插件仓库的

**Comment by chenshi1324** [comment]
小人过于嚣张，群众里面有坏人

**Comment by xianxincoder** [comment]
嗯 建议 讨论讨论挺好的，确实很多情况，倒卖，胡乱的转载，篡改代码改出来bug然后在跑去问作者有bug怎么改之类的这种。但是我感觉 防是防不住的，既然大家做开源，感觉还是要在意一下使用开源插件的用户感受。如果机器人发展的更好，更多的人知道咱们云崽是开源的项目，是不是倒卖的情况也会好一些。

**Comment by liuly0322** [comment]
https://github.com/HiArcadia/Yunzai-Bot-plugins-index

插件索引是有用的，作者如果想开源一般都会上传到 github 吧

我个人想法是可以云崽在 readme 加一些相关项目的链接，比如这个插件索引和 [一个使用文档](https://github.com/Xm798/Yunzai-Bot-Docs)，方便有需求的用户寻找，具体内容交给社区维护就可以了

**Comment by 200780381** [comment]
确实
