### ISSUE TITLE
git pull报错

### ISSUE THREAD

**Issue by guobaisanxiu** [Le-niao/Yunzai-Bot#433]
有什么简单的解决方法吗
Error: Command failed: git pull --no-rebase
Your configuration specifies to merge with the ref 'refs/heads/main'
from the remote, but no such ref was fetched.

**Comment by Le-niao** [comment]
自己改了yuan

**Comment by guobaisanxiu** [comment]
> 自己乱改了源

啊这，看了一下，不知道为什么变成猫佬那边的了，改了改了
