### ISSUE TITLE
一个签到成功一个签到失败是怎么回事

### ISSUE THREAD

**Issue by SkinnyLi** [Le-niao/Yunzai-Bot#439]
![image](https://user-images.githubusercontent.com/97529315/184501842-cb8b927f-f939-4a44-aa8c-1a4b7c592702.png)

**Comment by SkinnyLi** [comment]
termux里显示验证码失败

**Comment by SkinnyLi** [comment]
多签了几次成功了。。。不然设置一个签到失败就针对失败uid重新尝试10次的功能？（手动滑稽）

**Comment by Nijing153** [comment]
我这边也是一直有验证码失败，其他功能都能用。是啥问题呀。签了四五次都是失败的

**Comment by Le-niao** [comment]
字面意思
