### ISSUE TITLE
希望能做高并发，以及主人功能似乎失效了。

### ISSUE THREAD

**Issue by slideslide** [Le-niao/Yunzai-Bot#44]
希望能做高并发，以及主人功能似乎失效了。

**Comment by Le-niao** [comment]
配置可以设置cd，群默认cd间隔 500ms，个人cd间隔 1000ms
防止刷屏还有机器人对刷

**Comment by slideslide** [comment]
噢，谢谢，可是主人QQ十连等方面依旧受次数限制，我配置的是正确的QQ号没错欸？

**Comment by Le-niao** [comment]
十连主人不受限制加回去
