### ISSUE TITLE
请问3.0想修改bot的设置应该在修改哪个文件...

### ISSUE THREAD

**Issue by q35654046** [Le-niao/Yunzai-Bot#451]
萌新把整个目录都翻遍了 没有找到像2.2中的配置文件.求求大佬了.帮帮萌新把Y_Y

**Comment by liuly0322** [comment]
`config/config/` 下的所有文件

`plugins/genshin/config/` 下的所有文件

**Comment by q35654046** [comment]
感谢大佬
