### ISSUE TITLE
Cannot find package "oicq"

### ISSUE THREAD

**Issue by XiaoGanCN** [Le-niao/Yunzai-Bot#454]
![Screenshot_20220816_093811](https://user-images.githubusercontent.com/76635216/184780478-18849f30-98d9-4217-8276-36b7779739b9.jpg)

**Comment by Lo1iame** [comment]
检查下喵喵是否拉取到plugins目录下，以及报错提示缺少依赖，重新`cnpm install`一下试试

**Comment by Le-niao** [comment]
pnpm install -P
