### ISSUE TITLE
自动签到现在没有消息提示了吗？之前的AI聊天还会加回来吗？

### ISSUE THREAD

**Issue by wu5288540** [Le-niao/Yunzai-Bot#457]
自动签到现在没有消息提示了吗？之前的AI聊天斗图功能还会加回来吗？

**Comment by wu5288540** [comment]
刚刚翻了下配置文件，在model/mysSign.js的170、189行发现了语法校正工具自动标记的红叉叉，user.js里面的50、53、118行也发现了，麻烦作者大大看一看有什么影响

**Comment by Le-niao** [comment]
不影响
