### ISSUE TITLE
自动签到不成功 手动签到时候提示【签到失败：验证码失败】

### ISSUE THREAD

**Issue by tsrr** [Le-niao/Yunzai-Bot#461]
![image](https://user-images.githubusercontent.com/44045407/185016477-57a3c395-db11-4bf7-86d4-0835a52b21e3.png)
![image](https://user-images.githubusercontent.com/44045407/185016509-a1f3edb5-367e-4f24-bf5a-9284e1fd8f85.png)
请问下这种情况怎么处理，麻烦告知下谢谢  
邮箱：ljcqyx@qq.com

**Comment by Le-niao** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/380#issuecomment-1212836186

**Comment by tsrr** [comment]
好的 感谢看到了
