### ISSUE TITLE
关于戳一戳回复消息

### ISSUE THREAD

**Issue by ctrlcvs** [Le-niao/Yunzai-Bot#464]
V2版本戳一戳是封装成#poke#触发的，V3是否可以封装成#poke#触发

**Comment by liuly0322** [comment]
看起来这个功能自行写成插件会更合理一点（V3的模型只负责监听）

下面是一个示例：

```js
import plugin from '../../lib/plugins/plugin.js'
import fetch from 'node-fetch'

export class hitikoto extends plugin {
  constructor (e) {
    super({
      name: 'hitokoto',
      dsc: '戳一戳触发一言',
      event: 'notice.friend.poke',
      priority: 5000
    })
    // 要同时处理私聊戳一戳和群聊戳一戳
    // 二者对应的 event 并不相同
    // 如果想写在一个插件内需要这样 hook
    if (e && e.post_type === 'notice' &&
      e.notice_type === 'group' &&
      e.sub_type === 'poke') {
      this.event = 'notice.group.poke'
    }
  }

  // 接收到戳一戳会触发这个函数
  async accept () {
    let url = 'https://v1.hitokoto.cn/'
    let res = await fetch(url).catch((err) => logger.error(err))

    if (!res) {
      await this.reply('一言接口请求失败...')
    } else {
      res = await res.json()
      await this.reply(`「${res.from}」：${res.hitokoto}`)
    }
    
    // 阻止信息传递，处理完成
    return 'return'
  }
}

```

**Comment by ctrlcvs** [comment]
> 

额，我跟喵佬的plugin都写一个这种插件支持的话有点麻烦，所以希望乐神这边写出方法支持，而且主题要是有方法支持后续其他的plugin也可以自定义自己的戳一戳事件

**Comment by liuly0322** [comment]
> 额，我跟喵佬的plugin都写一个这种插件支持的话有点麻烦，所以希望乐神这边写出方法支持，而且主体要是有方法支持后续其他的plugin也可以自定义自己的戳一戳事件

在 adapter/index.js 中 accept(e) 内加一个判断即可，如果 e.sub_type === 'poke' 就自行修改 e.msg = '#poke#' 并调用 dispatch(e)，并不需要单独写一个插件

这是 v2 到 v3 的兼容性问题，因此可能更适合修改 adapter，原生 v3 插件（如本仓库 plugins/genshin）每个 app 单独定义具体触发条件并不存在这个问题

**Comment by liuly0322** [comment]
> 额，我跟喵佬的plugin都写一个这种插件支持的话有点麻烦，所以希望乐神这边写出方法支持，而且主体要是有方法支持后续其他的plugin也可以自定义自己的戳一戳事件

在 adapter/index.js 中构造函数内加一个判断即可，如果 e && e.sub_type === 'poke' 就自行修改 e.msg = '#poke#' 并调用 dispatch(e)，并不需要单独写一个插件

这是 v2 到 v3 的兼容性问题，因此可能更适合修改 adapter，原生 v3 插件（如本仓库 plugins/genshin）每个 app 单独定义具体触发 event 并不存在这个问题
