### ISSUE TITLE
这次更新有文件冲突

### ISSUE THREAD

**Issue by likodesu** [Le-niao/Yunzai-Bot#465]
更新失败！存在冲突：
Error: Command failed: git pull --no-rebase
error: Your local changes to the following files would be overwritten by merge:
	package.json
Please commit your changes or stash them before you merge.
Aborting

请解决冲突后再更新，或者执行#强制更新，放弃本地修改
这个是什么原因引起的啊

**Comment by bling-yshs** [comment]
`#强制更新`

**Comment by QyInvoLing** [comment]
强制更新完了之后莫名其妙启动了两个yunzai。。。一直顶对方下线，主人设置失效

**Comment by bling-yshs** [comment]
> 强制更新完了之后莫名其妙启动了两个yunzai。。。一直顶对方下线，主人设置失效

重启电脑就行了

**Comment by QyInvoLing** [comment]
两个bot解决了，主人设置失效的问题依然没有解决
新版本的主人设置不在./config/config/other.yaml?
