### ISSUE TITLE
无法重启&npm run start

### ISSUE THREAD

**Issue by 70loKirin** [Le-niao/Yunzai-Bot#467]

**Comment by 70loKirin** [comment]
发重启之后一直无反应直到再次node app机器人就回复“重启成功”（下图
![4HY7FJPDTVA1XEC07@TTA9P](https://user-images.githubusercontent.com/91271243/185184173-3036706f-bad1-4b1f-8a11-dd3a4c8eeef4.png)
）

当我试着`npm run start`，出现如下error，机器人并没有上线
![3M`0LIM _1@MYK1815A{)1R](https://user-images.githubusercontent.com/91271243/185184457-4a033423-10e9-41ad-a5c3-aa238f0900da.png)

**Comment by 70loKirin** [comment]
搜索一番之后尝试过删掉node_modules文件夹再次重新安装依赖但仍然是这样

**Comment by Le-niao** [comment]
用`npm start` 不用加run

**Comment by 70loKirin** [comment]
> 用`npm start` 不用加run

虽然但是  打扰一下  还是和`npm run start`是一样的输出
