### ISSUE TITLE
关于#米游社查询的网页，比较复杂而且高度比较高的时候，第一次可以正常返回，第二次Chromium实例关闭或崩溃！问题

### ISSUE THREAD

**Issue by xianxincoder** [Le-niao/Yunzai-Bot#469]
关于#米游社查询的网页，比较复杂而且高度比较高的时候，第一次可以正常返回，第二次Chromium实例关闭或崩溃！问题

比如下图
![20220818154858](https://user-images.githubusercontent.com/109654219/185341399-14a6b124-a8bb-4696-bffb-3b70a40f62cc.jpg)

**Comment by Le-niao** [comment]
截图太快chromium会崩溃...，增加了点延迟应该不会了
