### ISSUE TITLE
关于公用ck的一点问题

### ISSUE THREAD

**Issue by baixiong2530** [Le-niao/Yunzai-Bot#470]
目前在使用用户ck的时候跳出下面的图片，而且无法清理这些c
![QQ图片20220818165642](https://user-images.githubusercontent.com/101954173/185354629-e96f1205-684b-4bce-a13e-99c14f8ee10e.jpg)

**Comment by YvetteVv** [comment]
同问，怎么删除已经失效的公共ck？

**Comment by YvetteVv** [comment]
plugins\genshin\defSet\mys\pubCk.yaml
在这个file

**Comment by summercanvas891** [comment]
yunzai-bot\Yunzai-Bot\config.js 打开这个文件里面的公共ck修改好就行

**Comment by Le-niao** [comment]
手动删了失效ck，或者配置多个公共ck
