### ISSUE TITLE
佬！！！更新报错了！！！

### ISSUE THREAD

**Issue by yibeiliang151** [Le-niao/Yunzai-Bot#475]
![image](https://user-images.githubusercontent.com/107047034/185732564-72d17355-0c4d-43c7-a66d-e304b8b9cac0.png)

**Comment by XiaoFuOS** [comment]
你的报错我也遇到辣，顺便补充一下，更新日志也查不出，时间不对是啥的，等佬看看(●—●)
![IMG_20220820_150630](https://user-images.githubusercontent.com/103229747/185733576-79154fb7-c32e-4c13-99d3-70245d89e253.jpg)

**Comment by Le-niao** [comment]
升级更新git

**Comment by yibeiliang151** [comment]
> 

唔..怎么操作哇，佬

**Comment by yibeiliang151** [comment]
跟着这个教程做修好啦，谢谢佬！！
https://blog.csdn.net/sinat_34104446/article/details/119914342?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_baidulandingword~default-1-119914342-blog-122273033.pc_relevant_aa_2&spm=1001.2101.3001.4242.2&utm_relevant_index=4
