### ISSUE TITLE
怎么查看指令来源哪个插件？增加日志内容显示可行不

### ISSUE THREAD

**Issue by overnightover** [Le-niao/Yunzai-Bot#479]
![image](https://user-images.githubusercontent.com/63415357/185783899-b71402bb-f575-40c5-b56b-89983666414c.png)
例如这个命令，本来只是#添加表情，现在是一个插件提供的，但是不知道是哪个

**Comment by liuly0322** [comment]
日志上显示 app 名为小工具，调用了 woc 函数，~~是还有什么信息需要补充吗~~

可以通过 `grep -rn "小工具" .` 找到插件文件位置

**Comment by HuIn2479** [comment]
这是 闲心插件 更新的
可以去看下闲心的提交就知道了
