### ISSUE TITLE
有段时间没更新了怎么把从2.18版本更新到v3呢

### ISSUE THREAD

**Issue by 673918731** [Le-niao/Yunzai-Bot#481]
有段时间没关注，最近回坑，从2.18自动更新不能直接更新
重新下载把data直接复制过去发现绑定的uid都没了
被回复“请先绑定uid”
该怎么处理呢

**Comment by SurplusFate** [comment]
3.0还没有完善，暂时先用2版本比较好，2版本正常更新应该能更新到2.2.1。

**Comment by Le-niao** [comment]
重新绑下uid
