### ISSUE TITLE
log的时间里面能加上日期吗

### ISSUE THREAD

**Issue by wzunknown** [Le-niao/Yunzai-Bot#482]
小功能, 方便查看核对

**Comment by karakoo** [comment]
可以根据自己需要改写这一行当中的`hh:mm:ss.SSS`：
https://github.com/Le-niao/Yunzai-Bot/blob/0278b5edf5f6aedab19e60a8bf0a66b00a50d078/lib/config/log.js#L25

参考格式：
<table>
<tr>
	<td>年
	<td>yyyy
<tr>
	<td>月
	<td>MM
<tr>
	<td>日
	<td>dd
<tr>
	<td>小时
	<td>HH
<tr>
	<td>分钟
	<td>mm
<tr>
	<td>秒
	<td>ss
<tr>
	<td>毫秒
	<td>SSS
</table>
