### ISSUE TITLE
更新后，qq信息经常收不到或者不发送

### ISSUE THREAD

**Issue by xuanxiaoyu69** [Le-niao/Yunzai-Bot#484]
rt，以下是error.log
![image](https://user-images.githubusercontent.com/23549070/185823834-037ad8ec-b610-460f-951e-783a38d0f49b.png)

**Comment by Le-niao** [comment]
网络问题，发送图片超时

**Comment by xuanxiaoyu69** [comment]
> 网络问题，发送图片超时

收到，我去排查一下，多谢
