### ISSUE TITLE
v3 出现 QQ 版本过低

### ISSUE THREAD

**Issue by HuIn2479** [Le-niao/Yunzai-Bot#488]
![IMG_20220822_181229.jpg](https://user-images.githubusercontent.com/66163050/185897376-7e75104e-c712-424c-a10a-90c66afe4a5b.jpg)

**Comment by liuly0322** [comment]
https://github.com/takayama-lily/oicq/issues/369

https://github.com/takayama-lily/oicq/issues/408

考虑更换账号或者更换登录平台配置？通过

`npm run login`

重新配置登录账号

**Comment by guobaisanxiu** [comment]
这个提示可能是你密码错了

**Comment by HuIn2479** [comment]
> https://github.com/takayama-lily/oicq/issues/369
> 
> https://github.com/takayama-lily/oicq/issues/408
> 
> 考虑更换账号或者更换登录平台配置？通过
> 
> `npm run login`
> 
> 重新配置登录账号

谢谢，更换运行平台好了。
