### ISSUE TITLE
已经签到完之后，手动签到文本在哪里改？

### ISSUE THREAD

**Issue by sulorrr** [Le-niao/Yunzai-Bot#492]
每次机器人自动签到完事，群里还有很多人手动签到，想问那个“今日已签到”这个文本在哪里能找到呢，我准备给它改成“已经自动签到了，别tm签到了”

**Comment by liuly0322** [comment]
`plugins/genshin/model/mysSign.js` 中搜索，有多处，不过手动替换会影响后续升级，建议谨慎操作

这里确实可以加个 “请勿重复签到”，不然挺容易被误解成签到成功的意思（
