### ISSUE TITLE
问下各位大佬，v3怎么查看已经绑定的ck啊

### ISSUE THREAD

**Issue by Msdyz123** [Le-niao/Yunzai-Bot#495]
如题，之前的用户管理和CK管理等操作貌似都不管用了，看指令也没找到，之前在电脑上部署的v2.1.8，后来直接把v3部署在手机上了，今天自动签到的时候有一个CK失效了但是不知道是哪个失效的，想提醒一下那位朋友更新一下ck来着

**Comment by KudouShinnyan** [comment]
路径:

**Comment by KudouShinnyan** [comment]
路径:
~/Yunzai-Bot/data/MysCookie/

**Comment by Msdyz123** [comment]
感谢大佬，我找到了，顺便一提好像也找到了一个临时能解决的方式，直接看运行日志，会提示绑定CK的QQ和对应的游戏账号ID，也可以看出来是谁的CK
