### ISSUE TITLE
运行时不时出现read ECONNABORTED报错

### ISSUE THREAD

**Issue by xiao909** [Le-niao/Yunzai-Bot#496]
目前确认不是网络因素

**Comment by Le-niao** [comment]
无详细日志或者报错，无法判断

**Comment by xiao909** [comment]
> 无详细日志或者报错，无法判断

[YzBot][07:16:02.555][ERRO] read ECONNABORTED
[YzBot][07:16:02.561][MARK] 183.47.102.165:8080 closed
[YzBot][07:16:02.712][MARK] 183.47.102.165:8080 connected

**Comment by Cvandia** [comment]
请问解决了吗
