### ISSUE TITLE
当前QQ版本过低，请升级至最新版登录

### ISSUE THREAD

**Issue by ChenAi140** [Le-niao/Yunzai-Bot#499]
![QQ图片20220824173353](https://user-images.githubusercontent.com/90126138/186384568-bee284a6-bbc4-4e38-8488-dc22859ef44e.jpg)

**Comment by Le-niao** [comment]
与更新无关，tx的提示

**Comment by ChenAi140** [comment]
但是macos无法登录，我换ipad就行了
