### ISSUE TITLE
大佬，能加个撤回功能吗

### ISSUE THREAD

**Issue by saiyoulala** [Le-niao/Yunzai-Bot#5]
我看oicq上有这个功能，但打印了下实例上没有。。

**Comment by Le-niao** [comment]
撤回方法有 Bot.deleteMsg

**Comment by saiyoulala** [comment]
> 撤回方法有 Bot.deleteMsg

好的

**Comment by saiyoulala** [comment]
> 撤回方法有 Bot.deleteMsg

大佬，用这个报错Invoke failed, because incorrect message_id

**Comment by saiyoulala** [comment]
是Bot.deleteMsg(event.messeg_id)这样操作吗，我这样操作后并没有撤回也没有报错

**Comment by Le-niao** [comment]
是不是超过两分钟了，管理员撤回消息才没有限制

**Comment by saiyoulala** [comment]
> 是不是超过两分钟了，管理员撤回消息才没有限制

没有，我是放在定时器里的，目前是定的5秒

**Comment by Le-niao** [comment]
```
let msgRes = await e.reply(msg);
if(msgRes.retcode==0){
   setTimeout(()=>{
       Bot.deleteMsg(msgRes.data.message_id);
    },5000)
}
```
