### ISSUE TITLE
提示登录版本过低

### ISSUE THREAD

**Issue by AbyssGazer-Oliver** [Le-niao/Yunzai-Bot#502]
[YzBot][00:39:20.871][ERRO] [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面
[YzBot][00:39:20.871][ERRO] 登录错误，已停止运行

操作系统：Win11

经过确认密码无误，修改密码后问题可以100%复现，扫码登录会出现同样问题

**Comment by Maolaohei** [comment]
选择android设备登录，不会报错

**Comment by 70loKirin** [comment]
> [YzBot][00:39:20.871][ERRO] [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面 [YzBot][00:39:20.871][ERRO] 登录错误，已停止运行
> 
> 操作系统：Win11
> 
> 经过确认密码无误，修改密码后问题可以100%复现，扫码登录会出现同样问题

修改登陆设备，macos会出现如上问题
