### ISSUE TITLE
关于 heartbeat timeout 错误

### ISSUE THREAD

**Issue by takichisato** [Le-niao/Yunzai-Bot#504]
![Screenshot_2022-08-24-23-24-01-58](https://user-images.githubusercontent.com/110453204/186564099-dd6c4b93-c210-420b-8fca-cd56b67b4df2.png)

基于centos运行，v3版本
1.当手机息屏一段时间后，云崽不会响应指令，把手机打开后运行正常，运行日志出现 
heartbeat timeout
heartbeat timeout*2
106.55.128.7:8080 closed
106.55.128.249:8080 connected
termux设置的有耗电保护，允许后台运行

2.查询人物动作是否完成  是什么任务，可以关闭或者设置冷却时间么

求大佬解答

**Comment by Le-niao** [comment]
1.网络断了
2.你自己加的不知道
