### ISSUE TITLE
[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by JS-JC** [Le-niao/Yunzai-Bot#507]

**Comment by 673918731** [comment]
怎么解决呢

**Comment by 673918731** [comment]
把登入设备换成安卓设备就可以了，好像是只有苹果的问题

**Comment by feilongproject** [comment]
> 把登入设备换成安卓设备就可以了，好像是只有苹果的问题

请问下怎么更换登陆设备？

**Comment by feilongproject** [comment]
> > 把登入设备换成安卓设备就可以了，好像是只有苹果的问题
> 
> 请问下怎么更换登陆设备？

找到了，在目录下的`config\config.js`文件里面可以修改

**Comment by IsXiaoShuMiao** [comment]
> 把登入设备换成安卓设备就可以了，好像是只有苹果的问题

现在换成安卓似乎也不行

**Comment by JS-JC** [comment]
> 

npm run login 可以
