### ISSUE TITLE
希望可以出一个签到的总开关，而且不是单个uid的开关

### ISSUE THREAD

**Issue by MuXia-0326** [Le-niao/Yunzai-Bot#513]
虽说可以直接修改配置yml，但是每次有改动都得删文件然后重新设置，有点繁琐，希望能添加一下签到总开关的命令配置

**Comment by Le-niao** [comment]
`plugins\genshin\config` 改这里的，别改def的，没有的配置可以删除文件，重启重新生成新的

**Comment by MuXia-0326** [comment]
> `plugins\genshin\config` 改这里的，别改def的，没有的配置可以删除文件，重启重新生成新的

config里面的文件和mys.set.yaml 比 def中的少了几个配置项，还有自动生成是不是需要删除def里面的文件？

**Comment by Le-niao** [comment]
def是默认的最好不要动，你删config的就行

**Comment by MuXia-0326** [comment]
我试试

**Comment by MuXia-0326** [comment]
应该可以了，感谢解答
