### ISSUE TITLE
mys签到问题

### ISSUE THREAD

**Issue by ad1078191153** [Le-niao/Yunzai-Bot#520]
已更新最新版，后台npm stop重启过bot。#全部签到以及#签到命令全部都是失败。

单独签到：
uid：******，签到失败：验证码失败
全部签到：
原神签到任务完成：50个
已签：2个
成功：0个
失败：48个

自己CK删除重新添加过，故障依旧……
版本日志更新到08-27 10:54
签到日志没有报红
[原神签到失败][uid:****][qq:*****]：验证码失败 第1个
[原神签到失败][uid:****][qq:*****]：验证码失败 第2个
下面类推……

**Comment by Le-niao** [comment]
米游社的限制，目前无法跳过验证码

**Comment by ad1078191153** [comment]
您好，因为我是看到别人都似乎正常使用，请问是我这边有什么误操作吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月27日(星期六) 中午12:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Le-niao/Yunzai-Bot] mys签到问题 (Issue #520)





 
米游社的限制，目前无法跳过验证码

**Comment by canyi2** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/598，这里似乎有可行性的方案，但我尝试，并没有用处
