### ISSUE TITLE
V3.0配置主人QQ号不起作用

### ISSUE THREAD

**Issue by 951605048** [Le-niao/Yunzai-Bot#524]
配置文件中配置好主人QQ号，启动后尝试【#更新】【#重启】无效，关机再配置或者热配置，都是无效，提示“暂无权限，只有主人才能操作”
奇怪的是启动成功时有时会给主人qq发启动成功的命令提示

怎么让主人QQ可以正常使用更新重启等命令呢？

配置文件路径：在/config/config/other.yaml
配置详情：
# 主人QQ号
masterQQ: 951605048
![master](https://user-images.githubusercontent.com/44488124/187057867-1c7c63f2-6bc3-4a10-8fd0-e2ee9b509c7f.png)

**Comment by Le-niao** [comment]
配置错了这里是数组
