### ISSUE TITLE
pupeteer启动失败

### ISSUE THREAD

**Issue by Fahaxikiii** [Le-niao/Yunzai-Bot#525]
![Screenshot_2022_0828_160509.png](https://user-images.githubusercontent.com/93320886/187064324-bfb89968-02ec-4eb6-a392-a4485ae7b4d1.png)armV7的armbian20.12（Debian GNU/Linux 10 (buster) with Linux 5.9.0-rc7-aml-s812）

**Comment by Le-niao** [comment]
手动装chromium试下
