### ISSUE TITLE
全部更新指令出了问题，help，非常感谢啦

### ISSUE THREAD

**Issue by Pikasn** [Le-niao/Yunzai-Bot#527]
[更新][updateAll][私聊][Pikas(319557054)] #全部更新
fatal: detected dubious ownership in repository at 'D:/原神机器人/Yunzai-Bot'
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/原神机器人/Yunzai-Bot'

Set the environment variable GIT_TEST_DEBUG_UNSAFE_DIRECTORIES=true and run
again for more information.
[YzBot][23:02:04.243][ERRO] [更新][updateAll]
[YzBot][23:02:04.243][ERRO] Error: Command failed: git rev-parse --short HEAD
fatal: detected dubious ownership in repository at 'D:/原神机器人/Yunzai-Bot'
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/原神机器人/Yunzai-Bot'

Set the environment variable GIT_TEST_DEBUG_UNSAFE_DIRECTORIES=true and run
again for more information.

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at update.getcommitId (file:///D:/%E5%8E%9F%E7%A5%9E%E6%9C%BA%E5%99%A8%E4%BA
%BA/Yunzai-Bot/plugins/other/update.js:151:26)
    at update.runUpdate (file:///D:/%E5%8E%9F%E7%A5%9E%E6%9C%BA%E5%99%A8%E4%BA%B
A/Yunzai-Bot/plugins/other/update.js:114:35)
    at updateAll (file:///D:/%E5%8E%9F%E7%A5%9E%E6%9C%BA%E5%99%A8%E4%BA%BA/Yunza
i-Bot/plugins/other/update.js:208:16)
    at PluginsLoader.deal (file:///D:/%E5%8E%9F%E7%A5%9E%E6%9C%BA%E5%99%A8%E4%BA
%BA/Yunzai-Bot/lib/plugins/loader.js:246:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Le-niao** [comment]
权限问题，自行百度解决

**Comment by Pikasn** [comment]
谢谢你&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 上午8:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Le-niao/Yunzai-Bot] 全部更新指令出了问题，help，非常感谢啦 (Issue #527)





 
权限问题，自行百度解决
 
—
‎直接回复此电子邮件、‎‎在 GitHub 上查看‎‎或‎‎取消订阅‎‎。‎
‎您收到此消息是因为您创作了该线程。‎Message ID: ***@***.***&gt;
