### ISSUE TITLE
#更新日志  报错

### ISSUE THREAD

**Issue by yhArcadia** [Le-niao/Yunzai-Bot#534]
#更新日志  报错：
Error: Command failed: git log  -20 --oneline --pretty=format:"%h||[%cd]  %s" --date=format:"%m-%d %H:%M"
fatal: unknown date format format:%m-%d %H:%M

#更新  报错：
Yunzai-Bot已经是最新
最后更新时间：获取时间失败

![image](https://user-images.githubusercontent.com/85126209/187270789-2c71899c-0a77-4c2e-b20b-381000015d32.png)
![image](https://user-images.githubusercontent.com/85126209/187271064-1faa586b-98f1-475c-9636-b3468dcb6ebc.png)

**Comment by SirlyDreamer** [comment]
尝试更新一下git
