### ISSUE TITLE
遇到问题 给机器人发送#帮助 图片显示乱码

### ISSUE THREAD

**Issue by chongdong12** [Le-niao/Yunzai-Bot#546]
![QQ图片20220901173649](https://user-images.githubusercontent.com/95455587/187883256-4f7f88c0-111a-4135-8b59-e7aafd329781.jpg)

**Comment by Donggzs** [comment]
你这是没有安装浏览器中文字体

**Comment by Donggzs** [comment]
apt install -y --force-yes --no-install-recommends fonts-wqy-microhei

**Comment by chongdong12** [comment]
> apt install -y --force-yes --no-install-recommends fonts-wqy-microhei

解决了，非常感谢！
