### ISSUE TITLE
V3云崽通过链接的方式#更新抽卡记录获得的信息无法和上传的excel和json记录正确合并

### ISSUE THREAD

**Issue by OctoberCK** [Le-niao/Yunzai-Bot#552]
通过链接自动获取的抽卡记录是最近六个月的，这部分记录不会与excel和json的记录正确合并，会出现大量的重复数据。

**Comment by Le-niao** [comment]
提供能复现的json或者excel数据我测试下

**Comment by OctoberCK** [comment]
> 提供能复现的json或者excel数据我测试下

考虑到隐私问题QQ发您excel数据

**Comment by kirigirisan** [comment]
> 提供能复现的json或者excel数据我测试下

怀疑是导入的祈愿数据顺序识别出来的祈愿时间顺序是倒的（正常应该是新祈愿的在上方） （问题：#555）

**Comment by Le-niao** [comment]
更新后再重新导入试试

**Comment by OctoberCK** [comment]
已经正常了。
