### ISSUE TITLE
绑定cookie时，服务器收不到cookie

### ISSUE THREAD

**Issue by Sesshouin-Kiara** [Le-niao/Yunzai-Bot#562]
踩坑经过：有个老哥绑定cookie死活没反应，上服务器后台看了下，发现没有收到cookie（其实机器人qq就没收到cookie），经其他issues的回答提醒，发现是没加好友cookie太长导致机器人收不到消息的锅，需要先加好友才能发

**Comment by SirlyDreamer** [comment]
绑定cooklie确实得先加好友啊
