### ISSUE TITLE
qq的签到推送，时有时无

### ISSUE THREAD

**Issue by Mcui7** [Le-niao/Yunzai-Bot#563]
![559B1E74-5AE2-402D-9A4E-0996736FAE18](https://user-images.githubusercontent.com/111735765/188329448-1bea9778-0377-40aa-a7ea-a05744be0e0f.png)
最早2.x版本，签到之后，会私聊我签到是否成果，后来有一段时间没了，然后更新3.0会有这个推送；但是周末更新了一下，又没推送了。找了一下设置也没找到，在config.js里面，就要看到是开启的，请问这个是什么问题呀。

**Comment by Ailumar** [comment]
还有2.x版本时会推送签到结果给每一个绑定ck的QQ,不知道现在还有没有,怎么开?

**Comment by Le-niao** [comment]
没有个人推送，只有主人推送
