### ISSUE TITLE
签到被验证码拦截，以及解决思路

### ISSUE THREAD

**Issue by TaoismDeepLake** [Le-niao/Yunzai-Bot#564]
![image](https://user-images.githubusercontent.com/19328867/188350735-a1654f9a-7bb9-48ef-9402-ed285474e727.png)

米游社在 2.33.1 版本左右 加入了 geetest 行为识别

这里有MIT开源的参考方案：
https://github.com/Womsxd/AutoMihoyoBBS

**Comment by Le-niao** [comment]
你可以手动改ua试试

**Comment by lanlanwa** [comment]
> 你可以手动改ua试试

ua在哪儿改？
