### ISSUE TITLE
为什么绑定ck的时候需要重启才能生效

### ISSUE THREAD

**Issue by 15015070064** [Le-niao/Yunzai-Bot#569]
![WC6C%Z5L}HRWRL{B~3HV)4W](https://user-images.githubusercontent.com/40047545/188680772-afb38e19-5b35-4088-93d5-0aef5b2a9fcb.jpg)

需要重启机器人 这个ck才能生效，为啥

**Comment by Le-niao** [comment]
图鉴插件的bug

**Comment by ghostcatu** [comment]
> 
能具体讲讲吗 我看看在哪改
