### ISSUE TITLE
puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by OneOne9** [Le-niao/Yunzai-Bot#573]
[YzBot][22:51:24.329][ERRO] Error: Failed to launch the browser process!
/root/MyBot/Yunzai-Bot/node_modules/.pnpm/puppeteer@13.7.0/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

[YzBot][22:51:24.330][ERRO] puppeteer Chromium 启动失败

**Comment by SirlyDreamer** [comment]
Chromium依赖库未安装好

**Comment by SirlyDreamer** [comment]
参考https://github.com/Le-niao/Yunzai-Bot/issues/154

里面安装chrome library那一部分
