### ISSUE TITLE
redis socket链接异常关闭

### ISSUE THREAD

**Issue by mlrsyz** [Le-niao/Yunzai-Bot#575]
这种应该如何设置   本人使用的我自己的服务端redis  配置了域名端口+密码    运行几分钟后就断开了
![image](https://user-images.githubusercontent.com/44489042/188922504-e13b29a0-76a9-48f0-9f0c-4f3bba405ab8.png)

**Comment by Le-niao** [comment]
估计持久化保存失败，redis挂了

**Comment by mlrsyz** [comment]
并没有&nbsp; &nbsp;希望能加一个redis心跳检测机制
我redis设置了空闲180s的&nbsp; timeout&nbsp; 我给关了才行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月9日(周五) 上午9:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Le-niao/Yunzai-Bot] redis socket链接异常关闭 (Issue #575)




 
估计持久化保存失败，redis挂了
