### ISSUE TITLE
[疑问]请问一下bot管理员怎么管理别人绑定的uid

### ISSUE THREAD

**Issue by chongdong12** [Le-niao/Yunzai-Bot#584]
比如群里有人绑定了一个uid后，我如果想对这个uid进行操作的话应该怎么做呢？

**Comment by VeritasAlex** [comment]
./data/UserData目录下有以UID命名的json，不知道你要找的是不是这个。

**Comment by chongdong12** [comment]
> ./data/UserData目录下有以UID命名的json，不知道你要找的是不是这个。
emm那个我也看了，应该是某个人的面板信息，我想知道的是能不能删除别人绑定的uid，比如某人发#绑定指令，绑定了某个uid， 我可不可以直接删除他绑定的uid 让他取消绑定呢

**Comment by Donggzs** [comment]
好像是写到redis的?  
我也想帮人编辑绑定信息。
UID还会丢失呢， 之前@别人发指令后对方的uid就丢失了，得重新绑定。

**Comment by chongdong12** [comment]
> 好像是写到redis的? 我也想帮人编辑绑定信息。 UID还会丢失呢， 之前@别人发指令后对方的uid就丢失了，得重新绑定。

奥原来如此，那只能等了
