### ISSUE TITLE
米游社接口请求失败，暂时无法查询?

### ISSUE THREAD

**Issue by YKKKK-1** [Le-niao/Yunzai-Bot#585]
version: 3.0.0
服务器在首尔，用这台机器搭的节点是可以打开米友社的，防火墙已经关掉了
日志
![image](https://user-images.githubusercontent.com/109789425/189476033-f2663ef6-29ac-46d7-98fa-fca291a35119.png)
![image](https://user-images.githubusercontent.com/109789425/189476271-2dd093fa-b5d4-4b9d-a197-36f131d09ed0.png)

**Comment by Le-niao** [comment]
连接米游社接口超时
