### ISSUE TITLE
pnpm依赖安装错误

### ISSUE THREAD

**Issue by DDGG123** [Le-niao/Yunzai-Bot#595]
3.安装依赖
这一步会报错
DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ pnpm install -P
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +340
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ENOENT  ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pnpm\art-template@4.13.2\node_modules\acorn'

pnpm: ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pnpm\art-template@4.13.2\node_modules\acorn'
我之前在服务器端安装的很正常，但是内存不够天天重启，无法忍受打算在PC重新搭一个，没想到最简单的地方都卡住了，百度也找不到好的解答。
我尝试把服务器端的node_modules文件夹移过来覆盖，但是运行pnpm install -P仍然会报错，且覆盖后的文件也消失了。

**Comment by Le-niao** [comment]
删除pnpm-lock.yaml，node_modules 重新install试下

**Comment by DDGG123** [comment]
刚刚

**Comment by DDGG123** [comment]
我在上午又尝试了多次，包括删除pnpm-lock.yaml，node_modules ，甚至删除整个Yunzai-Bot文件夹，去百度如何删除pnpm，并去C:\Users\DG\AppData\Roaming\npm删除过整个文件夹，去给pnpm换源，重装了git，修复了node.js，该报错仍然存在，这是我最后一次尝试时的失败日志
DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ npm install pnpm -g

added 1 package in 4s

DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ npm install pnpm -g

changed 1 package in 5s

DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ pnpm install -P
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +340
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 340, reused 0, downloaded 0, added 0
Progress: resolved 340, reused 1, downloaded 0, added 0
Progress: resolved 340, reused 2, downloaded 0, added 0
 ENOENT  ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pm\art-template@4.13.2\node_modules\estraverse'

pnpm: ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pnpart-template@4.13.2\node_modules\estraverse'

$ npm install pnpm -g该命令的回复和之前几次尝试不一样，很奇怪
$ pnpm install -P输入后的加载长度也不一样，有过很长有过很短，但都是同样的报错，怀疑和我试图 翻墙有关

**Comment by DDGG123** [comment]
删除pnpm-lock.yaml，node_modules又试了一次
DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ npm install pnpm -g

changed 1 package in 5s

DG@DESKTOP-TCVHMFP MINGW64 /f/Yunzai-Bot (main)
$ pnpm install -P
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 95, reused 9, downloaded 0, added 0
Progress: resolved 270, reused 22, downloaded 0, added 0
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Progress: resolved 437, reused 76, downloaded 0, added 0
Packages: +338
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 492, reused 90, downloaded 0, added 0
 ENOENT  ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pnpm\art-template@4.13.2\node_modules\escodegen'

pnpm: ENOENT: no such file or directory, stat 'F:\Yunzai-Bot\node_modules\.pnpm\art-template@4.13.2\node_modules\escodegen'
注意到pnpm-lock.yaml并没有回来
