### ISSUE TITLE
迁移机器人

### ISSUE THREAD

**Issue by 12123ads** [Le-niao/Yunzai-Bot#60]
请问我想迁移这个机器人到别的服务器应该备份哪些文件？

**Comment by Le-niao** [comment]
`Yunzai-Bot/data` 本地文件，表情，抽卡记录等等
`dump.rdb` redis持久化数据

保存这两个就行

**Comment by 12123ads** [comment]
数据都迁移过去了，但字体好像出问题了
![-48c45438088c84a1](https://user-images.githubusercontent.com/69107029/162360374-c1af70bd-2b32-4ccd-9dcf-1ae86ac0ca25.png)

**Comment by Le-niao** [comment]
服务器安装中文字体
