### ISSUE TITLE
请问V3的人工智障的功能是被砍了吗

### ISSUE THREAD

**Issue by Familiar-coder** [Le-niao/Yunzai-Bot#604]
![截图_20220914111120](https://user-images.githubusercontent.com/84607943/190050438-7cc99b83-e302-49d5-9870-96beb678f2cb.png)
之前有人工智障时，群友发莫名其妙的命令时可以靠人工智障的兜底话术进行提醒，现在V3版本好像找不到这功能了。

**Comment by Le-niao** [comment]
没有
