### ISSUE TITLE
V3自动更新失败，报错如下

### ISSUE THREAD

**Issue by BIMOQS** [Le-niao/Yunzai-Bot#608]
更新失败！存在冲突：
Error: Command failed: git pull --no-rebase
error: Your local changes to the following files would be overwritten by merge:
	package.json
	pnpm-lock.yaml
Please commit your changes or stash them before you merge.
Aborting

请解决冲突后再更新，或者执行#强制更新，放弃本地修改

**Comment by Le-niao** [comment]
请解决冲突后再更新，或者执行#强制更新，放弃本地修改
