### ISSUE TITLE
更新的时候新的报错

### ISSUE THREAD

**Issue by 1485470102** [Le-niao/Yunzai-Bot#611]
#375 更新

Error: Command failed: git pull --no-rebase
error: 您对下列文件的本地修改将被合并操作覆盖：
	package.json
	pnpm-lock.yaml
请在合并前提交或贮藏您的修改。
正在终止
更新 3162534..e9ce51a

**Comment by Msdyz123** [comment]
同上，昨天更新还是没问题的，今天全部更新v3云仔就不能更了，插件还是可以正常更新的，蹲一个大佬（虽然现在也不怎么影响使用）

**Comment by SirlyDreamer** [comment]
更新依赖了，每次云崽更新依赖的时候都会出现这样的状况

具体解决方案如下：

1.进入控制台，删除package.json和pnpm-lock.yaml

```bash
rm ./package.json
rm ./pnpm-lock.yaml
```

2.拉取更新

```bash
git pull
```

3.重新安装依赖
```
pnpm install -P
```

如果出现插件因为依赖报错，则按照插件安装依赖的命令继续解决
