### ISSUE TITLE
无法查看武器详情

### ISSUE THREAD

**Issue by 2860566067ssly** [Le-niao/Yunzai-Bot#615]
机器人未识别命令，只有武器不行

**Comment by Zacharvc** [comment]
好像v3还没有武器图鉴，喵喵有角色图鉴，逍遥-cvs图鉴插件v3用不了

**Comment by Frozenfox6** [comment]
要装逍遥插件，v3可以用，按 https://docs.qq.com/doc/DT25kQ0x3VVlyc0Jz 里面逍遥插件的部分的每一步走一遍，因为装完还要装图片包，图鉴也不是默认打开的
