### ISSUE TITLE
关于体力帮助文档的建议

### ISSUE THREAD

**Issue by weilai5201314** [Le-niao/Yunzai-Bot#620]
今天帮群友获取cookie，他输入`document.cookie`之后显示的cookie不完整。
在他和我的电脑上都输入了`document.cookie`，都显示了省略号，且双击或者`ctrl + a`全选获取的cookie都带有省略号。
希望文档可以同时添加原来的`javascript:(function(){prompt('', document.cookie)})();`，最后就是用这个解决的问题。

- 文档显示：
![4E185A73AF433DC5FD27CE27A1AAD38D](https://user-images.githubusercontent.com/99032101/191265207-24f458b4-cb0e-456a-b9db-f175a2bbfb1d.jpg)

- 群友显示：
![1F62AA7111EE0718EC321DAE915BD416](https://user-images.githubusercontent.com/99032101/191265240-4a6c646c-5ca6-4398-aca3-35c462905c19.jpg)

- 最后解决：
![23A81EAD90E5AF3288734A4D1C89DC05](https://user-images.githubusercontent.com/99032101/191265285-e2691574-d8d6-4fa5-a8a4-a0052bb72201.jpg)

**Comment by weilai5201314** [comment]
- 全选之后即使带括号，也无法显示全
<img width="291" alt="image" src="https://user-images.githubusercontent.com/99032101/191267048-67f75dd9-d9e0-4bf5-8686-6105a3011271.png">

**Comment by lovepoi** [comment]
有没有可能你输完之后按个回车就全了

**Comment by Le-niao** [comment]
![QQ截图20220921093519](https://user-images.githubusercontent.com/12881780/191394657-3d878ad3-c013-4a63-9c4c-a069aa69183c.png)

**Comment by weilai5201314** [comment]
是我马了，谢谢
