### ISSUE TITLE
载入插件错误：enka

### ISSUE THREAD

**Issue by cc13090101** [Le-niao/Yunzai-Bot#633]
报错的版本更新时间为2022年9月24日09:37左右，修复enkaNetwork文件夹报错后的版本。
请问我该如何修复？
0|Yunzai-Bot  | [YzBot][09:33:48.825][ERRO] 载入插件错误：enka
0|Yunzai-Bot  | [YzBot][09:33:48.825][ERRO] Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'enka-network-api' imported from /root/Yunzai-Bot/plugins/genshin/model/enkaNetwork.js
0|Yunzai-Bot  |     at new NodeError (node:internal/errors:372:5)
0|Yunzai-Bot  |     at packageResolve (node:internal/modules/esm/resolve:954:9)
0|Yunzai-Bot  |     at moduleResolve (node:internal/modules/esm/resolve:1003:20)
0|Yunzai-Bot  |     at defaultResolve (node:internal/modules/esm/resolve:1218:11)
0|Yunzai-Bot  |     at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
0|Yunzai-Bot  |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
0|Yunzai-Bot  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
0|Yunzai-Bot  |     at link (node:internal/modules/esm/module_job:78:36) {
0|Yunzai-Bot  |   code: 'ERR_MODULE_NOT_FOUND'
0|Yunzai-Bot  | }

**Comment by Georgebillion** [comment]
同问题+1，也是在更新之后还是有这个问题

**Comment by MuXia-0326** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/629

**Comment by Georgebillion** [comment]
回复，现有源貌似不能直接安装enka包，建议走离线安装之后再重新install，且enka的git源即使是去反代也无法安装，很怪

**Comment by RightTriangle** [comment]
尝试给github配置一下ssh公钥，enka的git源拉取通过ssh拉取的
