### ISSUE TITLE
能否支持修改ck字段名称？因为名称本身被QQ屏蔽了

### ISSUE THREAD

**Issue by CUZNIL** [Le-niao/Yunzai-Bot#634]
过去QQ屏蔽了sm这个短语，导致临时会话发整段ck会被QQ拦截。不过显然可以通过不发smidV2解决，毕竟这段并不重要。
现在（可能就这俩天）又屏蔽了ke，但是cookie_token是必须包含的内容，导致根本无法通过临时会话绑定ck。
这是例图
![}GQT F(ASZD5}JYZFCVZ5](https://user-images.githubusercontent.com/76582404/192085254-ded285d8-06f3-4452-9cfc-d0fc0688daf9.png)

**Comment by Le-niao** [comment]
加好友再绑定ck
