### ISSUE TITLE
使用一些指令会导致cookie失效

### ISSUE THREAD

**Issue by Yeshao6472** [Le-niao/Yunzai-Bot#636]
[event.zip](https://github.com/Le-niao/Yunzai-Bot/files/9638854/event.zip)
（问题复现视频）
![yunzai](https://user-images.githubusercontent.com/77495862/192102625-1653b5ea-aa6b-478f-913f-b0033c5c42fe.png)
（npm run log的截图）
绑定ck后使用#签到，#原石等指令会导致cookie失效。
系统：Ubuntu 20.04，1h2g. Yunzai-Bot版本v3。

**Comment by Le-niao** [comment]
因为ck失效了

**Comment by CeciliaAki** [comment]
我也是这个问题，使用miao-plugin查看“#柯莱”
和“#签到”
都使几分钟之前有效的cookie失效了
看起来是很随机的情况
