### ISSUE TITLE
centos下中文乱码

### ISSUE THREAD

**Issue by aboyasd123** [Le-niao/Yunzai-Bot#637]
![image](https://user-images.githubusercontent.com/51694321/192106832-4db49931-18c2-41e8-b8cd-d0da33092046.png)中文乱码怎么解决啊

**Comment by aboyasd123** [comment]
解决了，我傻逼了😂😂

**Comment by xingyunlee12138** [comment]
> 解决了，我傻逼了😂😂

老哥怎么解决的啊，我这安装了字体但是貌似还是不起作用

**Comment by aboyasd123** [comment]
> > 解决了，我了😂😂
> 
> 老哥怎么解决的啊，我这安装了字体但是貌似还是不起作用

yum groupinstall fonts -y
我只用了这个命令，或者你把centos设置成中文试试
