### ISSUE TITLE
有没有可能做个接口拓展到其它聊天工具？

### ISSUE THREAD

**Issue by ProblemFactory** [Le-niao/Yunzai-Bot#638]
我想同时在telegram和qq部署云崽，看了下代码似乎不太容易改成telegram版本，有没有什么好的方案？

**Comment by liuly0322** [comment]
参考 Yunzai 的测试流程，
https://github.com/Le-niao/Yunzai-Bot/blob/main/lib/tools/test.js
https://github.com/Le-niao/Yunzai-Bot/blob/main/lib/tools/command.js、
也就是事件响应这块可以让 Yunzai 及插件完成，但是图片/消息的接口都需要自己处理
