### ISSUE TITLE
qq发送 #更新 指令更新报错

### ISSUE THREAD

**Issue by RightTriangle** [Le-niao/Yunzai-Bot#641]
![image](https://user-images.githubusercontent.com/47479859/192187803-79c04e91-9cd0-478b-8907-b70c8a908a69.png)

**Comment by liuly0322** [comment]
gitee 源的问题

如果你的服务器能正常访问 github，建议 origin 换为 github，否则等待 gitee 修复

**Comment by Le-niao** [comment]
重试几次还是不行，可以换成github试试
