### ISSUE TITLE
如何彻底删除V2版的配置文件

### ISSUE THREAD

**Issue by aquestionx** [Le-niao/Yunzai-Bot#642]
我的操作系统是Ubuntu 18.04，之前在用V2版，换V3版的时候就把V2版的整个文件夹删掉了。V3版目前能正常登录使用，但是在qq上对机器人发#重启的命令后，机器人会显示“开始执行重启，请稍等.. 当前为前台运行，重启将转为后台...”，然后不会提示重启成功。

此时在terminal输入 npm run log，日志文件显示如下
![log](https://user-images.githubusercontent.com/60572624/192209839-09a547c8-3d9a-4213-a09b-24bfeb456f14.jpg)

输入npm run stop关闭机器人则显示如下
![error](https://user-images.githubusercontent.com/60572624/192209598-a8e3b34e-1771-41d5-91e6-bb08d169eefa.PNG)

像我这样的情况是不是V2版的配置文件还有残留所以导致机器人不能重启

**Comment by liuly0322** [comment]
`rm -rf ~/.pm2`

related issue: https://github.com/Unitech/pm2/issues/1943
