### ISSUE TITLE
出现无法登录的问题

### ISSUE THREAD

**Issue by FuckAnyProblem** [Le-niao/Yunzai-Bot#643]
![-457b8ede88e7bdb0](https://user-images.githubusercontent.com/114020110/192341321-03a80367-746b-4c53-b1c3-84da014aeb77.jpg)
试过本地登录然后替换了，但是替换后仍要扫码

**Comment by Le-niao** [comment]
用密码登录试试

**Comment by JeckieBest** [comment]
可以下一个爱加速，把地址换成你服务器的地区，然后直接扫码就行，没天有20分钟试用，基本够用

**Comment by FuckAnyProblem** [comment]
> 用密码登录试试

密码登录不行

**Comment by FuckAnyProblem** [comment]
> 可以下一个爱加速，把地址换成你服务器的地区，然后直接扫码就行，没天有20分钟试用，基本够用

这个方法可行，谢谢

**Comment by Arturia169** [comment]
如果是国外的服务器怎么解决？
