### ISSUE TITLE
希望可以支持使用代理

### ISSUE THREAD

**Issue by Lactococcuslactis** [Le-niao/Yunzai-Bot#646]
国际服的米游社屏蔽了国内ip，使用代理才可以连接，大佬若是觉得合理，希望添加配置代理的方式

**Comment by ctrlcvs** [comment]
> 国际服的米游社屏蔽了国内ip，使用代理才可以连接，大佬若是觉得合理，希望添加配置代理的方式
配置文件中本来就可以添加配置代理ip
