### ISSUE TITLE
登录保护验证无法通过，卡在扫码验证

### ISSUE THREAD

**Issue by Sagili365** [Le-niao/Yunzai-Bot#647]
![image](https://user-images.githubusercontent.com/102888970/192565442-820335e6-922e-460b-b30a-2fec69f64eea.png)
尝试多次未果，手机上一直提示账户异地登录，忽略后服务器上继续和以前一样操作，均卡在这一步

**Comment by ImHeroZero** [comment]
同样错误,有知道怎么办的大佬吗

**Comment by wangxso** [comment]
试试用ipad登录

**Comment by ImHeroZero** [comment]
> 试试用ipad登录

试了，一样的错

**Comment by Donggzs** [comment]
lib/events/login.js

**Comment by Donggzs** [comment]
上面有注释，扫码仅可同IP~

**Comment by Sagili365** [comment]
那，请问怎么使用发送短信验证码的方式登陆呢？我使用SendSms()没有反应

**Comment by ShirosakiMio** [comment]
服务器上搭建代理再用手机连上扫码就可以了

**Comment by ImHeroZero** [comment]
我解决了,
需要把链接放到手机QQ里面打开才能显示二维码,
再把二维码截完图应该可以直接识别二维码(不行的话可以把图放到服务器再用手机QQ扫),然后就能授权登录下一步了.
