### ISSUE TITLE
为什么使用#签到、#全部签到返回失效啊？

### ISSUE THREAD

**Issue by 976863929** [Le-niao/Yunzai-Bot#648]
![1664322821201](https://user-images.githubusercontent.com/44665525/192657659-8a4cd62b-bba4-4831-8985-a2d851ee5628.jpg)

**Comment by Le-niao** [comment]
因为cookie失效了

**Comment by 976863929** [comment]
cookie应该没失效的，因为把之前的cookie重新绑定后使用#体力等命令都没问题的；同时也尝试过重新获取cookie后执行#签到命令还是返回失效
