### ISSUE TITLE
请问提示载入插件错误：enka  需要怎么处理..

### ISSUE THREAD

**Issue by q35654046** [Le-niao/Yunzai-Bot#652]
![image](https://user-images.githubusercontent.com/17274175/192728630-ff637475-b4db-489b-a5d1-d7f757b60ec7.png)

**Comment by MuXia-0326** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/639
https://github.com/Le-niao/Yunzai-Bot/issues/633
https://github.com/Le-niao/Yunzai-Bot/issues/629

**Comment by q35654046** [comment]
感谢大佬
