### ISSUE TITLE
更新3.1角色后，抽卡素材不正常显示

### ISSUE THREAD

**Issue by TangbohuDianPaoZhang** [Le-niao/Yunzai-Bot#654]
如图，抽卡界面不能正常显示请问如何解决
![QQ图片20220928213328](https://user-images.githubusercontent.com/93420604/192792343-79e0d88d-083a-4613-83c5-e9e015252366.jpg)

**Comment by liuly0322** [comment]
🤔可能是截图时机的问题

https://github.com/yoimiya-kokomi/miao-plugin/blob/master/adapter/lib/puppeteer.js

可以考虑主线代码参照这个修改，https://github.com/yoimiya-kokomi/miao-plugin/blob/8823eff9051894f09759cdd219eb725c6158ae59/components/common-lib/render.js#L27 给出了具体等待参数
