### ISSUE TITLE
签到问题咨询

### ISSUE THREAD

**Issue by 976863929** [Le-niao/Yunzai-Bot#655]
为什么使用#签到、#全部签到返回失效啊？
但是实际cookie应该没失效的，因为把之前的cookie重新绑定后使用#体力等命令都没问题的；同时也尝试过重新登录米游社获取cookie后执行#签到命令还是返回失效

**Comment by OmmOWhale01** [comment]
这个在UserAgent的那个issues里提到了，是因为常用设备风控的问题，那个issues的楼主用的其他项目的修改UA进行签到的，云崽的风控机制目前无解
