### ISSUE TITLE
在加载插件完成之后卡住了没有执行给管理员发信息的任务

### ISSUE THREAD

**Issue by Guoxiang1** [Le-niao/Yunzai-Bot#656]
[YzBot][01:29:09.213][MARK] Yunzai-Bot 启动中...
[YzBot][01:29:09.217][MARK] 连接redis....
[YzBot][01:29:09.330][MARK] 尝试启动redis
[YzBot][01:29:09.875][MARK] 连接redis成功
[YzBot][01:29:09.895][MARK] ----------
[YzBot][01:29:09.895][MARK] Package Version: oicq@2.3.1 (Released on 2022/6/21)
[YzBot][01:29:09.896][MARK] View Changelogs：https://github.com/takayama-lily/oicq/releases
[YzBot][01:29:09.896][MARK] ----------
[YzBot][01:29:10.076][MARK] 43.135.106.161:8080 connected
[YzBot][01:29:10.540][MARK] Welcome, echo  if:() ! 正在加载资源...
[YzBot][01:29:10.845][MARK] 加载了19个好友，4个群，1个陌生人
[YzBot][01:29:10.848][MARK] ----^_^----
[YzBot][01:29:10.849][MARK] Yunzai-Bot 上线成功 版本v3.0.0
[YzBot][01:29:10.850][MARK] https://github.com/Le-niao/Yunzai-Bot
[YzBot][01:29:10.862][INFO] 加载插件中..
[YzBot][01:29:11.537][INFO] ---------^_^---------
[YzBot][01:29:11.537][INFO] 喵喵插件2.0.0初始化~
[YzBot][01:29:11.746][INFO] 加载定时任务[2个]
[YzBot][01:29:11.746][INFO] 加载插件完成[15个]
[YzBot][01:29:11.747][INFO] -----------

在这之后就没有反应了，重启服务器也无效，log中也没有新信息

**Comment by Donggzs** [comment]
现在是这样的，已经启动完成了。你发送指令看看。

**Comment by Guoxiang1** [comment]
> 现在是这样的，已经启动完成了。你发送指令看看。

![S20929-10462816.png](https://user-images.githubusercontent.com/81576234/192927088-beb9af6a-0d33-4831-905e-b23dc58082be.png)

发指令也是没有用

**Comment by Le-niao** [comment]
装下chromium扩展
