### ISSUE TITLE
关于#体力出现   请先#绑定cookie问题 （bug复现或者说新的更严重的bug?）

### ISSUE THREAD

**Issue by ctrlcvs** [Le-niao/Yunzai-Bot#659]
![image](https://user-images.githubusercontent.com/73279880/193171799-a36f735a-65dd-4e97-9e7f-0cb3b5d6919b.png)
![image](https://user-images.githubusercontent.com/73279880/193171936-91eace0e-a5c1-449c-91ef-fa96e554fc06.png)
![image](https://user-images.githubusercontent.com/73279880/193172010-2abe3c90-ce39-4dc2-b77d-90afe55e4b8e.png)
用户签到ok，但是#体力会提示请选绑定cookie，另外图鉴的方法获取体力数据是直接调用你主体方法获取
然后再一个就是，我这边不是一个用户出现这种情况，是同时全部的都出现了这种情况

**Comment by Le-niao** [comment]
手动复制ck的，重启下就行

**Comment by ctrlcvs** [comment]
> 手动复制ck的，重启下就行

确实重启一下又好了，这是什么原因，这些cookie都是没有动过的

**Comment by kikasyou** [comment]
开启redis的AOF持久化
1) Windows系统
执行如下操作：
#修改redis.windows.conf配置文件，把no改为 yes
appendonly yes
#确定存储文件名是否正确
2) Linux系统
执行如下操作：
#修改配置文件：
vim /etc/redis/redis.conf
appendonly yes # 把 no 改为 yes
