### ISSUE TITLE
关于掉绑问题

### ISSUE THREAD

**Issue by weilai5201314** [Le-niao/Yunzai-Bot#660]
- 最近很多群友的cookie都会无缘无故的掉绑，发送`#体力`时出现`请先配置公共ck`，有的cookie甚至就绑定了两三个星期就突然失效了。
- 虽然说重新复制一次上一次的cookie再发一次就好了。但是掉的人数实在是有点多。
- 而且重启过机器人，基本上每天重启一次，但是每天都会出现。

**Comment by weilai5201314** [comment]
- 附一张图，一天就掉了很多，这些全都是已经绑过cookie的，还有些人因为不太会用机器人，掉绑了没重绑。
![88B62FFA78535B7E3E7779B9927EC712](https://user-images.githubusercontent.com/99032101/193417998-5743df74-ec6e-4032-8822-416da7d2dc0e.jpg)

**Comment by weilai5201314** [comment]
### 关于掉绑的后续跟进
- 因为很多群友不太会用，掉绑之后就会一直胡乱发送指令，他本人无法查询，但是其他人却可以代查，代查之后，机器人又恢复了。
- 还有的群友在掉绑之后，重新发送了上一次cookie，提示绑定成功，cookie没失效，结果依旧不能查询，会显示`配置公共ck`这样的提示语。
- 然后还在持续的掉绑cookie，每天都重启和更新机器人。
![96F927F3C066C650893614B9D95CBC37](https://user-images.githubusercontent.com/99032101/193463145-245eb618-50d0-49d9-b73c-05a8bb827400.jpg)
![1C0904D80041E5477EFAAB73BAC3B72C](https://user-images.githubusercontent.com/99032101/193463205-bacf64b5-bf17-4f59-80c6-d91bcb601daa.jpg)
![38C9E7063E841577B1D849F2E6CD9238](https://user-images.githubusercontent.com/99032101/193463211-f213363e-aa19-4b89-9498-407fd07cfd93.jpg)

**Comment by Le-niao** [comment]
配置下公共ck
