### ISSUE TITLE
更新报错如何解决

### ISSUE THREAD

**Issue by 200780381** [Le-niao/Yunzai-Bot#661]
[YzBot][22:01:18.823][MARK] [更新][updateAll][米忽悠表情包(星星)] #全部更新
0|Yunzai-Bot  | fatal: not a git repository (or any of the parent directories): .git
0|Yunzai-Bot  | [YzBot][22:01:18.903][ERRO] [更新][updateAll]
0|Yunzai-Bot  | [YzBot][22:01:18.903][ERRO] Error: Command failed: git rev-parse --short HEAD
0|Yunzai-Bot  | fatal: not a git repository (or any of the parent directories): .git
0|Yunzai-Bot  |     at checkExecSyncError (node:child_process:871:11)
0|Yunzai-Bot  |     at execSync (node:child_process:943:15)
0|Yunzai-Bot  |     at update.getcommitId (file:///Y:/Yunzai-Bot/plugins/other/update.js:151:26)
0|Yunzai-Bot  |     at update.runUpdate (file:///Y:/Yunzai-Bot/plugins/other/update.js:114:35)
0|Yunzai-Bot  |     at update.updateAll (file:///Y:/Yunzai-Bot/plugins/other/update.js:208:16)
0|Yunzai-Bot  |     at PluginsLoader.deal (file:///Y:/Yunzai-Bot/lib/plugins/loader.js:244:55)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Le-niao** [comment]
git clone的才可能更新
