### ISSUE TITLE
puppeteer Chormium启动失败

### ISSUE THREAD

**Issue by ChthollyWn** [Le-niao/Yunzai-Bot#663]
本来一切正常，今天早上突然就报了这个错误，之前issue里的方法都试过了，还是没有解决，求大佬帮忙
![image](https://user-images.githubusercontent.com/85938618/193436993-d2b2797a-dcb0-473d-9f38-8cb0f757e797.png)

**Comment by bule7756** [comment]
我也是这种情况，无语了

**Comment by ChthollyWn** [comment]
已解决，参考文章https://blog.csdn.net/snowin1994/article/details/78790182
