### ISSUE TITLE
关于抽卡记录的2个BUG

### ISSUE THREAD

**Issue by CurKay** [Le-niao/Yunzai-Bot#666]
这边反馈2个关于抽卡记录的bug。
1.导入抽卡记录，新手池会丢失的问题，这个可能是新手池忘了还是不打算给新手池做呢。
2.有个人发导出记录一直没反应，看了日志发现是302.json找不到文件或者目录，后来才想起来这个人已经很久没抽武器池了，这应该算是bug吧。因为没有抽武器池，所以武器池没有生成json，然后云崽找不到文件。所以就一直报错。
![I5OQ}6%3B(S7PN%PV1KMRAV](https://user-images.githubusercontent.com/46318903/193458994-f4025c82-f29b-4383-b983-671130480579.png)

**Comment by Le-niao** [comment]
新手池没有
