### ISSUE TITLE
关于公共ck和掉绑问题

### ISSUE THREAD

**Issue by weilai5201314** [Le-niao/Yunzai-Bot#669]
**在使用了#660 的解决办法：配置公共ck之后，发现了新的问题**
- 公共查询可以查看类似`#探索 #深渊`这样的信息，但是不能查看`#体力`，而群友一般查询的都是体力，所以配置公共ck不能缓解问题。
- 昨晚偶然发现一个好友在`/Yunzai-Bot/data/MysCookie`里面的`xxx.yaml`文件消失了，所以导致她需要重新绑定cookie，确认过她没有`删除ck`且cookie有效。其他失效人员的yaml目前没确认。

- 附配置了公共ck之后，查体力无效
![30B14A9C9E3D97DCBBE5CC78A154DE22](https://user-images.githubusercontent.com/99032101/193499261-061483a0-f375-4b1a-91be-e2a647cd1eb4.jpg)

**Comment by bling-yshs** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/557#issuecomment-1241999125
我之前也见过类似的，不过和你的情况稍微有点不同，我是每天签到的时候都会发现掉cookie了，但是cookie并没有失效，然后我开了AOF就没有出现过掉cookie的情况了

**Comment by weilai5201314** [comment]
> 

我也是昨晚，她来找我说ck没了，我就去yaml文件堆里面找她的qq.yaml给她发cookie，发现找不到她的yaml才发现的。

**Comment by lateautumn233** [comment]
好像可以更简单
redis-server --save 900 1 --save 300 10 --daemonize yes --appendonly yes --ignore-warnings ARM64-COW-BUG

**Comment by weilai5201314** [comment]
- 已经修改`redis.conf`开启AOF持久化，还在观察在开启AOF之后，重新绑定的人是否再次掉绑.
- 目前已确认，cookie掉绑之后，在`Yunzai-Bot/data/MysCookie`文件夹中的`qq.yaml`文件会消失，已确认三人。
