### ISSUE TITLE
无法输入ticket

### ISSUE THREAD

**Issue by wzwcc** [Le-niao/Yunzai-Bot#675]
![image](https://user-images.githubusercontent.com/76573126/193706521-a102172e-e87e-4625-b115-aca25289fcb4.png)
按道理有下面这一行 我直接卡住了 没这一行
![image](https://user-images.githubusercontent.com/76573126/193706567-483bfcb4-a3a3-4d4f-8480-129ff5c413bb.png)

**Comment by wzwcc** [comment]
扫码登录是可以的 但是不能用node app启动 用npm start才能扫码 但是npm start无法交互用户数据

**Comment by Le-niao** [comment]
先`node app`启动 登录成功后再`npm start`后台运行
