### ISSUE TITLE
什么问题？

### ISSUE THREAD

**Issue by ShengXi2000** [Le-niao/Yunzai-Bot#676]
![image](https://user-images.githubusercontent.com/83119504/193792622-59eea3d6-e060-4750-89d8-3cb18af654ac.png)

**Comment by anshifa958** [comment]
> ![image](https://user-images.githubusercontent.com/83119504/193792622-59eea3d6-e060-4750-89d8-3cb18af654ac.png)

看一下#415

**Comment by Le-niao** [comment]
装下chromium扩展
