### ISSUE TITLE
更新命令连接失败

### ISSUE THREAD

**Issue by Dr-WeiAL** [Le-niao/Yunzai-Bot#684]
![image](https://user-images.githubusercontent.com/47446553/194537060-463ce5be-2389-49f4-9808-d7e2bf660792.png)
![image](https://user-images.githubusercontent.com/47446553/194537079-bf336c46-c1f2-416f-b367-023c9550e4f7.png)
很怪，放机器人的机子能打开github，但发送更新命令就提示更新失败

**Comment by Le-niao** [comment]
连不上github 可以换成gitee试下
