### ISSUE TITLE
[功能请求] 主人能够通过和BOT私聊，向其他群聊发送维护公告或消息通知吗？

### ISSUE THREAD

**Issue by B1ackSand** [Le-niao/Yunzai-Bot#694]
查了下issue好像也没人提到这个功能，因为有时可能要重启云服务器，暂停BOT进行维护、加插件等等操作，希望能通过BOT向其他群聊发送消息，比如：
私聊界面：
+ **#群发公告 BOT由于进行维护，暂停xxx小时。**
+ **#群发消息 BOT今日维护，暂停服务一日。**
等等之类的。

我看了readme功能说明、还有issue里面似乎没有提到类似的功能，如果有的话希望大佬们指明。

**Comment by mofan1994** [comment]
windoge-plugin和Yenai-Plugin有提供此类功能，但是群发消息小心触发风控。

**Comment by B1ackSand** [comment]
> windoge-plugin和Yenai-Plugin有提供此类功能，但是群发消息小心触发风控。

感谢，我去查看下他们的插件。
