### ISSUE TITLE
求签到验证码失败解决方案

### ISSUE THREAD

**Issue by whereischina** [Le-niao/Yunzai-Bot#699]
![IMG_20221011_120241](https://user-images.githubusercontent.com/89396931/194994522-66d0722f-d7cb-4420-86fb-7c79ec659b8e.jpg)
问题如图，求解决方案

**Comment by chenshi1324** [comment]
方案就是手动签到

**Comment by ctrlcvs** [comment]
> 方案就是手动签到

大佬付费签到可以吗

**Comment by Le-niao** [comment]
可以试下换ip
