### ISSUE TITLE
centos7 ”node app“出现错误

### ISSUE THREAD

**Issue by misaka10843** [Le-niao/Yunzai-Bot#7]
本人使用centos7 node v12.16.3/v10.24.1搭建
但是使用时出现了下面的问题
（ v12.16.3的问题，似乎是版本过高的问题）

![屏幕截图 2021-11-29 112952](https://user-images.githubusercontent.com/69132853/143804525-ad60f775-0597-4b7e-b875-e7b6948eb71a.png)

所以本人就把版本换成了v10.24.1出现了此问题

![屏幕截图 2021-11-29 112649](https://user-images.githubusercontent.com/69132853/143804545-7589cb12-1f18-4e17-a6c2-cf6921481330.png)
请问如何修复此问题？
（cnpm等一系列操作安装都是按照#3的流程走的）

**Comment by Le-niao** [comment]
升级node吧 node版本最多v14

**Comment by misaka10843** [comment]
已解决qwq
开始用v12的时候出现错误搜了一下是说什么版本过高，所以就换了个低版本qwq
