### ISSUE TITLE
关于今日素材

### ISSUE THREAD

**Issue by XiaoFuOS** [Le-niao/Yunzai-Bot#70]
能不能改成可显示全部的角色和武器啊？武器没往角色身上戴就看不见。还有考虑一下周三素材，周四素材之类的，可以往后看，也能提前准备树脂

**Comment by chenchenriver** [comment]
你身上不戴米游社是查不到你有这个武器的，不可能实现这个功能。建议你把需要拉的武器都装备在任意角色上

**Comment by XiaoFuOS** [comment]
> 你身上不戴米游社是查不到你有这个武器的，不可能实现这个功能。建议你把需要拉的武器都装备在任意角色上

我的意思是，这个功能可以考虑不检查cookie。类似于[Adachi-BOT](https://github.com/Arondight/Adachi-BOT)的今日素材功能，这种可以查看任一天的素材
![%`ZTFDPR0OWU_EF77%RKP{Q](https://user-images.githubusercontent.com/103229747/163293806-3e3302fd-1d75-4c15-ad2e-170c0e1dbe6f.gif)

**Comment by zhangjy1318** [comment]
为什么我输入今日素材他没有反应呢
