### ISSUE TITLE
运行一段时间后会莫名掉线

### ISSUE THREAD

**Issue by HYTT0510** [Le-niao/Yunzai-Bot#71]
看了一下日志提示这个，需要重启才行
09:10:00 ApiRejection { code: -60, message: 'client not online' }

**Comment by Le-niao** [comment]
可能是掉线，看不出是什么问题

**Comment by HYTT0510** [comment]
![image](https://user-images.githubusercontent.com/46914653/163557934-cd7d94e3-0edc-4aa5-b0d1-480c1ec0d92a.png)
大佬看下error日志有无思路

**Comment by Le-niao** [comment]
token过期了吧，你试下密码登录

**Comment by HYTT0510** [comment]
重新npm start是可以的   就是过段时间会出现这种情况

**Comment by 741243716** [comment]
> 重新npm start是可以的 就是过段时间会出现这种情况

我也是一样的情况很奇怪了
