### ISSUE TITLE
图鉴与xiaoyao图鉴冲突

### ISSUE THREAD

**Issue by shilianmalaxiangguo** [Le-niao/Yunzai-Bot#710]
当逍遥插件设置【图鉴匹配开启】
效果为【无需图鉴结尾】
发送【#西风剑】会失效

必须要发送【#西风剑图鉴】才能生效

请问这是算bug吗

**Comment by lgyseven** [comment]
这个应该小问题，除了#角色，其他都带上图鉴后缀也可以，我觉得这样还挺规范

**Comment by ctrlcvs** [comment]
图鉴匹配开启的话，图鉴数据只匹配图鉴结尾的消息，关闭则需要#开头 这个并不是bug，在设置中也有说明的

> 当逍遥插件设置【图鉴匹配开启】 效果为【无需图鉴结尾】 发送【#西风剑】会失效
> 
> 必须要发送【#西风剑图鉴】才能生效
> 
> 请问这是算bug吗

**Comment by shilianmalaxiangguo** [comment]
> 图鉴匹配开启的话，图鉴数据只匹配图鉴结尾的消息，关闭则需要#开头 这个并不是bug，在设置中也有说明的
> 
> > 当逍遥插件设置【图鉴匹配开启】 效果为【无需图鉴结尾】 发送【#西风剑】会失效
> > 必须要发送【#西风剑图鉴】才能生效
> > 请问这是算bug吗

emmmm.但是在其他的群里这样确实是可以的
![西风剑](https://i.ibb.co/zfXZNh5/Snipaste-2022-10-14-16-28-21.png)

**Comment by ctrlcvs** [comment]
> > 图鉴匹配开启的话，图鉴数据只匹配图鉴结尾的消息，关闭则需要#开头 这个并不是bug，在设置中也有说明的
> > > 当逍遥插件设置【图鉴匹配开启】 效果为【无需图鉴结尾】 发送【#西风剑】会失效
> > > 必须要发送【#西风剑图鉴】才能生效
> > > 请问这是算bug吗
> 
> emmmm.但是在其他的群里这样确实是可以的 ![西风剑](https://camo.githubusercontent.com/c8bef2b134c8f0b6ddb9fa9e70c1a290c70abd55d7cb828bef2ac1b380f9b2ea/68747470733a2f2f692e6962622e636f2f7a66585a4e68352f536e6970617374652d323032322d31302d31342d31362d32382d32312e706e67)

你把图鉴匹配关了 ，然后就可以通过#触发了，别的群可以就是设置问题呗

**Comment by shilianmalaxiangguo** [comment]
> > > 图鉴匹配开启的话，图鉴数据只匹配图鉴结尾的消息，关闭则需要#开头 这个并不是bug，在设置中也有说明的
> > > > 当逍遥插件设置【图鉴匹配开启】 效果为【无需图鉴结尾】 发送【#西风剑】会失效
> > > > 必须要发送【#西风剑图鉴】才能生效
> > > > 请问这是算bug吗
> > 
> > 
> > emmmm.但是在其他的群里这样确实是可以的 ![西风剑](https://camo.githubusercontent.com/c8bef2b134c8f0b6ddb9fa9e70c1a290c70abd55d7cb828bef2ac1b380f9b2ea/68747470733a2f2f692e6962622e636f2f7a66585a4e68352f536e6970617374652d323032322d31302d31342d31362d32382d32312e706e67)
> 
> 你把图鉴匹配关了 ，然后就可以通过#触发了，别的群可以就是设置问题呗

谢谢大佬,大佬硬邦邦.
