### ISSUE TITLE
请问puppeteer Chromium 启动失败

### ISSUE THREAD

**Issue by wooodswu** [Le-niao/Yunzai-Bot#713]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/87766834/195978198-720ce9b3-57f5-4f3c-bf12-d4261a73c31d.png">
Debian服务器
<img width="375" alt="image" src="https://user-images.githubusercontent.com/87766834/195978239-42f347b1-1b96-4ef8-9e5e-21230d5da9a9.png">
之前我参考了之前一个提问的答案 还是不行
<img width="569" alt="image" src="https://user-images.githubusercontent.com/87766834/195978288-e51204e8-8d8c-4b89-aabf-be3c34689e18.png">

**Comment by wooodswu** [comment]
sudo apt install libgbm-dev libasound2-dev -y
这个依赖也安装了，也没什么用。。。
<img width="566" alt="image" src="https://user-images.githubusercontent.com/87766834/195978673-13460f74-4dc1-4d22-9528-04e0f3169972.png">
任然报错

**Comment by anshifa958** [comment]
> sudo apt install libgbm-dev libasound2-dev -y 这个依赖也安装了，也没什么用。。。 <img alt="image" width="566" src="https://user-images.githubusercontent.com/87766834/195978673-13460f74-4dc1-4d22-9528-04e0f3169972.png"> 任然报错

它不是提示你是libnss3的问题嘛，实在不行把#415的那个命令执行一下，看还报不报错

**Comment by ececleon** [comment]
sudo apt install alsa-utils libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev

**Comment by Le-niao** [comment]
装下chromium扩展
