### ISSUE TITLE
深渊无伤时，#深渊   报错。

### ISSUE THREAD

**Issue by backunderstar** [Le-niao/Yunzai-Bot#716]
示例：
米游社截图：
![米游社截图](https://user-images.githubusercontent.com/89375248/196018271-3000875e-adb5-496c-86bb-6002a20e6202.png)
使用#深渊 报错截图：
![报错截图](https://user-images.githubusercontent.com/89375248/196018321-d9e87bd8-fd47-44d2-96b0-726c05814a4e.png)
找不到值。
但是#+uid时显示有深渊这项不报错。
![0BB7712DA91428321C707A4CC8F66659](https://user-images.githubusercontent.com/89375248/196018422-d45cdde0-c84c-4db4-87c1-57ad9295103a.jpg)
推测是无伤的会这样，其他有伤账号正常。

**Comment by kikasyou** [comment]
装个miao plugin，试试#上传深渊
