### ISSUE TITLE
v3中有无命令总览js文件

### ISSUE THREAD

**Issue by CICILC** [Le-niao/Yunzai-Bot#719]
v2版本有将全部指令都展示出来的总揽文件command.js v3同样的文件在哪里找的到呢
![Screenshot_20221017-014547_QQ](https://user-images.githubusercontent.com/115946224/196050321-89f945ca-a288-436a-a60b-8894ebed7d86.jpg)

**Comment by yin52** [comment]
/plugins/genshin/README.md

**Comment by Le-niao** [comment]
没有
