### ISSUE TITLE
关于再次出现自动签到失败

### ISSUE THREAD

**Issue by ldcivan** [Le-niao/Yunzai-Bot#724]
似乎再次出现了大面积的自动签到失败，理由是弹出了验证码（验证码失败）。

**Comment by Le-niao** [comment]
就是验证码失败

**Comment by liang-shui** [comment]
> 我有一个签到成功，其他都失败了。提示验证码失败次数过多。

你这个成功的应该是uid本人在米游社手动签到了，这样机器人就显示了签到成功，实际上机器人还是签到不了。

**Comment by regaliaf** [comment]
> > 我有一个签到成功，其他都失败了。提示验证码失败次数过多。
> 
> 你这个成功的应该是uid本人在米游社手动签到了，这样机器人就显示了签到成功，实际上机器人还是签到不了。

那现在有什么解决办法么？还是说签到目前就废了？
