### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by Richo-lu** [Le-niao/Yunzai-Bot#728]
为了开启AOF持久化，把appendonly no改成appendonly yes了，结果签到开始报失败，改回no之后签到也还是失败，不知该如何解决
![QQ图片20221018122915](https://user-images.githubusercontent.com/71910448/196335798-d6b3e7e6-8b00-41d2-8ff0-9eea6f45e661.png)
![QQ图片20221018123412](https://user-images.githubusercontent.com/71910448/196336272-e103b87c-65c0-40e9-82b3-88311a5d6d42.png)

**Comment by sagiriyo** [comment]
+1  有的能签有的不能签

**Comment by Richo-lu** [comment]
> 



> +1 有的能签有的不能签

能签的是自己在米游社签过了的，再用机器人签就会显示已签到

**Comment by sagiriyo** [comment]
> > +1 有的能签有的不能签
> 
> 能签的是自己在米游社签过了的，再用机器人签就会显示已签到

自己签到要过验证   大概率是bot不能自动过验证导致失败了

**Comment by earthjasonlin** [comment]
今天开始有的，米游社不行hoyolab可以

**Comment by uyaddayu** [comment]
为啥又签到不了了，我用米游社试了下，也会出验证码，但是可以频繁点击那个签到跳过验证码机制，bot能实现这一点吗

**Comment by ctrlcvs** [comment]
> 为啥又签到不了了，我用米游社试了下，也会出验证码，但是可以频繁点击那个签到跳过验证码机制，bot能实现这一点吗

跟这个没有关系，跟ua也没有关系 跟你的ip有关系，其次的话你签到出现验证码 然后bot停4天签到后又会恢复，但是恢复后同一个IP签到账号多还是一样会出现验证码的，签到接口判定你IP为脚本操作了你怎么重试都不行的

**Comment by pkuislm** [comment]
在出现验证码的时候私信用户一个滑动条验证的链接可行吗？

**Comment by ctrlcvs** [comment]
> 可行，目前有人在折腾这块，进展缓慢。。
