### ISSUE TITLE
有没有办法开启米游社签到但是关闭云原神签到

### ISSUE THREAD

**Issue by izaynpan** [Le-niao/Yunzai-Bot#729]
没找到在哪设置或者修改，不知道可不可以实现

**Comment by ctrlcvs** [comment]
xiaoyao-cvs-plugin/config/
在这个目录下面设置，设置后需要重启

> 没找到在哪设置或者修改，不知道可不可以实现

**Comment by izaynpan** [comment]
> 

谢谢，才知道是xiaoyao插件的😂
