### ISSUE TITLE
机器人信息莫名其妙自动撤回（非抽卡

### ISSUE THREAD

**Issue by shunzi2006** [Le-niao/Yunzai-Bot#732]
![Screenshot_2022-10-18-23-25-00-736_com.tencent.mobileqq-edit.jpg](https://user-images.githubusercontent.com/107313064/196474123-d8a9892c-68b4-49b5-bb29-6953dc39db6e.jpg)

**Comment by lgyseven** [comment]
这不是喵喵插件的嘛

**Comment by Le-niao** [comment]
十连模拟抽卡才会撤回，或者你其他功能撤回

**Comment by shunzi2006** [comment]
> 十连模拟抽卡才会撤回，或者你其他功能撤回
我这边目前是不管发什么信息，都会被撤回
