### ISSUE TITLE
建议增加/可修改米游社签到失败次数

### ISSUE THREAD

**Issue by lin-junliang** [Le-niao/Yunzai-Bot#734]
目前是失败5次后就会停止，万一后面的人不需要验证码的话就错过了。
1、希望可以改成全部人都尝试签到
2、签到完成后把失败的QQ号和失败原因发到主人QQ（这个在运行里可以看到）

3、在上面的基础上，如果能直接把签到失败的消息发送到这个QQ号本人的账号上的话就最好了
“1”能做到的话至少我可以自行通知到签到失败的人，“2”主要是方便导出信息，“3”就是全自动了

**Comment by Le-niao** [comment]
不改
