### ISSUE TITLE
米游社接口请求失败，暂时无法查询

### ISSUE THREAD

**Issue by Shironaus** [Le-niao/Yunzai-Bot#735]
日志里一直报这个
 FetchError: request to https://bbs-api.mihoyo.com/post/wapi/getNewsList?gids=2&page_size=10&type=3 failed, reason: connect ETIMEDOUT 203.107.60.77:443

**Comment by Le-niao** [comment]
米游社接口请求失败

**Comment by JadeVane** [comment]
请问这个问题最后解决了吗，我现在也遇到了这个问题
