### ISSUE TITLE
docker映射错误，导致搭建出错

### ISSUE THREAD

**Issue by VsentCN** [Le-niao/Yunzai-Bot#74]
如题
- $PWD/Yunzai/config.js:/app/Yunzai-Bot/config/config.js
路径映射有误

**Comment by Xm798** [comment]
后面的容器内路径不要动，前面的路径修改为你自己 config.js 的实际路径。如果就在当前目录下，就使用 $PWD/config.js:/app/Yunzai-Bot/config/config.js

**Comment by VsentCN** [comment]
> 后面的容器内路径不要动，前面的路径修改为你自己 config.js 的实际路径。如果就在当前目录下，就使用 $PWD/config.js:/app/Yunzai-Bot/config/config.js

这个我知道，自己已经改过了

**Comment by Xm798** [comment]
> > 后面的容器内路径不要动，前面的路径修改为你自己 config.js 的实际路径。如果就在当前目录下，就使用 $PWD/config.js:/app/Yunzai-Bot/config/config.js
> 
> 
> 
> 这个我知道，自己已经改过了

镜像启动还是本地构建？贴一下日志看一下？

**Comment by VsentCN** [comment]
> > > 后面的容器内路径不要动，前面的路径修改为你自己 config.js 的实际路径。如果就在当前目录下，就使用 $PWD/config.js:/app/Yunzai-Bot/config/config.js
> > 
> > 
> > 这个我知道，自己已经改过了
> 
> 镜像启动还是本地构建？贴一下日志看一下？

文件映射出错了，构建后出来的是config.js文件夹而不是文件，导致启动出错

**Comment by Xm798** [comment]
路径错误，检查本地文件路径。
见 docker [官方文档](https://docs.docker.com/storage/volumes/#create-and-manage-volumes) 和 StackOverflow [相关讨论](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume)。
> If you start a container with a volume that does not yet exist, Docker creates the volume for you.

**Comment by VsentCN** [comment]
>

> 

具体原因是因为项目目录不存在Yunzai/config,js这个文件，docker默认对不存在的目录或文件创建的是文件夹，导致创建了config.js这个文件夹而不是文件。

**Comment by Xm798** [comment]
> 具体原因是因为项目目录不存在Yunzai/config,js这个文件，docker默认对不存在的目录或文件创建的是文件夹，导致创建了config.js这个文件夹而不是文件。

是的呀，所以说要修改前面的文件路径为你的配置文件路径。docker 映射不存在的文件就会创建文件夹。 
而且本地的映射目录和这个项目关系不大，Yunzai，data和logs这几个目录应该是由使用者创建的，我写的docker-compose文件这样用了，具体可以根据使用者的习惯调整。

**Comment by Xm798** [comment]
使用docker不需要拉取项目到本地，用镜像的话只要有docker-compose.yaml 和 config.js 就可以启动，本地构建的话还需要再加上 docker-entrypoint.sh 和 Dockerfile 两个文件。

**Comment by VsentCN** [comment]
> 

这样啊，我是本地搭建的，其实对普通用户而言项目其他可以映射的无非就插件目录，加上之后主要是方便小白用户用Docker启动

**Comment by Xm798** [comment]
docker 是我自用的，因为我自己的服务器上还有很多其他的项目，所以不希望各种项目之间的环境互相干扰，而且 docker 也不用搭建环境，开箱即用，顺便加上了每次重启自动拉取最新项目并更新依赖，更新只需要重启容器。写了 docker 部署测试没问题之后就 PR 上来了，也没写教程（因为感觉会用 docker 的人应该都可以看懂…吧）。映射的话就是映射 redis 的目录、 Yunzai 的 data 目录和插件目录再加上配置文件，个人感觉 docker 确实很适合用户快速搭建项目。

**Comment by VsentCN** [comment]
> docker 是我自用的，因为我自己的服务器上还有很多其他的项目，所以不希望各种项目之间的环境互相干扰，而且 docker 也不用搭建环境，开箱即用，顺便加上了每次重启自动拉取最新项目并更新依赖，更新只需要重启容器。写了 docker 部署测试没问题之后就 PR 上来了，也没写教程（因为感觉会用 docker 的人应该都可以看懂…吧）。映射的话就是映射 redis 的目录、 Yunzai 的 data 目录和插件目录再加上配置文件，个人感觉 docker 确实很适合用户快速搭建项目。

这样啊，了解了
