### ISSUE TITLE
获取网络图片并发送时会在Yunzai-Bot/data缓存一个文件问题

### ISSUE THREAD

**Issue by xianxincoder** [Le-niao/Yunzai-Bot#741]
获取网络图片并发送消息后会在Yunzai-Bot/data生成一个缓存文件
插件代码这边没有做任何处理，应该如何处理才能让缓存的文件放到data指定的目录下呢？目前这样直接放在data目录下会显得很乱，不知道是不是oicq生成的，看着云崽里没有相关代码
![image](https://user-images.githubusercontent.com/109654219/197151577-e5ae3af1-dba7-498a-bf6c-04ed028ac56d.png)

**Comment by Le-niao** [comment]
oicq生成的图片缓存

**Comment by xianxincoder** [comment]
oicq有没有开放指定路径呢，比如给放到data/cache 里 云崽使用者可以统一删除

**Comment by xianxincoder** [comment]
@Le-niao
