### ISSUE TITLE
更新产生本地冲突，失败及重启机器人后出现插件报错

### ISSUE THREAD

**Issue by CeciliaAki** [Le-niao/Yunzai-Bot#744]
问题1：更新出现本地冲突失败
![61L `2HZP~N%` WO4LSSQ T](https://user-images.githubusercontent.com/103917391/197329987-354c5eea-5690-4ca7-b22b-10e9387e5d1b.png)

问题2：重启机器人后发现报错
![image](https://user-images.githubusercontent.com/103917391/197330618-c1d45b72-58b4-4624-b0ec-66076d2d6425.png)

备注：在聊天框使用“#更新”和“#强制更新”指令后，再在控制台输入代码git pull显示已经更新到最新版本

请问各位大佬这样的问题如何解决

**Comment by Lactococcuslactis** [comment]
这个是网络问题 走代理强制更新吧 git config --global url."https://gh.api.99988866.xyz/https://github.com".insteadOf https://github.com

**Comment by CeciliaAki** [comment]
> 这个是网络问题 走代理强制更新吧 git config --global url."[https://gh.api.99988866.xyz/https://github.com".insteadOf](https://gh.api.99988866.xyz/https://github.com%22.insteadOf) https://github.com

大佬好，使用了你给出的代码后，git pull指令有反应（虽然我并不能看懂是否成功），但是enka插件仍然在重启的时候报错，还想请问一下，要怎么修复这个enka插件的api无法导入的问题？这个错误导致在使用喵喵插件的时候，无法获取最新的角色面板了。
希望大佬指教，感谢！

代码图如下
![EOXMTP6N}U8RCDT}C3UCQVR](https://user-images.githubusercontent.com/103917391/198534742-f020cd4d-255d-4a85-a4a5-b714ced2fd18.jpg)

**Comment by CeciliaAki** [comment]
> 这个是网络问题 走代理强制更新吧 git config --global url."[https://gh.api.99988866.xyz/https://github.com".insteadOf](https://gh.api.99988866.xyz/https://github.com%22.insteadOf) https://github.com

已通过搜索历史issue解决问题，仍然感谢大佬之前的回答
