### ISSUE TITLE
#原石功能报错

### ISSUE THREAD

**Issue by HeiCreeper** [Le-niao/Yunzai-Bot#752]
[YzBot][19:38:04.786][MARK] puppeteer Chromium 启动中。。
[YzBot][19:38:04.950][MARK] puppeteer Chromium 启动成功
[YzBot][19:38:34.979][ERRO] 图片生成失败:ledgerCount:TimeoutError: Navigation ti
meout of 30000 ms exceeded
[YzBot][19:38:35.095][ERRO] Chromium实例关闭或崩溃！

**Comment by Le-niao** [comment]
可能原石数据出错导出截图失败
