### ISSUE TITLE
机器人重启后，就不能返回图片了。日志上是正常的，

### ISSUE THREAD

**Issue by lingo76** [Le-niao/Yunzai-Bot#753]

**Comment by lingo76** [comment]
![image](https://user-images.githubusercontent.com/93309074/197430004-100e37f1-ae09-49da-81cb-aff7547ad972.png)
![image](https://user-images.githubusercontent.com/93309074/197430050-553130b6-929e-40e8-b25a-d5a3b43422ea.png)

**Comment by fhl-jj** [comment]
我也遇到这个情况了，生成图片成功，但是没有发送，不过本地有的图片可以发送，看了yunzai日志貌似是：【Chromium实例关闭或崩溃！】蹲个解决方法，谢谢大佬

**Comment by lingo76** [comment]
> 我也遇到这个情况了，生成图片成功，但是没有发送，不过本地有的图片可以发送，看了yunzai日志貌似是：【Chromium实例关闭或崩溃！】蹲个解决方法，谢谢大佬

这样的话，那直接覆盖安装 Chromium 。我去试试看

**Comment by lingo76** [comment]
![image](https://user-images.githubusercontent.com/93309074/197464881-e48c6d36-5c51-47a3-81b5-e2150e3de88b.png)
chromium 启动成功了，不是这个问题

**Comment by fhl-jj** [comment]
> 你会发现机器人并不会回应你的任何指令，原因是容器里的redis服务并不会开启自启，你需要在npm启动前先输入启动redis的命令，这两条命令就是容器重启后重新开启项目的步骤：
> 
> redis-server --save 900 1 --save 300 10 --daemonize yes
> 
> 作者：zh8416 https://www.bilibili.com/read/cv16393194 出处：bilibili
> 
> 我的是 redis 启动命令错了，用这个命令启动就正常了。

好的，谢谢，这就去试试
