### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录

### ISSUE THREAD

**Issue by CUZNIL** [Le-niao/Yunzai-Bot#760]
尝试了所有设备类型，依旧无法登录
iPad
![D0JSS Q3%0QYOJ17WEQ`GW4](https://user-images.githubusercontent.com/76582404/197517787-cb4acf1c-1bf0-4555-a6c6-7db48c87ff78.jpg)
安卓手表
![O9 CLLG$GNFU(7OJJ{X7V S](https://user-images.githubusercontent.com/76582404/197517819-79b88951-fd71-4434-ba8a-880f65ce9a40.jpg)
aPad
![_5PPCD73IYPXRLU~X 37M_S](https://user-images.githubusercontent.com/76582404/197517852-6d2490fe-f14e-4862-bfd5-f8853a4b862e.jpg)
安卓手机
![ZYRKJHS4R@5_P8ATAQB) $K](https://user-images.githubusercontent.com/76582404/197517871-5c2de487-aff1-404a-b31a-bf518b36d2ea.jpg)
MacOS
![6Y3 J$8WL~6G5TARR(EPHP1](https://user-images.githubusercontent.com/76582404/197517900-73a3fe7c-eee7-4ce3-bd3c-11ad4616106e.jpg)

**Comment by CUZNIL** [comment]
![N XVF1J0C{HIGD0ND){PLP](https://user-images.githubusercontent.com/76582404/197519421-5b18c59e-de7a-4e92-80e3-5b8b7bd3d5b4.gif)
![image](https://user-images.githubusercontent.com/76582404/197519491-ce73a07e-fc64-49df-a497-f952175d0e67.png)
根据群友的意见已经解决，如有类似问题可以参考

**Comment by yelinlan** [comment]
不起作用

**Comment by yelinlan** [comment]
我从原先安卓选了ipad就好了。

**Comment by CUZNIL** [comment]
> 我从原先安卓选了ipad就好了。

我最开始也是这么解决的，之后会出现我说的这个情况，五个设备都不行

**Comment by yelinlan** [comment]
但是我改了，json文件里的参数，还是依旧。只能先这样了。

**Comment by Qiyue555** [comment]
改完直接输入node App，可以正常使用

**Comment by zhuba-Ahhh** [comment]
修改IMEI后 npm run login 成功解决问题
