### ISSUE TITLE
大大，今晚登陆云崽提示QQ版本低

### ISSUE THREAD

**Issue by wuhuan666** [Le-niao/Yunzai-Bot#763]
![image](https://user-images.githubusercontent.com/54826754/197572353-8ba29230-91a0-41fb-bae7-4d4ebe91fca3.png)
有解决办法吗？

**Comment by ywstratus** [comment]
我也是，凌晨重启发现没有成功，上去一看提示版本过低

**Comment by Sayu0000** [comment]
我裂开，我也是这个问题。设备全试了一遍都没得用

**Comment by Algar233** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/760
