### ISSUE TITLE
增加从authkey获取抽卡记录的功能

### ISSUE THREAD

**Issue by forchannot** [Le-niao/Yunzai-Bot#765]
参考小派蒙的https://github.com/CMHopeSunshine/LittlePaimon/commit/b6f603896b4449d0c81cc56736867c5c9253fbb8                            LittlePaimon/plugins/Paimon_Gacha_Log/data_source.py

**Comment by ctrlcvs** [comment]
需要用到stoken 然后的话这个功能很早就有插件支持了

**Comment by forchannot** [comment]
> 需要用到stoken 然后的话这个功能很早就有插件支持了

请问下是哪个插件呢

**Comment by ctrlcvs** [comment]
> > 需要用到stoken 然后的话这个功能很早就有插件支持了
> 
> 请问下是哪个插件呢

xiaoyao-cvs-plugin

**Comment by forchannot** [comment]
好的，谢谢
