### ISSUE TITLE
提示QQ版本过低

### ISSUE THREAD

**Issue by xiaomingwa** [Le-niao/Yunzai-Bot#767]
盖亚！怎么搞哦各位大佬

**Comment by firfix** [comment]
修改Yunzai-Bot/config/config/qq.ymal里面的登录端重启可以解决。我原先用安卓端登录，最近拉取更新之后也出现这个问题，现在切换到ipad端能正常使用。

**Comment by xiaomingwa** [comment]
> 修改Yunzai-Bot/config/config/qq.ymal里面的登录端重启可以解决。我原先用安卓端登录，最近拉取更新之后也出现这个问题，现在切换到ipad端能正常使用。

不行emmm试过了

**Comment by youllor** [comment]
切扫码登录成功^-^

**Comment by xiaomingwa** [comment]
> 切扫码登录成功^-^

这个确实可以登上了，但是有时候过一天就掉线要求重新扫码了

**Comment by fsqhn** [comment]
我也是用安卓说版本过低，登陆失败。然后用ipad端就提示登陆设备有风险，要用手机号码登陆或改用常用设备登陆。头都快挠掉了。

**Comment by xiaomingwa** [comment]
> 我也是用安卓说版本过低，登陆失败。然后用ipad端就提示登陆设备有风险，要用手机号码登陆或改用常用设备登陆。头都快挠掉了。

可以

**Comment by fsqhn** [comment]
在服务器部署的，不在本地。用不了扫码登陆。

**Comment by xiaomingwa** [comment]
> 在服务器部署的，不在本地。用不了扫码登陆。

我是旧手机搭建的

**Comment by youllor** [comment]
> > 切扫码登录成功^-^
> 
> 这个确实可以登上了，但是有时候过一天就掉线要求重新扫码了

扫码登录几个小时后尝试重新密码登录成功，或许是账号风控被解除了。
