### ISSUE TITLE
发送cookie报错

### ISSUE THREAD

**Issue by small-potato-git** [Le-niao/Yunzai-Bot#771]
发送cookie报错，就单纯的发了一个cookie。
![68H7_4D 9VBAJI%(A2IB5KT](https://user-images.githubusercontent.com/45375162/197948934-ed170d1a-a6bc-43c4-866a-d209999df94a.png)
![JJHIN24G$FRUYZ6YY{HCV6G](https://user-images.githubusercontent.com/45375162/197948956-cf9b96f1-b6de-4a39-8d99-a406fb4174c8.png)

**Comment by small-potato-git** [comment]
ip没有被黑，签到，体力正常

**Comment by scalpelliu** [comment]
一样的问题，
![image](https://user-images.githubusercontent.com/48466547/198033584-6d006d43-eef2-4d2d-87d9-be5529520896.png)
cookie是国际服的，无痕模式、退出再次登录获取的cookie后台都会报这个错：`Invalid URL`  。QQ对话这边的表现就是发了cookie没有回应。

`0|Yunzai-Bot  | [YzBot][21:04:52.623][MARK] [用户绑定][bingCk][私聊][啊啊啊啊啊(1145141919810)] #绑定cookie
0|Yunzai-Bot  | [YzBot][21:04:52.896][ERRO] [用户绑定][bingCk]
0|Yunzai-Bot  | [YzBot][21:04:52.896][ERRO] TypeError [ERR_INVALID_URL]: Invalid URL
0|Yunzai-Bot  |     at new NodeError (node:internal/errors:372:5)
0|Yunzai-Bot  |     at URL.onParseError (node:internal/url:553:9)
0|Yunzai-Bot  |     at new URL (node:internal/url:629:5)
0|Yunzai-Bot  |     at new Request (file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/request.js:55:16)
0|Yunzai-Bot  |     at file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/index.js:51:19
0|Yunzai-Bot  |     at new Promise (<anonymous>)
0|Yunzai-Bot  |     at fetch (file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.2.6/node_modules/node-fetch/src/index.js:49:9)
0|Yunzai-Bot  |     at Function.getGameRole (file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/plugins/genshin/model/mys/MysUser.js:381:21)
0|Yunzai-Bot  |     at User.getrGameRoles (file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/plugins/genshin/model/user.js:154:26)
0|Yunzai-Bot  |     at User.checkCk (file:///C:/Users/Administrator/Downloads/Yunzai/V3-Yunzai/Yunzai-Bot/plugins/genshin/model/user.js:109:32)`

![image](https://user-images.githubusercontent.com/48466547/198034145-d9cc2120-e7be-464e-a7e9-e4a494366aae.png)
这个是登录了一段时间获取的cookie，退出再次登录获取的cookie也是`Invalid URL`这个报错。
以上。

**Comment by nian43** [comment]
我目前也出现了这个问题，官服发送正常，国际服绑定不了

**Comment by yoimiya-kokomi** [comment]
更新到yunzai最新版本

**Comment by lgyseven** [comment]
绑定Stoken失败，异常：undefined
绑定cookie失败：Login expired. Please log in again.
两种ck绑定都报错了

**Comment by ctrlcvs** [comment]
> 绑定Stoken失败，异常：undefined 绑定cookie失败：Login expired. Please log in again. 两种ck绑定都报错了

这是IP黑了，其次下次关于stoken的问题可以去图鉴plugin提。。
