### ISSUE TITLE
突然间qq版本过低

### ISSUE THREAD

**Issue by Quanxuecoding** [Le-niao/Yunzai-Bot#773]
一直以来正常使用，今晚更新了一下插件准备重启，结果突然qq版本过低；尝试换登陆方式，apad成功了一下，准备切后台走人，结果也不好使了；目前就是5种都不行了；；；怎么解决
![image](https://user-images.githubusercontent.com/110401866/198027711-837828ee-ce81-4621-bec6-66ba0caa807f.png)
![image](https://user-images.githubusercontent.com/110401866/198027773-5bddfb16-32a3-4c83-bcf4-e84f3b82c22d.png)

**Comment by Algar233** [comment]
https://github.com/Le-niao/Yunzai-Bot/issues/760
