### ISSUE TITLE
每天八点左右都会自动下线

### ISSUE THREAD

**Issue by nian43** [Le-niao/Yunzai-Bot#778]
![Screenshot_20221027-091547__01](https://user-images.githubusercontent.com/116774530/198170584-fa157793-e40e-4e38-85fd-0ed183da5fc2.jpg)
大佬们帮忙看看，这是怎么回事，每天八点都会自动下线，每次都要手动重启

**Comment by ctrlcvs** [comment]
lin-plugin的报错，盲猜是自动点赞
