### ISSUE TITLE
一直提示qq版本过低登录错误

### ISSUE THREAD

**Issue by Quadmension4** [Le-niao/Yunzai-Bot#782]
大概是10月26号晚上9点左右出现的版本过低，之后就一直登不上，尝试过#760以及其他#下的解决方法无果，换过其他的qq号也提示版本过低无法登录，请问有没有解决办法呢

**Comment by threeshui** [comment]
我也是昨天出现的这个问题，尝试过更改data/QQ/device，但没有解决，刚刚更换了一下可以正常登录的config文件夹已经成功解决，希望您可以尝试一下，我的过程是在本地搭建了一个环境，可以正常登录，然后把VPS上的config文件夹删除，将本地的config全部复制过去，然后就可以登录了。

**Comment by threeshui** [comment]
您好，我找到了解决方法：请先在本地搭建一个可以正常运行的yunzai，然后通过扫码登录，可以正常登录成功，这时候关掉机器人，将VPS上的yunzai-bot/config/config的qq.yaml中的密码设置为空，设备换成安卓手机，然后将本地的yunzai-bot/data/qq号下的token复制到VPS里的同样位置，就可以正常登录，这是一个替代方法。

**Comment by ArcF1sh** [comment]
我也碰到了这个问题
