### ISSUE TITLE
更新后无法正常使用

### ISSUE THREAD

**Issue by Msdyz123** [Le-niao/Yunzai-Bot#788]
如题，前天晚上执行了一下全部更新，更新成功，但是重启没有提示成功，看后台能够成功登陆bot，但是无法接受所有的指令，也没有日志输出，有没有大佬知道是什么问题啊，下图是关机重启的日志，依旧是能成功登陆但是没有加载任何插件，无日志输出，不接受任何指令
![Screenshot_2022-10-28-18-41-03-830_com termux](https://user-images.githubusercontent.com/107755459/198569927-3e563769-1194-46cc-ab56-b4abfb2c0ad1.jpg)

**Comment by Le-niao** [comment]
重启试试
