### ISSUE TITLE
更新后无法添加多个uid

### ISSUE THREAD

**Issue by geol** [Le-niao/Yunzai-Bot#789]
昨晚通过菜单执行更新，今天发现无法添加多个uid，重复尝试均无效。查看日志并没有出错提示。
另外，添加表情后，一重启主机，表情就消失了，但是查看data/face，文件还在。而且有出现添加表情一次没成功要多次才能添加上的情况。
#更新 由于断网后导致云崽掉线，然后再上线情况就很不对劲。拉取腾讯滑动验证，手动验证，粘贴验证token后画面就卡在那里了，另外一个验证也是在验证完毕后卡在那儿。后来没办法用了扫码登陆，也是扫完卡在那里。现在换成v2才正常上线。

**Comment by Le-niao** [comment]
测试正常可以添加多个uid
