### ISSUE TITLE
#原石 显示 “尚未配置，无法查询 配置教程：undefined”

### ISSUE THREAD

**Issue by bling-yshs** [Le-niao/Yunzai-Bot#79]
原谅我比较笨，用的 npm start ，所以不知道日志在哪看

![This is an image](https://raw.githubusercontent.com/bling-yshs/ys_tuchuang/main/Picgo/2022-04-16-18-16-22.jpg)

**Comment by Xm798** [comment]
config.js 里没有配置配置教程吧

**Comment by Le-niao** [comment]
更新重启一下就好
