### ISSUE TITLE
找不到ociq这个包怎么办

### ISSUE THREAD

**Issue by Atxoed** [Le-niao/Yunzai-Bot#8]
![O14RR3A0MDTL96V@D@MSS3Y](https://user-images.githubusercontent.com/95240922/143912254-13c0dda3-5cec-45dc-b03c-e9bc2410b68c.png)

**Comment by Le-niao** [comment]
升级Node.js

**Comment by Atxoed** [comment]
> 
可是我这已经是最新的16.13.0了呀

**Comment by Le-niao** [comment]
npm install 安装模块
