### ISSUE TITLE
查询体力会使用别人的cookie，没有用我自己的从而报错

### ISSUE THREAD

**Issue by Lactococcuslactis** [Le-niao/Yunzai-Bot#812]
```
[YzBot][00:07:42.951][INFO] recv from: [Private: 17*****42(friend)] #体力
[YzBot][00:07:43.001][MARK] [米游社查询][uid：85****768][使用已查询ck：15***3]
[YzBot][00:07:45.008][MARK] [米游社接口][dailyNote][85*****8] 1994ms
**[YzBot][00:07:45.011][DEBU] [米游社接口][请求参数] https://*******/genshin/api/dailyNote?role_id=8***68&server=os_asia {"headers":{"x-rpc-app_version":"2.9.0","x-rpc-client_type":"2","User-Agent":"Mozilla/5.0 (Linux; Android 12; Yz-5b2fd) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.73 Mobile Safari/537.36 miHoYoBBSOversea/2.9.0","Referer":"https://webstatic-sea.hoyolab.com","DS":"1667232463,454774,a5f7034313e04cc37a32e28a20a96ced","Cookie":"ltoken=qq*****W7g***CEpuKo6****OGC;ltuid=153****3;cookie_token=giNM*****5AXk; account_id=15******3; mi18nLang=zh-cn;"},"agent":null,"timeout":10000,"method":"get"}**
[YzBot][00:07:45.013][MARK] [mys接口报错]{"data":null,"message":"","retcode":10104,"api":"dailyNote"}，uid：8*******8
[YzBot][00:07:45.215][INFO] succeed to send: [Private(17******42)] 米游社接口报错，暂时无法查询：error
```

没有使用我对应的ituid 和ITtoken，我的cookie是正常绑定的，发送#我的ck，正常返回绑定的ck，#发送用户统计，发现我的ituid没有显示，重新新发送ck仍然不行，使用#刷新用户缓存 后正常工作了，用户统计也显示我的ck，可能是我的缓存被莫名其妙删除了？这种情况我今天碰到两次了，感觉是把自己的配置为公共ck有关，我只配置自己的ck为公共ck，自己的经常被删，其他的没有莫名其妙的掉

**Comment by ctrlcvs** [comment]
查询体力报错error大概率是遇到验证码了，建议上米游社看看

**Comment by Lactococcuslactis** [comment]
> 查询体力报错error大概率是遇到验证码了，建议上米游社看看

首先这是用了别人cookie查询我的体力，不是肯定会报错，其次这是国际服hoyolab，暂时还没加验证码

**Comment by yoimiya-kokomi** [comment]
理论上不会分配错误

这里日志输出的是ltuid（通行证id），所以和uid数字不一致是正常的
你可以发一下#我的ck，看下ck字段的ltuid是否是这个

可以通过 #ck 命令自检下ck状态

如果此ck登录失效或一直失败可以尝试退出hoyolab重新登录获取下ck重新绑定。以及如果此ck同时设置了公共ck，公共ck也同步更新下

**Comment by yoimiya-kokomi** [comment]
另，如果是日常使用的ck，建议不放到公共ck中，自己账号绑定此ck即可
目前的逻辑不会要求必须绑定公共ck了

**Comment by Lactococcuslactis** [comment]
> 理论上不会分配错误
> 
> 这里日志输出的是ltuid（通行证id），所以和uid数字不一致是正常的 你可以发一下#我的ck，看下ck字段的ltuid是否是这个
> 
> 可以通过 #ck 命令自检下ck状态
> 
> 如果此ck登录失效或一直失败可以尝试退出hoyolab重新登录获取下ck重新绑定。以及如果此ck同时设置了公共ck，公共ck也同步更新下

谢谢大佬回复，这确实不是我的ituid，而是另外一个人的，当时发生的时候，发送过#我的ck，返回我的ituid是2开头的而不是1开头的这个id，发送#用户统计 没有我的Ituid
![AP%`@CLYG3O7@K`$B2R9 GP](https://user-images.githubusercontent.com/79368384/199181183-36bcc923-e9ad-4d57-afeb-2a4d61fafb6e.jpg)
第一次发生的时候重新发送ck搞定了，第二次重新新发送ck仍然不行，使用#刷新用户缓存，后显示了我的ituid，搞定了
![image](https://user-images.githubusercontent.com/79368384/199181808-2334cfd1-d0f4-48c2-b26e-05a97edc1071.png)
缓存里没我的ck就用了另外一个人的

**Comment by yoimiya-kokomi** [comment]
ok
对于体力命令没有自己ltuid时应该是提示无ck而不是走查询分配，回头我看看是不是这里漏声明只有自己ck才能查询了

**Comment by yoimiya-kokomi** [comment]
ok

对于体力命令没有自己ltuid时应该是提示无ck而不是走查询分配，回头我看看是不是这里漏声明只有自己ck才能查询了

以及确认下体力功能用的是yunzai自带还是图鉴插件或其他插件提供的

**Comment by ctrlcvs** [comment]
> ok
> 
> 对于体力命令没有自己ltuid时应该是提示无ck而不是走查询分配，回头我看看是不是这里漏声明只有自己ck才能查询了
> 
> 以及确认下体力功能用的是yunzai自带还是图鉴插件或其他插件提供的

小黑子又想甩锅图鉴呢？？？？ 图鉴的接口调用逻辑是直接调用的云崽的逻辑获取数据，唯一的区别就是没有区别

**Comment by yoimiya-kokomi** [comment]
咳，了解下使用的功能而已，c佬莫激动…

**Comment by Lactococcuslactis** [comment]
哈哈哈，用的是c佬的图鉴
