### ISSUE TITLE
显示QQ版本过低也许是device.json问题?

### ISSUE THREAD

**Issue by lateautumn233** [Le-niao/Yunzai-Bot#813]
![Screenshot_2022-11-01-09-26-00-350_com sonelli juicessh](https://user-images.githubusercontent.com/63851402/199139395-fb293b27-b386-4e2f-b9b0-9858e0994f84.jpg)
![Screenshot_2022-11-01-09-26-24-467_com sonelli juicessh](https://user-images.githubusercontent.com/63851402/199139406-9b763f5a-241d-4633-818a-c6aa91b92c76.jpg)
![IMG_20221101_093235](https://user-images.githubusercontent.com/63851402/199139415-47056e44-eaea-4f31-85b0-ff040622bd85.jpg)

我怀疑是不是bot生成的device.json是不是被识别了
随便改了改device.json能登录上了

**Comment by AkiraShe** [comment]
修改imei后几位后登录成功了，感谢！

**Comment by nepocashew** [comment]
感谢，修改imei后能登录了

**Comment by overnightover** [comment]
修改imei后几位后登录成功了，感谢！困扰我好多天了

**Comment by 976863929** [comment]
想咨询下有什么格式要求么？我也尝试了修改文件内容，还是返回这个错

**Comment by wyUshio** [comment]
> 想咨询下有什么格式要求么？我也尝试了修改文件内容，还是返回这个错

没啥格式.后面几位就留几位随便改下就可以了.已经成功,感谢楼上的分享

**Comment by GodLike233** [comment]
改imei，随便填什么就行

**Comment by Midnight-2004** [comment]
我单改imei不行，还得把登录设备类型一块改了才能进，但还是要感谢分享

**Comment by Caishuhanhhh** [comment]
感谢就是这个问题，顺便给纯小白指路   cd data/qq号  然后 vim  dxxx-QQ号-json 然后 i 移动键盘修改，然后 :wq
再运行就可以了。
