### ISSUE TITLE
切换多个uid不生效

### ISSUE THREAD

**Issue by lunki528** [Le-niao/Yunzai-Bot#815]
已经添加了2个uid，能成功签到2个。
但是进行切换时无法正常生效，参考下面的截图：
![2TXE_()I@M`1 K 7`O01R8A](https://user-images.githubusercontent.com/62690759/199144904-dcf66b1a-1f95-4b7a-9efe-822feee26f43.png)

不知道是不是我使用的问题，麻烦帮忙确认一下

**Comment by 244030119** [comment]
直接#uid1就行，不需要+

**Comment by Msdyz123** [comment]
同样遇到这个问题，不能绑定新的UID，并且不能切换，#绑定123456789之后显示绑定成功，UID列表没有新的UID并且不能切换，不知道是啥情况

**Comment by jiut** [comment]
同楼上一样的问题，#绑定之后显示绑定成功，但是uid列表没有。

**Comment by lunki528** [comment]
直接#uid1，尝试能切换成功，多谢！
