### ISSUE TITLE
密码登录提示qq版本过低，且扫码登录无效

### ISSUE THREAD

**Issue by SmilingEnchanter** [Le-niao/Yunzai-Bot#818]
![Screenshot_20221101_113252_com termux_edit_118225](https://user-images.githubusercontent.com/117137250/199153261-c74b06e8-514e-42bb-b4b8-2deb111b59ae.jpg)
如图，之前扫码还可以登录，今天凌晨掉线了一次就登不上了，尝试重新配置机器人无法解决，求解决方案

**Comment by HuskyLYL** [comment]
俺也是同样的问题

**Comment by BZBY** [comment]
我重新下载了 之后就好了 ，现在不晓得怎么绑到之前的数据库

**Comment by njgccx** [comment]
我也扫了二维码没反应

**Comment by simo8102** [comment]
这些问题 你们其实应该去上游得oicq那反馈

**Comment by Qujixiang** [comment]
> ![Screenshot_20221101_113252_com termux_edit_118225](https://user-images.githubusercontent.com/117137250/199153261-c74b06e8-514e-42bb-b4b8-2deb111b59ae.jpg) 如图，之前扫码还可以登录，今天凌晨掉线了一次就登不上了，尝试重新配置机器人无法解决，求解决方案

服务器和扫码设备要同一个公有IP才可以扫码登录

**Comment by 976863929** [comment]
我这边是尝试按照 [Mirai](https://github.com/mamoe/mirai/commit/c9d1d386b16e886ad63eb51e6baf7270fcf2fa7b#diff-41ee640092a307ee3e1dc4fef90fc974b5a24346c49a3e547867febc385b72a0) 提供的协议设备元数据修改node_modules/oicq/lib/core/device.js 中的version和subid后成功解决

**Comment by SmilingEnchanter** [comment]
已解决，运行机器人的手机连接扫码手机的热点后可以进行扫码（不是很懂什么原理
