### ISSUE TITLE
更新指令无效

### ISSUE THREAD

**Issue by 1420125167** [Le-niao/Yunzai-Bot#82]
私聊bot使用#更新指令更新之后提示已经是最新版本，但新版本添加的指令无法使用，手动执行git pull也显示already up to date
![QQ截图20220418133137](https://user-images.githubusercontent.com/13842432/163759703-7309c609-8a5f-42db-bdfe-4039e604ae3c.png)
![image](https://user-images.githubusercontent.com/13842432/163759745-c213b8af-29c0-48f8-9a43-9f61dbc428b9.png)

**Comment by chenchenriver** [comment]
应该是要重启一下吧？

**Comment by 1420125167** [comment]
> 应该是要重启一下吧？

重启过几遍了，没用

**Comment by Le-niao** [comment]
可能被其他功能拦截了
