### ISSUE TITLE
低性能设备登录事件早于登录监听加载，无法正常登录

### ISSUE THREAD

**Issue by TimeRainStarSky** [Le-niao/Yunzai-Bot#824]
在低性能设备上，登录事件会比登录监听更早加载完成，导致无法正常登录，特别是在 Commit 7605bfa 之后，多加载了 Runtime，导致该问题更严重，请优化登录流程

以下截图是在 lib/events/login.js 末尾添加 logger.info("加载完成")，可以看出，登录事件早于登录监听加载完成时，无法正常登录
![Screenshot_20221102-021157_ZeroTermux](https://user-images.githubusercontent.com/63490117/199513189-d661b3ba-ac36-4737-b5c0-46942496a4dc.png)

**Comment by TimeRainStarSky** [comment]
一种解决方法：配置文件添加登录延迟设置，有出现这个问题的手动调整登录延迟，让登录监听加载完成再登录

**Comment by Msdyz123** [comment]
请教一下大佬，应该怎么修改登录延迟啊，在config文件夹底下没找到修改登录延迟的文件，我也出现了这个问题，全部更新的指令之后后台依然会记录信息但是机器人不接受任何指令，再次登录就不能登录了，扫码验证成功之后无法登录，密码登录之后有验证链接成功验证后也是无反应不能登录

**Comment by qq5520746** [comment]
我也是

**Comment by yoimiya-kokomi** [comment]
我本地无法复现问题，但如果有能复现的可以协助修改测试下
lib/bot.js 文件
 第9行： `ListenerLoader.load(this)` 删除

下方13行左右 `const bot = new Yunzai(cfg.qq, cfg.bot)` 这一句之后，增加一行
`await ListenerLoader.load(bot)`

协助测试下，测试结果请回复下

**Comment by Msdyz123** [comment]
> 我本地无法复现问题，但如果有能复现的可以协助修改测试下 lib/bot.js 文件 第9行： `ListenerLoader.load(this)` 删除
> 
> 下方13行左右 `const bot = new Yunzai(cfg.qq, cfg.bot)` 这一句之后，增加一行 `await ListenerLoader.load(bot)`
> 
> 协助测试下，测试结果请回复下

使用此方法成功解决，触发了验证码，使用滑动助手成功登陆，之前保存的密码登录显示QQ版本低，手动pnpm run login改为扫码登录成功进去了，退出来再次login改为密码登录后可以正常使用了，所有功能一切正常，非常感谢大佬！！！
