### ISSUE TITLE
发送“#更新”与“#全部更新”指令后报错

### ISSUE THREAD

**Issue by bfhy** [Le-niao/Yunzai-Bot#829]
[更新][update][私聊][冰封幻影(2826301316)] #更新
fatal: Needed a single revision
[YzBot][16:44:43.829][ERRO] [更新][update]
[YzBot][16:44:43.830][ERRO] Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision

[更新][updateAll][私聊][冰封幻影(2826301316)] #全部更新
fatal: Needed a single revision
[YzBot][16:45:38.599][ERRO] [更新][updateAll]
[YzBot][16:45:38.599][ERRO] Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision

    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at update.getcommitId (file:///F:/Yunzai-Bot/plugins/other/update.js:151:26)
    at update.runUpdate (file:///F:/Yunzai-Bot/plugins/other/update.js:114:35)
    at updateAll (file:///F:/Yunzai-Bot/plugins/other/update.js:208:16)
    at PluginsLoader.deal (file:///F:/Yunzai-Bot/lib/plugins/loader.js:247:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by bfhy** [comment]
> [更新][更新][YzBot][ERRO] 错误：命令失败：git rev-parse --short HEAD致命：需要单个修订版
> 
> ```
> at checkExecSyncError (node:child_process:828:11)
> at execSync (node:child_process:899:15)
> at update.getcommitId (file:///F:/Yunzai-Bot/plugins/other/update.js:151:26)
> at update.runUpdate (file:///F:/Yunzai-Bot/plugins/other/update.js:114:35)
> at update (file:///F:/Yunzai-Bot/plugins/other/update.js:58:16)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async PluginsLoader.deal (file:///F:/Yunzai-Bot/lib/plugins/loader.js:251:52)
> ```

**Comment by idonotthinksoso** [comment]
我也碰到了, 后来解决了吗

**Comment by bfhy** [comment]
目前还没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月1日(星期四) 中午1:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Le-niao/Yunzai-Bot] 发送“#更新”与“#全部更新”指令后报错 (Issue #829)






我也碰到了, 后来解决了吗

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
