### ISSUE TITLE
[BUG]当机器人启动然后登录之后会提示QQ掉线，但实际上并没有掉线

### ISSUE THREAD

**Issue by xiaoACE6716** [Le-niao/Yunzai-Bot#832]
![123](https://user-images.githubusercontent.com/94223505/199860470-738065c1-8b3d-431f-891c-b6ee442f2f87.png)
如图，它会提示掉线，但是实际上没有掉线，而且功能还是可用的

**Comment by ctrlcvs** [comment]
bot运行了多个。。。。 

closed 跟 connected 这两个同时提示的话代表是同时运行了多个

建议你pnpm stop 或者说npm stop后再使用node app启动

另外 #重启 指令会默认转换后台运行 在后台运行的情况下再使用node app启动的话会是这个提示

如果是后台运行的情况下需要查看日志 可以通过 pnpm run log 或者 npm run log 来查看机器人运行日志
