### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by QianMoQAQ** [Le-niao/Yunzai-Bot#84]
手机怎么弄啊
![-3d56dfdbcd37bbb3](https://user-images.githubusercontent.com/99474233/163959963-7a5d76fa-c348-436e-b1fa-6b02fd14fbab.jpg)
求助…………………………

**Comment by Le-niao** [comment]
`npm install` 安装下

**Comment by QianMoQAQ** [comment]
![Uploading -6a8ccacf05222cf6.jpg…]()

**Comment by QianMoQAQ** [comment]
![-6a8ccacf05222cf6](https://user-images.githubusercontent.com/99474233/163967930-a4fa09df-40c8-4184-b5ae-60068f2ae5d0.jpg)

**Comment by QianMoQAQ** [comment]
> `npm install` 安装下

![-6a8ccacf05222cf6](https://user-images.githubusercontent.com/99474233/163972960-c0cf2113-9199-4579-a844-4fbf403be173.jpg)
