### ISSUE TITLE
请问QQ昵称的当前内存占用如何关闭?

### ISSUE THREAD

**Issue by ImHeroZero** [Le-niao/Yunzai-Bot#843]
如题,插件安装的有点多了,不知道是Yunzai自带的,还是某个插件增加的,在索引里找了,一个说明都没有......

**Comment by fsqhn** [comment]
抽卡插件的，就是flower-plugin这个。

**Comment by ImHeroZero** [comment]
> 抽卡插件的，就是flower-plugin这个。

感谢
