### ISSUE TITLE
云崽扫码登入和输入密码登录都无反应

### ISSUE THREAD

**Issue by WNCX** [Le-niao/Yunzai-Bot#846]
bot用的好好的突然间断线，再次用密码登入时提示版本过低
随后清除密码，通过扫码登录后反应（手机扫二维码并授权登录后命令行不再有任何反应）
后面通过更改版本号解决了版本过低，但出现了和扫码一样的情况

*重新安装云崽后仍然是这个问题
*重装系统后仍然存在这个问题
*在重装系统后再直接通过git下载仓库并配置运行仍然存在此问题
*更换电脑重装系统后再通过git下载仓库并配置运行仍然存在此问题
*使用虚拟机重复上述操作仍然存在此问题

系统：ubuntu22.04LTS
node版本：16.x

**Comment by AgIzT** [comment]
找到云崽目录/data文件下你机器人的QQ，点进去那个/device文件，把里边的照着格式乱改
![BX%90YG8JP_O7NY5WY@)70H](https://user-images.githubusercontent.com/108292638/200209180-bff6aeef-4d53-4a58-b614-963064fb3e19.gif)

**Comment by 976863929** [comment]
我是更新了qq版本后才解决的

**Comment by lgyseven** [comment]
> 我是更新了qq版本后才解决的

佬怎么更新的qq版本

**Comment by zh8416** [comment]
> 我这边是尝试按照 [Mirai](https://github.com/mamoe/mirai/commit/c9d1d386b16e886ad63eb51e6baf7270fcf2fa7b#diff-41ee640092a307ee3e1dc4fef90fc974b5a24346c49a3e547867febc385b72a0) 提供的协议设备元数据修改node_modules/oicq/lib/core/device.js 中的version和subid后成功解决

给你点赞兄弟，你这个方法靠谱，从版本号上把问题解决了

**Comment by zh8416** [comment]
[device.txt](https://github.com/Le-niao/Yunzai-Bot/files/9960227/device.txt)
承接上面大佬的教程，把109行和114行的值改成mirai那里的值，就不再提示版本过低了

**Comment by cc13090101** [comment]
按此方法修改后仍然提示QQ版本过低

**Comment by zh8416** [comment]
> 按此方法修改后仍然提示QQ版本过低

选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后

**Comment by zh8416** [comment]
> > > 按此方法修改后仍然提示QQ版本过低
> > 
> > 
> > 选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后
> 
> 按此方法修改node_modules/oicq/lib/core/device.js文件mobile中的version和subid后依旧提示版本过低，登录选择是安卓手机

如果修改device.json和device.js后，pnpm run login也还版本低的话，那说明这方法还是治标不治本。

**Comment by JingNianNian** [comment]
> > > > 按此方法修改后仍然提示QQ版本过低
> > > 
> > > 
> > > 选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后
> > 
> > 
> > 按此方法修改node_modules/oicq/lib/core/device.js文件mobile中的version和subid后依旧提示版本过低，登录选择是安卓手机
> 
> 如果修改device.json和device.js后，pnpm run login也还版本低的话，那说明这方法还是治标不治本。


`
    name: "A8.9.15.9425",
    version: "8.9.15.9425",
    ver: "8.9.15",
    subid: 537138832,
`
更改这四项后，不提示版本过低，现在提示：[安全提醒]当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。
我更换了三个设备，并更改devices.js中，均提示如此。

**Comment by 3455315719** [comment]
> > > > > 按此方法修改后仍然提示QQ版本过低
> > > > 
> > > > 
> > > > 选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后
> > > 
> > > 
> > > 按此方法修改node_modules/oicq/lib/core/device.js文件Mobile中的版本和subid后依旧提示版本过低，登录选择是安卓手机
> > 
> > 
> > 如果修改device.json和device.js后，pnpm run login也还版本低的话，那说明这方法还是治标不治本。
> 
> `name: "A8.9.15.9425", version: "8.9.15.9425", ver: "8.9.15", subid: 537138832,` 更改这四项后，不提示版本过低，现在提示：[安全提醒]当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 我更换了三个设备，并更改devices.js中，均提示如此。

手机扫码登陆 下载一个爱加速app 定位到和服务器相同的省市就可以了

**Comment by sec-8** [comment]
> > > > > > 按此方法修改后仍然提示QQ版本过低
> > > > > 
> > > > > 
> > > > > 选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后
> > > > 
> > > > 
> > > > 按此方法修改node_modules/oicq/lib/core/device.js文件Mobile中的版本和subid后依旧提示版本过低，登录选择是安卓手机
> > > 
> > > 
> > > 如果修改device.json和device.js后，pnpm run login也还版本低的话，那说明这方法还是治标不治本。
> > 
> > 
> > `name: "A8.9.15.9425", version: "8.9.15.9425", ver: "8.9.15", subid: 537138832,` 更改这四项后，不提示版本过低，现在提示：[安全提醒]当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 我更换了三个设备，并更改devices.js中，均提示如此。
> 
> 手机扫码登陆 下载一个爱加速app 定位到和服务器相同的省市就可以了


> > > > > > 按此方法修改后仍然提示QQ版本过低
> > > > > 
> > > > > 
> > > > > 选的登录模式和修改的设备版本是否一致，比如安卓手机对应mobile，手表是watch，苹果的在最后
> > > > 
> > > > 
> > > > 按此方法修改node_modules/oicq/lib/core/device.js文件Mobile中的版本和subid后依旧提示版本过低，登录选择是安卓手机
> > > 
> > > 
> > > 如果修改device.json和device.js后，pnpm run login也还版本低的话，那说明这方法还是治标不治本。
> > 
> > 
> > `name: "A8.9.15.9425", version: "8.9.15.9425", ver: "8.9.15", subid: 537138832,` 更改这四项后，不提示版本过低，现在提示：[安全提醒]当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。 我更换了三个设备，并更改devices.js中，均提示如此。
> 
> 手机扫码登陆 下载一个爱加速app 定位到和服务器相同的省市就可以了


我下了爱加速换到上海（服务器在上海），扫码还是异常状态，当前设备网络状态不稳定...

**Comment by Hanserwei** [comment]
device.js里面的version和subid改成多少，我改成8.9.15.9425和537138832并没有解决问题

**Comment by zh8416** [comment]
> device.js里面的version和subid改成多少，我改成8.9.15.9425和537138832并没有解决问题

你是重新login的吗，而且这134行对应的是安卓手机的登陆方式，如果你是ios或者手表的最好也换一下。正常来说按这些步骤至少不会报版本低的问题了

**Comment by suriealli** [comment]
我也是，目前改了版本号，没提示版本问题，但是现在扫码跟密码登录都提示设备不稳定，登录不了，我是寄了吗

**Comment by Sagili365** [comment]
同样问题,我是改IMEI就好了，参见#813

**Comment by GoFun-Dian** [comment]
> 同样问题,我是改IMEI就好了，参见#813

都尝试了，为啥不行
