### ISSUE TITLE
关于：米游社接口报错，暂时无法查询：error

### ISSUE THREAD

**Issue by weilai5201314** [Le-niao/Yunzai-Bot#849]
- 群友在查看体力的时候出现报错，其他功能可以查看
- 已经去米游社的体力里面，点进去看了，且发了录屏在群里，查看的时候没有验证码（已看过录屏且确认没有）
- 他今天上午有验证码，中午没有，然后下午又有了
- 已经重新退出登录，然后获取了cookie。

<img width="576" alt="image" src="https://user-images.githubusercontent.com/99032101/200313027-927d1fde-c4a8-4d57-8fa5-6622fc3bf3f6.png">

录屏里面，点进体力界面

<img width="627" alt="image" src="https://user-images.githubusercontent.com/99032101/200313493-0cde26a3-dda4-4cbb-b0c6-72d7cae5fe2d.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/99032101/200312573-f5851c87-0ce5-44e7-b87a-a043d2e6960c.png">

**Comment by weilai5201314** [comment]
补充一下，就是已经看过了 #828 ，所以等了几天才来issue，实际上他几天前就已经不能查了，但是米游社一直都没有验证码。
今天短暂的中午可查，下午又不行了。

**Comment by pexcuseme** [comment]
去米游社签到的地方，验证码可能在那里，不一定在体力

**Comment by weilai5201314** [comment]
> > 补充一下，就是已经看过了 #828 ，所以等了几天才来issue，实际上他几天前就已经不能查了，但是米游社一直都没有验证码。 今天短暂的中午可查，下午又不行了。
> 
> 同设备情况下获取cookie保存，其次的话验证码目前阶段是属于是全局的，并不是说你体力接口查询验证码就百分百会出验证码，同理的对应部分功能也会出现验证码的情况。
> 
> 另外error的情况并不都是验证码，具体看校验code retcode 是1034的时候是验证码别的并不是验证码
> 
> 这里再补充说明一下，就是体力验证码米游社看不见的话 尝试多刷几次看看，因为米游社同时校验设备的 不清楚是不是这个原因导致的

**#已解决**

- 已经看了，`retcode`是1034。
- 让群友去刷新了体力的界面，并且签到，签到过验证码之后就可以查看体力。

**#疑问**

- 但是现在签到界面，`签到验证码`好像每天都有？
- 虽然我自身没有每天都过验证码，也能查看体力。
- 但是群友如果明天又不能查看，又得去米游社过验证吗？那还挺难受的。

<img width="710" alt="image" src="https://user-images.githubusercontent.com/99032101/200498611-33e77be7-c7a1-445a-a8fe-3b4d9d8760de.png">

**Comment by ctrlcvs** [comment]
> > > 补充一下，就是已经看过了 #828 ，所以等了几天才来issue，实际上他几天前就已经不能查了，但是米游社一直都没有验证码。 今天短暂的中午可查，下午又不行了。
> > 
> > 
> > 同设备情况下获取cookie保存，其次的话验证码目前阶段是属于是全局的，并不是说你体力接口查询验证码就百分百会出验证码，同理的对应部分功能也会出现验证码的情况。
> > 另外error的情况并不都是验证码，具体看校验code retcode 是1034的时候是验证码别的并不是验证码
> > 这里再补充说明一下，就是体力验证码米游社看不见的话 尝试多刷几次看看，因为米游社同时校验设备的 不清楚是不是这个原因导致的
> 
> **#已解决**
> 
> * 已经看了，`retcode`是1034。
> * 让群友去刷新了体力的界面，并且签到，签到过验证码之后就可以查看体力。
> 
> **#疑问**
> 
> * 但是现在签到界面，`签到验证码`好像每天都有？
> * 虽然我自身没有每天都过验证码，也能查看体力。
> * 但是群友如果明天又不能查看，又得去米游社过验证吗？那还挺难受的。
> 
> <img alt="image" width="710" src="https://user-images.githubusercontent.com/99032101/200498611-33e77be7-c7a1-445a-a8fe-3b4d9d8760de.png">

签到验证码根据我个人的测试情况是 2-3天验证码后会解除分控 ，但是后续正常签到2-3天一样的还是会存在验证
码，不过签到的验证码似乎被单独隔出来的，并不会说冲突到体力的，如果说体力经常验证码的可以尝试过签到的验证码

另外就是用户尽量不要绑定太多的bot或者说网络IP，这些数据容易导致验证码。

如果说一个用户经常出现验证码的话，建议有事没事上米游社逛逛，目前测出的接口不仅仅是体力跟签到需要验证码，以及说深渊还有角色查询他人的时候也同样会出现 retcode为1034的情况

**Comment by weilai5201314** [comment]
好的谢谢。
