### ISSUE TITLE
部分图片出现中文乱码

### ISSUE THREAD

**Issue by Lurvelly** [Le-niao/Yunzai-Bot#850]
问题样例(Centos 8.2)：
![da3215895dff0a148ab163e4225802e6](https://user-images.githubusercontent.com/17422260/200331688-de457656-be34-4e31-bb4f-69ccdd9fc347.jpg)
正常样例(未知系统)：
![b74c7e131ef2e90a0216c50938938acd](https://user-images.githubusercontent.com/17422260/200331811-c295dab8-3f76-4740-bfb5-f23d8e963d6b.jpg)

问题系统信息：
[root@VM-8-8-centos ~]# uname -r
4.18.0-305.3.1.el8.x86_64
[root@VM-8-8-centos ~]# cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core)

**Comment by cy115** [comment]
下载字体了吗,估计你第一个系统没有安装中文字体
yum groupinstall fonts -y

**Comment by Lurvelly** [comment]
> 下载字体了吗,估计你第一个系统没有安装中文字体 yum groupinstall fonts -y

多谢，@cy115

之前我把locale修改为zh_CN.UTF-8 依然存在问题，但下载字体后恢复正常了，确实是缺少字体的原因。

我将关闭这个issue。
