### ISSUE TITLE
内存占用越来越多cpu爆满

### ISSUE THREAD

**Issue by 1011382654** [Le-niao/Yunzai-Bot#859]
有大佬遇到吗？现在不知道是哪个插件什么命令造成的要怎么排查啊！
插件就装了：genshin、miaomiao、xiaoyao、土块
![This is an image](https://ww3.sinaimg.cn/large/008p0nyfly1h7z8wehzwmj30np09ugmg.jpg)

**Comment by ctrlcvs** [comment]
![image](https://user-images.githubusercontent.com/73279880/200865721-6bd0482b-a0f9-449d-95bf-95de3fa7fba1.png)
你服务器 打开一个谷歌浏览器你会发现进程不止一个
其次目前喵喵插件是内置了一个浏览器运行的可能会多一个，别的插件都是直接调用的主体的浏览器操作

**Comment by 1011382654** [comment]
> ![image](https://user-images.githubusercontent.com/73279880/200865721-6bd0482b-a0f9-449d-95bf-95de3fa7fba1.png) 你服务器 打开一个谷歌浏览器你会发现进程不止一个 其次目前喵喵插件是内置了一个浏览器运行的可能会多一个，别的插件都是直接调用的主体的浏览器操作

现在每隔几个小时内存就要满一次,看着他一点一点的涨很无奈。。。然后奔溃重启服务器

**Comment by ctrlcvs** [comment]
![image](https://user-images.githubusercontent.com/73279880/200869525-556edb24-979c-442b-b279-0b64131d3333.png)

尝试修改`./lib/puppeteer/puppeteer.js` 中的截图次数上限看看

另外可以看看 #842 中提到的一个方法进行重启 puppeteer

**Comment by 1011382654** [comment]
> ![image](https://user-images.githubusercontent.com/73279880/200869525-556edb24-979c-442b-b279-0b64131d3333.png)
> 
> 尝试修改`./lib/puppeteer/puppeteer.js` 中的截图次数上限看看
> 
> 另外可以看看 #842 中提到的一个方法进行重启 puppeteer

我试试看。唉！这一回头又涨了几个百分点之前都不这样的

**Comment by 1011382654** [comment]
> ![image](https://user-images.githubusercontent.com/73279880/200869525-556edb24-979c-442b-b279-0b64131d3333.png)
> 
> 尝试修改`./lib/puppeteer/puppeteer.js` 中的截图次数上限看看
> 
> 另外可以看看 #842 中提到的一个方法进行重启 puppeteer

麻了，还是会涨最多能8个chrome进程每个占用两百多MB，奔溃日志
(node:154033) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by 1011382654** [comment]
![image](https://ww3.sinaimg.cn/large/008p0nyfly1h7zyy8pwmrj30rc0abjse.jpg)
![image](https://ww3.sinaimg.cn/large/008p0nyfly1h7zz2elzycj30kk0fbmz6.jpg)
![image](https://ww3.sinaimg.cn/large/008p0nyfly1h7zz3tmf9lj30kk0f8wge.jpg)

**Comment by geol** [comment]
实在不行你用wsl呗，我用的树莓派，4g内存一直很富裕，没出现chromium占满内存的事儿。

**Comment by 1011382654** [comment]
> 实在不行你用wsl呗，我用的树莓派，4g内存一直很富裕，没出现chromium占满内存的事儿。

不知道是不是更新的原因现在没问题了，chrome进程也只会存在一个
