### ISSUE TITLE
插件库在哪里？群号是多少啊

### ISSUE THREAD

**Issue by liuzj288** [Le-niao/Yunzai-Bot#86]
rt

**Comment by bling-yshs** [comment]
+1

**Comment by Duyalun** [comment]
213938015快满了

**Comment by karakoo** [comment]
> 213938015快满了

没有对外开放了，已经搜不到了

**Comment by liuzj288** [comment]
> 213938015快满了

能拉人进去不（丘丘号：1067371971）

**Comment by hzx19980513** [comment]
> > 213938015快满了
> 
> 能拉人进去不（丘丘号：1067371971）

同 可以拉我一下不（丘丘：923450872）

**Comment by bling-yshs** [comment]
+1

377178599

嘿嘿

> > > 213938015快满了
> > 
> > 
> > 能拉人进去不（丘丘号：1067371971）
> 
> 同 可以拉我一下不（丘丘：923450872）

**Comment by zhangjy1318** [comment]
还能拉下吗（丘丘号：1318629157）

**Comment by Duyalun** [comment]
只有miaomaio插件群可以进了 607710456
