### ISSUE TITLE
UID切换问题

### ISSUE THREAD

**Issue by jiut** [Le-niao/Yunzai-Bot#869]
同样遇到这个问题，不能绑定新的UID，并且不能切换，#绑定123456789之后显示绑定成功，UID列表没有新的UID并且不能切换，不知道是啥情况

_Originally posted by @Msdyz123 in https://github.com/Le-niao/Yunzai-Bot/issues/815#issuecomment-1298429544_

**Comment by firfix** [comment]
#uid指令显示的是你绑定过cookie的uid。直接通过#绑定uid指令的绑定很鸡肋，能查到的信息基本等同于你进别人主页能看到的内容。
