### ISSUE TITLE
建议加入XML大图

### ISSUE THREAD

**Issue by miseryCN** [Le-niao/Yunzai-Bot#87]
机器人的大部分功能是基于图片的，我觉得可以把现在的图片浏览体验提升一下。
使用xml大图，可以一目了然，不需要再去点开图片看了。 xml大图和目前的比较：

![QQ图片20220421102044](https://user-images.githubusercontent.com/32919541/164358686-d37d3c2d-cdee-4b3d-8686-d0dc1b7072be.jpg)

可以做一个兼容处理，优先发送xml大图，失败则转换为普通图片处理；亦或是让用户自行配置（发送XML大图有封号的风险）

一点小意见，望采纳！

**Comment by Le-niao** [comment]
有封号的风险不考虑
