### ISSUE TITLE
发送cookie给机器人，机器人未响应

### ISSUE THREAD

**Issue by geol** [Le-niao/Yunzai-Bot#877]
如题。然后从别的端登陆机器人qq查看，发现对方并未发送任何消息。云崽的终端输出界面也没有任何提示。

**Comment by likodesu** [comment]
这是因为没发送出去，要加好友

**Comment by geol** [comment]
新策略吗？机器人qq是管理员，任何人才能私聊的。

**Comment by firfix** [comment]
包含敏感词的时候消息会被截取，比如sm之类的，有时候字符串里面包含这些就会被截断。加好友就没这个问题

**Comment by geol** [comment]
谢谢辣

**Comment by geol** [comment]
谢谢辣
