### ISSUE TITLE
绑定UID无法改绑

### ISSUE THREAD

**Issue by xiaoACE6716** [Le-niao/Yunzai-Bot#884]
发送#绑定UID后，机器人回复绑定成功，但是使用更新面板后仍然为之前绑定的UID，#UID也是只有之前绑定的UID

**Comment by lgyseven** [comment]
切换uid

**Comment by xiaoACE6716** [comment]
> 切换uid

不行，uid列表里也只有之前绑定的UID，而没有新绑定的uid

**Comment by xiaoACE6716** [comment]
还是说，在某个版本更新后，就只能查自己绑定的ck所归属的那个号了，不能将绑定更改为别人的uid然后去查询
(为什么我会这么想：因为以前确实可以直接绑定另外的uid去用)

**Comment by firfix** [comment]
除非服务器上恰好包含另一个uid的cookie，不然单凭一个uid就是用不了需要cookie才能做的操作。

**Comment by jiut** [comment]
是否和这个 issue 的情况相似#869

**Comment by xiaoACE6716** [comment]
> 是否和这个 issue 的情况相似#869

是的，在之前没更新的时候，可以通过#绑定123456789的命令去切换绑定的uid，然后我是装了喵喵插件所以用的是喵喵插件的面板查询，但是更新后，使用#绑定123456789的命令，机器人会回复绑定成功123456789，但是使用更新面板的时候，查询的还是我之前绑定的uid
