### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by liujhs** [Le-niao/Yunzai-Bot#887]
[YzBot][10:39:58.547][ERRO] [ErrorReply: NOAUTH Authentication required.]
运行环境：
腾讯云 CentOS8
node.js:18.12.1
报这个错怎么解决呢？

**Comment by liujhs** [comment]
redis需要密码

**Comment by ziyuCat** [comment]
为啥我把密码配置上之后，再次启动【node app】 直接提示，redis链接失败
