### ISSUE TITLE
一个会让BOT刷屏的bug

### ISSUE THREAD

**Issue by xingluo233** [Le-niao/Yunzai-Bot#890]
众所周知 双击BOT头像，BOT会发一张图，如果没绑uid的话 双击头像就会这样，一直双击会让BOT刷屏，建议没绑uid时，不对双击头像回应![Screenshot_2022-11-16-16-37-18-628-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/54618947/202130684-07201de7-cf65-42fe-b330-10dd79af8cbb.jpg)

**Comment by Grapesigns** [comment]
可以关闭

**Comment by firfix** [comment]
这不算bug吧...

**Comment by lgyseven** [comment]
建议关掉
