### ISSUE TITLE
退群通知能不能改一改，去掉永远两个字

### ISSUE THREAD

**Issue by WNCX** [Le-niao/Yunzai-Bot#920]
![N@ RODO0K%77BWC_GFK211O](https://user-images.githubusercontent.com/70813274/203047985-ec854ba7-285d-4424-91fb-d673a9f39631.png)
写`永远离开了我们`感觉好像是谁去世了一样，一个退群通知总给人一种不吉利的感觉
如果去掉了`永远`那么就不会有这种感觉

**Comment by xujunBachlor** [comment]
![image](https://user-images.githubusercontent.com/33261606/203239753-a84490d2-081d-4197-92ca-2bd87e8fbce7.png)

```
 constructor () {
    super({
      name: '退群通知',
      dsc: 'xxx永远离开了我们',
      event: 'notice.group.decrease'
    })

    /** 退群提示词 */
    this.tips = '永远离开了我们。。'
  }
```

这里就可以设置提示语了
