### ISSUE TITLE
无法登陆qq

### ISSUE THREAD

**Issue by Kevinces** [Le-niao/Yunzai-Bot#93]
密码登陆显示登陆存在风险，扫码登陆显示登陆环境异常不允许登陆

**Comment by karakoo** [comment]
可以选择关闭登录保护，然后使用密码登录

**Comment by Kevinces** [comment]
> 

已经关闭了登陆保护，但是还是显示登陆存在风险，不允许登陆

**Comment by Kevinces** [comment]
> 可以选择关闭登录保护，然后使用密码登录

已经关闭了登陆保护，但是还是显示登陆存在风险，无法登陆

**Comment by karakoo** [comment]
> > 可以选择关闭登录保护，然后使用密码登录
> 
> 已经关闭了登陆保护，但是还是显示登陆存在风险，无法登陆

试试删除device.json、换个登录设备类型

**Comment by L-yt** [comment]
同大部分都搞好了，就卡在tx风控这块，难搞，另外没找到device.json这个东西

**Comment by karakoo** [comment]
> 同大部分都搞好了，就卡在tx风控这块，难搞，另外没找到device.json这个东西

在这里
![image](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)

**Comment by L-yt** [comment]
> > 同样什么都难搞好，就卡在tx风这块，搞，另外控制没找到device.json这个东西
> 
> 在这里 ![图片](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)

尝试了还是不行，tx罪大恶极，得找别的路子看看

**Comment by Kevinces** [comment]
> > > 同样什么都难搞好，就卡在tx风这块，搞，另外控制没找到device.json这个东西
> > 
> > 
> > 在这里 ![图片](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)
> 
> 尝试了还是不行，tx罪大恶极，得找别的路子看看

我尝试成功了，删除这个device文件后用 https://github.com/mzdluo123/TxCaptchaHelper 上的滑动验证码助手在安卓真机验证登陆成功。

**Comment by L-yt** [comment]
> > > > 同样什么都难搞好，就卡在tx风这块，搞，另外控制没找到device.json这个东西
> > > 
> > > 
> > > 在这里 ![图片](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)
> > 
> > 
> > 尝试了还是不行，tx罪大恶极，得找别的路子看看
> 
> 我尝试成功了，删除这个device文件后用 https://github.com/mzdluo123/TxCaptchaHelper 上的滑动验证码助手在安卓真机验证登陆成功。

但是我用的linux服务器，看了下项目介绍是指定手机使用，感谢思路

**Comment by Kevinces** [comment]
> > > > > 同样什么都难搞好，就卡在tx风这块，搞，另外控制没找到device.json这个东西
> > > > 
> > > > 
> > > > 在这里 ![图片](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)
> > > 
> > > 
> > > 尝试了还是不行，tx罪大恶极，得找别的路子看看
> > 
> > 
> > 我尝试成功了，删除这个device文件后用 https://github.com/mzdluo123/TxCaptchaHelper 上的滑动验证码助手在安卓真机验证登陆成功。
> 
> 但是我用的linux服务器，看了下项目介绍是指定手机使用，感谢思路

同linux服务器，只需要在登陆的时候把手机上完成验证码的tiket复制到服务器上即可

**Comment by L-yt** [comment]
> > > > > > 同样什么都难搞好，就卡在tx风这块，搞，另外控制没找到device.json这个东西
> > > > > 
> > > > > 
> > > > > 在这里 ![图片](https://user-images.githubusercontent.com/70872201/165012920-d7ff56c2-ca56-45a0-8687-b4f5e8ab59c7.png)
> > > > 
> > > > 
> > > > 尝试了还是不行，tx罪大恶极，得找别的路子看看
> > > 
> > > 
> > > 我尝试成功了，删除这个device文件后用 https://github.com/mzdluo123/TxCaptchaHelper 上的滑动验证码助手在安卓真机验证登陆成功。
> > 
> > 
> > 但是我用的linux服务器，看了下项目介绍是指定手机使用，感谢思路
> 
> 同linux服务器，只需要在登陆的时候把手机上完成验证码的tiket复制到服务器上即可

ok，下午搞搞看，谢谢大佬
