### ISSUE TITLE
从11-25日开始绑定cookie失败

### ISSUE THREAD

**Issue by shuangxunian** [Le-niao/Yunzai-Bot#942]
用`document.cookie.replace('smid','')`获取到的ck一直显示：
绑定cookie失败
请先【登录米游社】或【登录通行证】再获取cookie

版本为3.0.0的云崽

**Comment by CeciliaAki** [comment]
我这边也出现了这个问题，让群友确认了获取cookie的流程没有任何错误后（最新的完整的米游社原神界面的cookie），换了各种方法，仍然显示

请先【登陆米游社】或【登陆通行证】再获取cookie

**Comment by xRabbitKnight** [comment]
按教程获取的cookie好像有几条重要的字段没了
Chrome登录米游社，F12进调试，选择网络，刷新后找到main.js，请求标头里的cookie复制过去能用

**Comment by Lo1iame** [comment]
网页端不行，移动端不行，获取cookie的APP也不行，依然提示
请先【登陆米游社】或【登陆通行证】再获取cookie

目前只有绑了stoken后用【#刷新ck】我才看到成功

**Comment by Lo1iame** [comment]
> > 网页端不行，移动端不行，获取cookie的APP也不行，依然提示 请先【登陆米游社】或【登陆通行证】再获取cookie
> > 目前只有绑了stoken后用【#刷新ck】我才看到成功
> 
> 我这样拿的cookie不能用吗，我刚刚试了下还可以 你试下更新下Yunzai，今天早上有有关新版cookie的代码合并

谢谢，合并后用main.js里取到的完整可以绑定，其他方式取到的好像都缺失字段了

**Comment by 1202GanYu** [comment]
edge无痕模式登录米游社，F12进调试，选择网络，然后点文档，刷新后找到ys/，请求标头里的cookie复制过去能用

**Comment by GOOD-AN** [comment]
最新的v2版ck，已经不适用于原来js获取了，似乎开启了httponly，手机版可以使用最新版的via，这样来获取。
![VG1$T0_JWNGGQCEI56{4QSI](https://user-images.githubusercontent.com/53306377/204074515-274f3715-7838-4739-b179-4821e9a124f9.jpg)
*此截图版本为4.4.5

**Comment by CainLuo** [comment]
其实可以不用校验cookie是否是第几版，只要是从米游社获取的cookie，直接使用就行了

**Comment by GOOD-AN** [comment]
> 其实可以不用校验cookie是否是第几版，只要是从米游社获取的cookie，直接使用就行了

是的，我只是说明一下为什么会出现这个情况，不用在意第几版。
