### ISSUE TITLE
添加国际服支持?

### ISSUE THREAD

**Issue by Canary233** [Le-niao/Yunzai-Bot#946]
如题

**Comment by kissnavel** [comment]
国际服本来就支持啊

**Comment by Canary233** [comment]
> 国际服本来就支持啊

Hoyolab好像没法绑定:
绑定cookie失败：该账号尚未绑定原神角色！

**Comment by kissnavel** [comment]
> > 国际服本来就支持啊
> 
> Hoyolab好像没法绑定: 绑定cookie失败：该账号尚未绑定原神角色！

我的就是用来绑国际服的，绝对可以绑。
