### ISSUE TITLE
戳一戳突然无法使用

### ISSUE THREAD

**Issue by davidelectricfree** [Le-niao/Yunzai-Bot#95]
#老婆 及其他功能均正常，但是戳机器人没有任何反应，且控制台那里也不会显示机器人被戳的信息，很奇怪，将bot文件夹所有文件重新删了重新下载安装依然无法解决问题。

备注：程序版本为最新版，删除bot文件夹使用git安装的也是最新版。

**Comment by Le-niao** [comment]
机器人qq开启头像双击动作

**Comment by davidelectricfree** [comment]
> 机器人qq开启头像双击动作

QQ机器人没有换过啊，之前戳一戳功能一直是好的，直到我把miao-plugin插件导入到机器人以后，发现一堆问题，然后我又把miao-plugin从插件文件夹删除，就发现突然戳一戳不能用了，后面重装什么的根本也不行

**Comment by davidelectricfree** [comment]
> 机器人qq开启头像双击动作

另外我戳机器人，手机版QQ是能够看到那行字：你戳了戳XXX，但是bot cmd终端这边看不到任何被戳的debug信息，我这边已经将信息模式从info改到debug了

**Comment by Le-niao** [comment]
你将登录设备改其他的，手表收不到戳一戳的通知

**Comment by davidelectricfree** [comment]
> 你将登录设备改其他的，手表收不到戳一戳的通知

当前使用的是IPAD，也就是协议5，我印象中我没改过，之前确实是可以用的，戳一下就好了，现在不知道为什么不行了。

**Comment by davidelectricfree** [comment]
> 你将登录设备改其他的，手表收不到戳一戳的通知

emmmmmmmm我换个问法吧，大佬，这个项目除了那个yunzai_bot的文件夹，是否还在电脑其他地方有数据库，我想彻底重装，C盘下面program files 下面的redis文件夹我都卸载，edis文件及redis文件夹下面的数据和Log文件我全部删了，重新装redis还是不好用，除了这两个地方，项目在其他地方还有数据吗？或者还有相关的数据库文件吗？

**Comment by Le-niao** [comment]
还有一个redis数据 dump.rdb

**Comment by davidelectricfree** [comment]
> 还有一个redis数据 dump.rdb

dump.rdb 是不是就是在redis文件夹里面，如果是那个，我已经删过了。还有其他的吗？
