### ISSUE TITLE
部分uid查询回复：米游社数据未公开

### ISSUE THREAD

**Issue by muguodiao** [Le-niao/Yunzai-Bot#955]
疑似bug，存疑uid：尾号2299 尾号2294 尾号2293
![image](https://user-images.githubusercontent.com/105115300/204244218-4e4d0fda-2dc1-4cf4-aeb4-e3a27bf3b3cd.png)

**Comment by muguodiao** [comment]
![image](https://user-images.githubusercontent.com/105115300/204244684-5993f77b-d38d-4db6-b4ed-b992edc6c503.png)
尾号2193
![image](https://user-images.githubusercontent.com/105115300/204244880-9825701a-6f0f-4801-b673-1e93bc1276c1.png)

**Comment by GOOD-AN** [comment]
提供的这几个uid实际数据是公开的吗？我尝试了直接访问接口与其他项目，都返回的是未公开。

**Comment by muguodiao** [comment]
> 提供的这几个用户界面设计（User Interface Design的缩写）实际数据是公开的吗？我尝试了直接访问接口与其他项目,都返回的是未公开。

理论上是公开的，这些id是我挨个测试出来的，末尾四位数是这些的都返回未公开，其中最开始的那个id号主说是公开的，你可以尝试以同样四位尾数的其他id，比如123452193  123122193

**Comment by GOOD-AN** [comment]
是这样的，我换了号`119582294`、`222012299`可以正常查询显示。和号主先对一下设置，米游社APP -> 我的 -> 个人主页 -> 我的角色右侧管理 -> 点击倒三角，会有两个选项，个人主页卡片和角色详情数据，看一下是否打开。

**Comment by lgyseven** [comment]
绑定cookie可以绕过直接查米游社数据，绑定uid查数据得设置米游社名片公开才行
