### ISSUE TITLE
关于每日签到或自动签到的建议

### ISSUE THREAD

**Issue by gaqwe767** [Le-niao/Yunzai-Bot#96]
![QQ截图20220426081613](https://user-images.githubusercontent.com/64371245/165195539-05e396ef-bdff-43c9-abf0-15b30afb38f0.jpg)
建议加个签到图，更加直观。图来自XLZ原神信息查询工具。
建议加入多帐号签到，如图
![QQ图片20220426082459](https://user-images.githubusercontent.com/64371245/165195873-fa84e22f-d901-47d5-bd39-3b511a71ce10.png)
来自：https://github.com/molehzy/GenshinBot

bot其实做的挺不错的，就是我想要多帐号签到没有，希望完善一下，如果多帐号还支持自动签到那就更好了。其实也可以简单点，一个QQ对应一个UID签到也可以。多帐号需求是因为我有官服还有B服号绑都一个米游社帐号上了，而且米游社也支持绑多个渠道帐号，还有感谢各位开发者dalao，辛苦了！

**Comment by Juenia** [comment]
发送```
#开启自动签到
```
试试？
