### ISSUE TITLE
QQ版本过低

### ISSUE THREAD

**Issue by GoGoManiac** [Le-niao/Yunzai-Bot#969]
目前五种登录平台都显示版本过低了，且无法扫码（显示必须在同一wifi下），求解决

**Comment by WindraiteLesd** [comment]
把data里的device.json按照原有格式和长度乱改一遍，无法扫码用手机号登录

**Comment by GoGoManiac** [comment]
> 把data里的device.json按照原有格式和长度乱改一遍，无法扫码用手机号登录
![QQ截图20221201142113](https://user-images.githubusercontent.com/64263349/204980491-2c61d9ee-cff2-469e-8b10-6bfb573af54f.png)
我如果重新登录，会显示错误 同时更改device.js无效果

**Comment by WindraiteLesd** [comment]
其实改IMEI那一段就行了，你把那个文件删了让yunzai重新生成一份，完了再回去改IMEI那串数字末端试试

**Comment by GoGoManiac** [comment]
> 其实改IMEI那一段就行了，你把那个文件删了让云扎重新生成一份，完了再回去改IMEI那串数字末端试试

照您说的做了，如果用账密登录则依旧是版本过低，若扫码则显示风险，我也试了一下用手机号登录，显示的就是'ERR_OUT_OF_RANGE'

**Comment by mingmono** [comment]
请问您的问题解决了吗，我也是这个问题，请问一下是怎么解决的

**Comment by WindraiteLesd** [comment]
> > 其实改IMEI那一段就行了，你把那个文件删了让云扎重新生成一份，完了再回去改IMEI那串数字末端试试
> 
> 照您说的做了，如果用账密登录则依旧是版本过低，若扫码则显示风险，我也试了一下用手机号登录，显示的就是'ERR_OUT_OF_RANGE'

那你在自己电脑上部署yunzai然后扫码登陆，登上了把data里生成的token.session复制到服务器对应的文件夹里

**Comment by mingmono** [comment]
> > > 其实改IMEI那一段就行了，你把那个文件删了让云扎重新生成一份，完了再回去改IMEI那串数字末端试试
> > 
> > 
> > 照您说的做了，如果用账密登录则依旧是版本过低，若扫码则显示风险，我也试了一下用手机号登录，显示的就是'ERR_OUT_OF_RANGE'
> 
> 那你在自己电脑上部署yunzai然后扫码登陆，登上了把data里生成的token.session复制到服务器对应的文件夹里

谢谢您的回复，问题已经解决了，解决方法和您回复的方法一样
