### ISSUE TITLE
图片上传失败，reason: 上传遇到网络错误

### ISSUE THREAD

**Issue by BearSword9** [Le-niao/Yunzai-Bot#971]
之前一直没问题，上周全部更新了一下开始出现了报错↓
![QQ截图20221201140523](https://user-images.githubusercontent.com/119561843/204978167-423b021d-bbc9-4065-bcb6-41ec88ad2668.png)

机器人#设置等指令的图片可以正常发出，但是查询角色，面板，配队之类的指令就会出现这个问题

**Comment by Algar233** [comment]
网络问题，更换DNS或者换网

**Comment by BearSword9** [comment]
感谢，确实是家里网络问题，换了几个公共dns也不好使改用手机热点就没问题了。
前几个月没这毛病，不知道是不是最近重庆电信出问题了
