### ISSUE TITLE
无法删除部分隐私数据

### ISSUE THREAD

**Issue by z3052624057** [Le-niao/Yunzai-Bot#973]
对于用户个人而言，用户的隐私数据才是他们最重视的；
而在云仔bot中，一旦用户绑定了自己的UID并且使用#更新面板 命令后，他们的原神角色部分相关数据会被存储到 .\data\UserData 中，而当他们想删除的时候，却无法使用#删除面板 等命令来删除他们的角色数据。
本人UID186167950，曾经多次因为角色面板展示而被拉去PVP。目前本人已经将游戏中的角色数据和米游社数据全部隐藏，但是残留的部分面板信息仍然有时会被群友调出来PVP。对此我已经向多个bot的主人申请删除本人的json文件了，但是很多都以”过于麻烦“等理由拒绝删除。本人在想：既然Cookie命令可以通过指令删除，那么同样是为了隐私保护，面板的json文件（比如.\data\UserData\186167950.json）是否也可以通过指令删除呢？（本人只会Python，所以就先不提交Pr了，望开发者早日上线这个功能，谢谢）

**Comment by WindraiteLesd** [comment]
这个issues不应该去喵喵那里提吗？

**Comment by Georgebillion** [comment]
这貌似要喵喵那边大佬支持吧，跟云崽关系不是很大吧？

**Comment by kikasyou** [comment]
首先这个issue提错项目了，根据功能的描述，你应该去云崽的插件miao-plugin发，这是那个插件提供的功能，而不是本体，建议撤回。而且这个需求....没几个人会有这样的需求，还不如你去跟机器人主人好说好话，发个红包，成年人拿钱办事，让他帮你删了，并不麻烦的。

后面是碎碎念——通过uid，匿名查询角色面板，这在游戏内也是做得到的：按F2，输入uid，就能看到这个人放在“角色展柜”里的角色，如果他还打开了“显示角色详情”，那就能看到圣遗物武器天赋命座等等，这些都是你自己设置的公开啊。不能说你把角色下架了，之前公开过的数据就成了“隐私数据”？我不理解这个逻辑。
