### ISSUE TITLE
qq版本过低

### ISSUE THREAD

**Issue by earthjasonlin** [Le-niao/Yunzai-Bot#978]
今天重启了一下bot，又提示qq版本过低了，12345都试过了

**Comment by AshJordanZhao** [comment]
Yunzai-Bot/data/qq号/device-qq号.json 修改一下IMEI试试，随便换几位数字

**Comment by sah0716** [comment]
换个小号应该可以，我各种登录方式都试了最后还是换个小号登上了

**Comment by earthjasonlin** [comment]
换IMEI可以了，这个真的挺神奇（

**Comment by AshJordanZhao** [comment]
> 换IMEI可以了，这个真的挺神奇（

是的 这个暂时还有效果 我就怕后面IMEI改了也不行就没办法了
什么输入密码用滑动解锁小助手 扫码登陆 开启设备锁 更改设备类型我以前都试过 还是IMEI最有效
