### ISSUE TITLE
建议在face.js中添加“勒”做屏蔽词

### ISSUE THREAD

**Issue by MskTim** [Le-niao/Yunzai-Bot#98]
建议在face.js中添加“勒”做屏蔽词 否则机器人会打出 **勒万岁
![QQ截图20220426211632](https://user-images.githubusercontent.com/87525977/165308461-4c0df0bd-9cb1-42c8-a417-be3200ec529c.png)

**Comment by davidelectricfree** [comment]
这个表情是你群友添加的吧，而且机器人管理员没有审核就放进去了

**Comment by MskTim** [comment]
> 

并不是哦，我配置了百度文字识别的OCR，这是机器人根据群友表情包搜图回对的结果
