### ISSUE TITLE
有没有大佬知道如何停止机器人

### ISSUE THREAD

**Issue by ClaypotRice** [Le-niao/Yunzai-Bot#980]
yunzai的terminal无法输入任何东西。有时候要关闭电脑重启，但点窗口关闭按键会显示未响应。最后还是要强制关闭，这样子操作总感觉会出问题。有没有可以正常关闭机器人的方法。

**Comment by Algar233** [comment]
ctrl+c或者指令#关机

**Comment by 960816102** [comment]
pnpm stop
指令在这。

**Comment by ClaypotRice** [comment]
6
