### ISSUE TITLE
卡池信息错误

### ISSUE THREAD

**Issue by KeyPJ** [Le-niao/Yunzai-Bot#986]
我原打算在自己项目[原神卡池一览](https://github.com/KeyPJ/genshin-gacha-banners)里间接使用这边维护的卡池信息,
详见[这里](https://github.com/KeyPJ/genshin-gacha-banners/blob/7c82c68ea6206f3fcd659ac17fd1558008105190/src/fetchData.js#L65)
结果别人提出了有部分卡池信息错误,主要是部分四星角色或者武器存在重复,例如
https://github.com/Le-niao/Yunzai-Bot/blob/40f365bc1cb6963ca5bd5983e3f7f91eafe7aeda/plugins/genshin/defSet/pool/301.yaml#L57-L59

**Comment by Le-niao** [comment]
多谢更正
